### ISSUE TITLE
Missing indicator.gbif

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#108]
Noticeable on "more images" button

https://www.dropbox.com/s/np5bj9rpe55rlpy/Screenshot%202014-11-06%2012.59.50.png?dl=0

**Comment by nickdos** [comment]
http://biocache.ala.org.au/images/indicator.gif

is the offending URL, called at:
```
<div id="loadMoreImages" style="display:none;">
   <button class="btn">Show more images
       <img style="display:none;" src="/images/indicator.gif"/>
    </button>
</div>
```

**Comment by nickdos** [comment]
Might need to check this when deployed. Seems like it may have been "fixed" in prod but still broken in dev mode. Re-open if this is the case and my change reverted the previous change. I did test running my app as "grails prod run-war" but its no guarantee.
