### ISSUE TITLE
Typo at "Original versus Processed" Comparison Table

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/biocache-hubs#110]
On the "Original versus Processed" Comparison Table in occurrence view, Class is misspelled as  *Classs* .

**Comment by nickdos** [comment]
"classs" value is coming from biocache-service:

http://biocache.ala.org.au/ws/occurrence/compare?uuid=10ff70a3-7088-44c6-9cea-95ccd9299ba5

Might be a reserved word workaround (usually as clazz)? Moving to biocache-service.

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/biocache-service#36
