### ISSUE TITLE
Observers list is populated as original values.

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/biocache-hubs#120]
As seen in the below, the observers/collectors list is as its original value:
![image](https://cloud.githubusercontent.com/assets/1578598/6406698/0619f7f2-be88-11e4-9725-24ec8b9c5bc5.png)

It would be great enhancement to parse them and store them separately. Then it will be possible to look for all the records for a single person by selecting him instead of selecting all of his collector groups.

**Comment by Tasilee** [comment]
I fully agree with that strategy as it would also identify a stack of variants that we may be able to resolve over time.

**Comment by nielsklazenga** [comment]
I agree too, as long as the original values remain indexed as well. In AVH, the order of the collectors (recorders) matters, so we would like to keep the provided strings, but if we could also facet on individual collectors and, besides the occurrence records, also get the facet with all groups of which the collector has been part of (so we can drill down further) that would indeed be a nice enhancement.

**Comment by djtfmartin** [comment]
The collector names are parsed and stored in a pipe separated list. This is visible on an index page but isnt indexed currently. It was done as part of the duplicate detection work.

**Comment by nickdos** [comment]
might put this on hold until we've got SOLR cloud working with 3+ shards, then we'll have a better chance of handling a bigger index.
