### ISSUE TITLE
No records in the data resource page doesn't show up correctly 

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/biocache-hubs#121]
In the data resource page (e.g http://collections.ala.org.au/public/show/dr2225 ), if there is no record available, it shows :

  [collectory.js.norecord] can be accessed through 

![image](https://cloud.githubusercontent.com/assets/1578598/7172469/b087a428-e42b-11e4-99d2-ca1238d70cd0.png)

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/collectory-plugin#56
