### ISSUE TITLE
Print CSS file needed

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#123]
Printing results page is a mess. Needs a separate print.css file to hide most of the divs so we just get the results list and search meta data.
Should also work with record pages.

**Comment by nickdos** [comment]
List and record pages and maybe `explore/your-area`

**Comment by nickdos** [comment]
Has dependency on this related issue https://github.com/AtlasOfLivingAustralia/front-end-static/issues/3

**Comment by temi** [comment]
also, added temporary print rules to ala-bootstrap2, ala-bootstrap3 and ala-wordpress-theme to hide some footer elements.
