### ISSUE TITLE
Consistent lat/long display (minor issue)

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#124]
LatLong in the spatial select tool looks like this (nice)

![screenshot 2015-05-27 10 47 16](https://cloud.githubusercontent.com/assets/444897/7833339/f275de16-045d-11e5-962f-5708ece0d7ef.png)

while in the main map tool (not so nice)

![screenshot 2015-05-27 10 47 09](https://cloud.githubusercontent.com/assets/444897/7833346/fc089c34-045d-11e5-9830-c819a2c5eaab.png)

**Comment by nickdos** [comment]
Different emphasis for the 2 maps... first map requires prompts as its the main function/purpose of the map. The second is the map display for the results and most users will not be needing to restrict via polygon, so showing prompts would be distracting and even confusing. The idea is that users would "learn" how to use the function from the first map and then its not required on the second. 

Maybe we should show the same prompts on "hover" on the second map, as opposed to having the prompt displayed automcatically/all the time... I'll try this first...

**Comment by nickdos** [comment]
Oops didn't read text - thought this was about the help thingy.  Leaflet issue so deal with this when in the leaflet code
