### ISSUE TITLE
Implement name autocomplete service

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#128]
_From @nickdos on June 18, 2015 2:56_

Currently in the biocache-hubs, autocomplete is tied to the ALA BIE service.

With more external users running biocache, there is a need to provide the autocomplete service for just the data coming from biocache-service. biocache-service is already doing names lookups via the lucene index, so it should be possible to produce an aucomplete lookup service, similar to that provided by the BIE.

APPD would benefit from this.

_Copied from original issue: AtlasOfLivingAustralia/biocache-service#53_

**Comment by nickdos** [comment]
Not sure why this has been moved unless it has been implemented in biocahe-service already... Has it?

**Comment by nickdos** [comment]
Is dependent on https://github.com/AtlasOfLivingAustralia/biocache-service/issues/53
