### ISSUE TITLE
Image metadata display

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#129]
_From @M-Nicholls on June 17, 2015 23:39_

When displaying images show creator, rights, rightsHolder and license with information drawn from the image metadata (rather than the occurrence record)

_Copied from original issue: AtlasOfLivingAustralia/biocache-service#52_

**Comment by djtfmartin** [comment]
_From @M-Nicholls on June 18, 2015 6:37_

test records: http://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr2326

**Comment by nickdos** [comment]
Its not clear to me whether the `creator, rights, rightsHolder` and `license` data is coming from biocache-service in the record JSON payload or whether biocache-hubs needs to make a separate web service call to image-service to display this info?

**Comment by djtfmartin** [comment]
I think biocache-hubs will need to make a separate call to the image-service (in the instances where we are using an image service).

**Comment by nickdos** [comment]
OK - thinking more long term I'd hope that this data is embedded in biocache and indexed so people can filter/facet on license type and users of our web services can access this data as well. To me it seems essential info to provide.

**Comment by djtfmartin** [comment]
Agree that might be useful, but that would be non-trivial to do with the current architecture. We would need to redundantly store all image metadata in the cassandra and deal with multiple images per record in cassandra with different metadata per image. Calling out to a webservice  at index time would kill indexing performance.

**Comment by djtfmartin** [comment]
There would also be some major changes to the SOLR index to support nested objects.

**Comment by nickdos** [comment]
Maybe a first step could be adding the info into the existing JSON array:
```
images: [
{
  alternativeFormats: {
    imageUrl: "http://images.ala.org.au/image/proxyImage?imageId=a532af05-0c47-4a5a-a401-58172831f507",
    thumbnailUrl: "http://images.ala.org.au/image/proxyImageThumbnail?  imageId=a532af05-0c47-4a5a-a401-58172831f507",
    largeImageUrl: "http://images.ala.org.au/image/proxyImageThumbnailLarge?imageId=a532af05-0c47-4a5a-a401-58172831f507",
    smallImageUrl: "http://images.ala.org.au/image/proxyImageThumbnail?imageId=a532af05-0c47-4a5a-a401-58172831f507"
  },
  filePath: "a532af05-0c47-4a5a-a401-58172831f507"
}
],
```
and leave indexing to a SOLR refactor?

**Comment by djtfmartin** [comment]
It still will require a call out to the image service. The biocache can do this, but this easily done via ajax against the existing image-service services...

e.g. taking the "filePath" in the example above:

http://images.ala.org.au/ws/image/a532af05-0c47-4a5a-a401-58172831f507

I'd be tempted just to load from the image-service directly via ajax. The image service already has CORS support:

https://github.com/AtlasOfLivingAustralia/image-service/blob/master/grails-app/conf/BuildConfig.groovy#L69
