### ISSUE TITLE
Link up transcriber number to user name for DigiVol records

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#132]
Transcriber field is just showing a user ID number. This should be do a lookup to user name in AUTH ~~and also be linked back to user's page in VP/DigiVol~~ (not currently possible due to VP using internal IDs for users)

http://biocache.ala.org.au/occurrences/703787e0-c34c-4fe5-9fd7-f1f9cdf68215

**Comment by djtfmartin** [comment]
The VP __is__ now using ALA ids so this can be done now with a lookup against auth.

e.g. from this example:

- the task http://volunteer.ala.org.au/task/show/7273620
- the transcriber ID - 892
- https://auth.ala.org.au/userdetails/admin/user/show/892
