### ISSUE TITLE
Facet list not loading

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#133]
As reported in support email, the full list of facets is not loading.

![image](https://cloud.githubusercontent.com/assets/444897/8589856/98fb457a-2612-11e5-82ed-7b1f6cdecda2.png)

I think this is connected with the recent changes to customise the facet list using an external config file local to the hub.

I've temporarily removed this from biocache.ala.org.au

**Comment by djtfmartin** [comment]
Addendum - using the "clear caches" function in the admin tool doesnt resolve the problem

**Comment by nickdos** [comment]
I see you commented out the `biocache.groupedFacetsUrl=file:///data/ala-hub/config/grouped_facets_ala.json` line in config file. I assume that was for this issue? Do you think this is the cause?

**Comment by nickdos** [comment]
Have not seen since deploying the change described by Dave. Will close but feel free to re-open if this pops up again.
