### ISSUE TITLE
Expose species subgroups in EYA

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#134]
EYA should expose subgroups in the same way the regions and mobile apps do

See https://github.com/AtlasOfLivingAustralia/biocache-store/issues/44 for more details

**Comment by nickdos** [comment]
I'm not keen on this idea. Here's why:
* this a simple, easy to use tool and adding subgroups will add a significant level of complexity
* list of groups will become way too long and subgroups will require a hide/show widget which complicates UI 
* no one has requested this from outside ALA that I know of
* it adds little value for the way the tool is used (my opinion) - bird groups and mammal groups will be slightly easier to navigate but requires knowledge of the subgroup names - which are not intuitive and requires basic zoological/botanical knowledge - not who this page is catered for.

**Comment by djtfmartin** [comment]
This has been requested many times by John La Salle. Its probably worth a chat with John and also Taryn as I think this is used in education materials.

I think it does add value. If i select an area in Canberra and just have a interest in parrots, I typically have to page through 7-8 "show more" before i find all the taxa.

Its also possibly not great that we are using one breakdown in regions.ala.org.au + mobile and another in EYA.

**Comment by nickdos** [comment]
Fair enough... if John has requested this then its worth giving a go. Might be a chance to make some design changes anyway... Will keep this for the upcoming sprint.
