### ISSUE TITLE
IBRA and IMCRA facets no longer working

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/biocache-hubs#135]
Need to modify the Advanced Search and Facet definition code so that it references the "cl1048" (ibra) and "cl21" fields rather than the previous "ibra" and "imcra" fields.  In files:
biocache-hubs/src/groovy/au/org/ala/biocache/hubs/AdvancedSearchParams.groovy,
biocache-hubs/grails-app/views/home/_advanced.gsp
and
biocache-hubs/src/groovy/au/org/ala/biocache/hubs/FacetsName.groovy

Possibly could investigate moving facet names to a config file...

**Comment by Tasilee** [comment]
Agreed. IBRA 7 and IMCRA 4 are the latest and justifiable as 'facets', see https://github.com/AtlasOfLivingAustralia/biocache-service/issues/30

**Comment by nickdos** [comment]
Fixed in commit d830bc89f514f4c865ef740dc67f32962d1d8440
