### ISSUE TITLE
Habitat and mixing Occurrence and Profile data

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/biocache-hubs#136]
The use of the word "habitat" to indicate whether something is marine or not has always been a thorn in the eye, but that was just a label and you didn't have to display the filter if you didn't want to see it. Some time ago, however, I noticed that on the Occurrence detail pages 'Habitat' for the far majority of AVH records is given as 'Terrestrial', with the actual habitat information, if provided, given after 'Supplied as", which is pretty unacceptable data tampering.

The marine/non-marine distinction is not 'habitat' and 'terrestrial' may mean 'occurring on land' when it is set off against 'marine', but in the context of habitat it means something completely different, namely 'growing on the ground' – and not in a tree or on a rock etc. Ornithologists should be up in arms about this, if they have been paying attention.

The bigger issue here is that Profile data is presented as processed Occurrence data. Profile data is based on Occurrence data and therefore replacing the provided Occurrence data with Profile data is circular, unscientific and misleading.

I suspect that if I do a spatial analysis, I'll find that things marine will generally occur in the sea, but there will be other Profile data that is more useful to have in the Biocache. When that is done, the Profile information should be clearly separated from the Occurrence data, just like the political boundaries and environmental data is now (and even that could be done a bit more clearly).

I am only assuming the 'Terrestrial' comes from the same source as the 'Species habitats' filter, as I don't know where else it could come from. The 'Non-marine' in that filter, however, is way preferable over 'Terrestrial', but I guess sounds less habitatty, so why not remove it from the Occurrence detail page altogether and move the provided habitat information up to where the other provided information is?

When putting Profile data into the Biocache, as far as I can see, [`dwc:habitat`](http://rs.tdwg.org/dwc/terms/habitat) is the only term for which there will be a conflict between Profile and Occurrence data. There should be separate "fields" in the BioCache for both uses. However, in a Profile, `habitat` should be used for terms from the [IUCN Habitat Vocabulary](http://rs.gbif.org/vocabulary/iucn/habitat.xml), or, preferably, from a more fine-grained, possibly Australian, vocabulary that doesn't exist yet. For the stuff that is currently in `species_habitats`, the terms [`isMarine`](http://rs.gbif.org/terms/1.0/isMarine), [`isTerrestrial`](http://rs.gbif.org/terms/1.0/isTerrestrial) and [`isFreshwater`](http://rs.gbif.org/terms/1.0/isFreshwater) should be used.
.

**Comment by nickdos** [comment]
This is a data processing issue so will move it to biocache-store.

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/biocache-store#73
