### ISSUE TITLE
Legend never loads on maps

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#138]
http://biocache.ala.org.au/occurrences/search?taxa=kangaroo#tab_mapView

<img width="1189" alt="screenshot 2015-08-13 20 16 09" src="https://cloud.githubusercontent.com/assets/444897/9259314/42d0f7b0-41f8-11e5-8a11-d9497304fb18.png">

**Comment by nickdos** [comment]
I think this might've been another knock-on effect of the network outage on Friday. Works fines for me now:
![image](https://cloud.githubusercontent.com/assets/532845/9298377/48347d34-44f1-11e5-8332-40b4ea511096.png)
