### ISSUE TITLE
WMS service ENV colormode "decade" facet not working

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#139]
_From @nickdos on September 8, 2014 6:8_

The decade facet is non-standard as it appears to be a synonym or "special" facet name (not sure exactly). the WMS service will not show any dots for a search when "decade" is used. 

E.g. the equivilent "year" colormode gives:

http://biocache.ala.org.au/ws/webportal/wms/reflect?q=lsid%3Aurn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3Ae9e7db31-04df-41fb-bd8d-e0b0f3c332d6&fq=family%3AEQUIDAE&fq=state%3A%22Victoria%22&SERVICE=WMS&REQUEST=GetMap&VERSION=1.1.1&LAYERS=ALA%3Aoccurrences&STYLES=&FORMAT=image%2Fpng&TRANSPARENT=true&HEIGHT=256&WIDTH=256&BGCOLOR=0x000000&OUTLINE=true&ENV=colormode%3Ayear%3Bname%3Acircle%3Bsize%3A4%3Bopacity%3A1&STYLE=opacity%3A0.8&SRS=EPSG%3A3857&BBOX=15967389.460660176,-4383204.9499851465,16280475.52851626,-4070118.8821290643

but change it to decade and it returns no dots:

http://biocache.ala.org.au/ws/webportal/wms/reflect?q=lsid%3Aurn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3Ae9e7db31-04df-41fb-bd8d-e0b0f3c332d6&fq=family%3AEQUIDAE&fq=state%3A%22Victoria%22&SERVICE=WMS&REQUEST=GetMap&VERSION=1.1.1&LAYERS=ALA%3Aoccurrences&STYLES=&FORMAT=image%2Fpng&TRANSPARENT=true&HEIGHT=256&WIDTH=256&BGCOLOR=0x000000&OUTLINE=true&ENV=colormode%3Adecade%3Bname%3Acircle%3Bsize%3A4%3Bopacity%3A1&STYLE=opacity%3A0.8&SRS=EPSG%3A3857&BBOX=15967389.460660176,-4383204.9499851465,16280475.52851626,-4070118.8821290643

This is breaking the biocache search map when colour_by = decade.

_Copied from original issue: AtlasOfLivingAustralia/biocache-service#4_

**Comment by nickdos** [comment]
_From @adam-collins on September 9, 2014 23:28_

SP deals with decade by using occurrence_year and specifying the min max filter pairs required to return each decade.  SP only requests decades that have occurrences for the query but a listing of min max filter pairs for all valid decades would do much the same.

An example, missing some decades.
colormode%3Aoccurrence_year%2C*%2C1859-12-31T00%3A00%3A00Z%2C1880-01-01T00%3A00%3A00Z%2C1889-12-31T00%3A00%3A00Z%2C1890-01-01T00%3A00%3A00Z%2C1899-12-31T00%3A00%3A00Z%2C1900-01-01T00%3A00%3A00Z%2C1909-12-31T00%3A00%3A00Z%2C1910-01-01T00%3A00%3A00Z%2C1919-12-31T00%3A00%3A00Z%2C1920-01-01T00%3A00%3A00Z%2C1929-12-31T00%3A00%3A00Z%2C1930-01-01T00%3A00%3A00Z%2C1939-12-31T00%3A00%3A00Z%2C1940-01-01T00%3A00%3A00Z%2C1949-12-31T00%3A00%3A00Z%2C1950-01-01T00%3A00%3A00Z%2C1959-12-31T00%3A00%3A00Z%2C1960-01-01T00%3A00%3A00Z%2C1969-12-31T00%3A00%3A00Z%2C1970-01-01T00%3A00%3A00Z%2C1979-12-31T00%3A00%3A00Z%2C1980-01-01T00%3A00%3A00Z%2C1989-12-31T00%3A00%3A00Z%2C1990-01-01T00%3A00%3A00Z%2C1999-12-31T00%3A00%3A00Z%2C2000-01-01T00%3A00%3A00Z%2C2009-12-31T00%3A00%3A00Z%2C2010-01-01T00%3A00%3A00Z%2C2019-12-31T00%3A00%3A00Z

Alternatively, can look at making an actual decade field in the index.

**Comment by nickdos** [comment]
OK fix is to change from "decade to "occurrence_year" - moving to hubs...

**Comment by djtfmartin** [comment]
I think a decade field in the index will make lives easier.

**Comment by nickdos** [comment]
Waiting for `occurrence_decade_i` to be available in prod... should be minor fix then.
