### ISSUE TITLE
Fish or Fishes

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#14]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=98
*date:* Thu Aug  8 16:27:28 2013
*author:* moyesyside
 ---

Original Issue reported by Reported by john.t...@austmus.gov.au, Today (16 hours ago) - [https://code.google.com/p/ala-portal/issues/detail?id=300](https://code.google.com/p/ala-portal/issues/detail?id=300)

Reported by john.tann@austmus.gov.au, Today (16 hours ago) 
I have been told that when we refer to 'fish' as a lifeform we should use the word 'fishes'
See [http://australianmuseum.net.au/fish-and-fishes](http://australianmuseum.net.au/fish-and-fishes)

The word 'fish' should be changed to 'fishes' when referring to a lifeform.

**What steps will reproduce the problem?**
An example:
Australian Museum Ichthyology collection. in the graph of records by higher level group:  
Axis is Arthropods Fish Insects Reptiles

**What is the expected output? What do you see instead?**
Axis is Arthropods ***Fishes*** Insects Reptiles 

What version of the product are you using? On what operating system?
2013

Please provide any additional information below.
The term 'fish' is probably incorrectly used in a bunch of places.

This is a low priority fix.
 fish or fishes.png 4.7 KB   View   Download

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/biocache-service#13
