### ISSUE TITLE
Flag an issue - not accepting comments

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#140]
_From @johntann99 on August 16, 2015 22:15_

When a user attempts to Flag-an-issue, SUBMIT action does not function.

_Copied from original issue: AtlasOfLivingAustralia/biocache-service#62_

**Comment by nickdos** [comment]
Fixed via config change for AUTH - gateway=false.

**Comment by nickdos** [comment]
AN AVH users has reported the flag an issue function as being patchy. It works sometimes but not others. I note that "gateway=false" for AVH, so it appears there is something else going on.

Needs further investigation.

**Comment by nickdos** [comment]
Seeing this error in JS console in Chrome:

> XMLHttpRequest cannot load https://auth.ala.org.au/cas/login?service=http%3A%2F%2Fbiocache.ala.org.au%2Foccurrences%2Fassertions%2Fadd. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://biocache.ala.org.au' is therefore not allowed access.

**Comment by nickdos** [comment]
Putting this in "waiting for" column to see if we get any more reports. If not will close.

**Comment by ansell** [comment]
I can also replicate it.

The log file on the server doesn't contain specific details about where the error is coming from internally:

```
2019-01-17 15:36:21.159 DEBUG --- [o-8080-exec-875] a.o.a.c.util.AuthenticationCookieUtils   : Cookie ALA-Auth found
2019-01-17 15:36:21.159 DEBUG --- [o-8080-exec-875] a.o.a.c.util.AuthenticationCookieUtils   : Cookie ALA-Auth found
2019-01-17 15:36:21.233 ERROR --- [o-8080-exec-875] g.a.s.a.o.a.b.hubs.WebServicesService    : POST - Unexpected error: 400 : Bad Request
2019-01-17 15:36:21.233 ERROR --- [o-8080-exec-875] g.a.c.a.o.a.b.hubs.AssertionsController  : Unexpected error: 400 (java.lang.Integer) : Bad Request
```

It is returning HTTP 400, confirmed with the nginx log file and the browser dev tools

```
[REDACTED] - - [17/Jan/2019:15:36:21 +1100] "POST /occurrences/assertions/add HTTP/1.1" 400 21 "https://biocache.ala.org.au/occurrences/b1a004d9-8d0d-42be-9445-cdcc053e53bd" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:64.0) Gecko/20100101 Firefox/64.0" "[REDACTED]" request_time=0.075 upstream_response_time=0.075 upstream_connect_time=0.000 upstream_header_time=0.075 upstream_cache_status=-
```

The parameters that were in the POST request (in my repetition) were:

param | value
-- | --
recordUuid | b1a004d9-8d0d-42be-9445-cdcc053e53bd
code | 0
comment | Report+from+a+user+to+the+support+email+address+that+this+record+"should+map+to+Mt+Lindesay+in+the+border+ranges+of+NSW+rather+than+in+the+Tamworth+region."
userAssertionStatus | Open+issue
userId | 27583
userDisplayName | Peter+Ansell

The code of `0` looks correct:

https://github.com/AtlasOfLivingAustralia/biocache-store/blob/master/src/main/scala/au/org/ala/biocache/vocab/AssertionCodes.scala#L15

**Comment by ansell** [comment]
All three of the annotations that were attempted yesterday on https://biocache.ala.org.au/occurrences/b1a004d9-8d0d-42be-9445-cdcc053e53bd are currently visible on the record page so the annotations were not completely disappeared by the error during indexing.

**Comment by ansell** [comment]
Another helpdesk ticket referencing this, number 27612

**Comment by ansell** [comment]
Flag an issue is working again. I will open a new issue on biocache-store describing the link between the stacktrace above and the workflow for resampling/reindexing/annotations and at what points annotations can show the failure message, but be visible after either one or two more reindexes, which could be up to 1 week after the annotation was made.

**Comment by nickdos** [comment]
Still happening, reopening

**Comment by timhicks-ala** [comment]
Raised in helpdesk ticket 98084

**Comment by nickdos** [comment]
@alexhuang091 we've had a few helpdesk requests for this problem. The user gets an error when submitting the annotation but it turns out the annotation is saved and displays on nex reload of page. Users thinks it failed though and auto-page refresh does not happen.

**Comment by alexhuang091** [comment]
> @alexhuang091 we've had a few helpdesk requests for this problem. The user gets an error when submitting the annotation but it turns out the annotation is saved and displays on nex reload of page. Users thinks it failed though and auto-page refresh does not happen.

I'll have a look at it ASAP.

**Comment by timhicks-ala** [comment]
Raised additionally in https://support.ehelp.edu.au/a/tickets/107689 and https://support.ehelp.edu.au/a/tickets/107343 - in the latter case, the user flagged an issue on a record, and saw an error: "There was problem flagging the issue. Please try again later." However, the record was successfully annotated: https://avh.ala.org.au/occurrences/dada29f2-3562-48f9-ad1f-d295a7ff817b

@alexhuang091 an example to look into.

**Comment by alexhuang091** [comment]
When I used `ThreadPoolExecutor` in pipeline project to limit the max co-current thread number to 1 I ran across same exception when new request comes while a thread in pool is running

`Task au.org.ala.biocache.service.AssertionService$$Lambda$44/1833416613@77a51e41 rejected from java.util.concurrent.ThreadPoolExecutor@7962eec5[Running, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]",`

The exception type is `RejectedExecutionException`

This error looks same as what we saw when assertion error happens. Same exception type, same form of error message.

<img width="1792" alt="截屏2021-05-10 下午4 52 46" src="https://user-images.githubusercontent.com/61677987/118921516-a5e07a00-b97b-11eb-91af-f2fb9d898f30.png">

Then I guess a similar ThreadPool is used in solrClient to sent requests to solr server and I found in Biocache-store/SolrIndexDAO.scala

`solrServer = new ConcurrentUpdateSolrClient.Builder(solrHome).withThreadCount(Config.solrUpdateThreads).withQueueSize(BATCH_SIZE).build()`

In the `ConcurrentUpdateSolrClient.Builder`

```
@Deprecated
public ConcurrentUpdateSolrClient(String solrServerUrl, HttpClient client, int queueSize, int threadCount, ExecutorService es, boolean streamDeletes) {
    this.scheduler = ExecutorUtil.newMDCAwareCachedThreadPool(new SolrjNamedThreadFactory("concurrentUpdateScheduler"));
    this.shutdownExecutor = true;
}

public static ExecutorService newMDCAwareCachedThreadPool(ThreadFactory threadFactory) {
    return new MDCAwareThreadPoolExecutor(0, Integer.MAX_VALUE,
        60L, TimeUnit.SECONDS,
        new SynchronousQueue<Runnable>(),
        threadFactory);
}

public static class MDCAwareThreadPoolExecutor extends ThreadPoolExecutor {
      public MDCAwareThreadPoolExecutor(int corePoolSize, int maximumPoolSize, long keepAliveTime, TimeUnit unit, BlockingQueue<Runnable> workQueue, ThreadFactory threadFactory, RejectedExecutionHandler handler) {
          super(corePoolSize, maximumPoolSize, keepAliveTime, unit, workQueue, threadFactory, handler);
    }
}

```

So eventually in solrClient we have a ThreadPollExecutor by 
```
(0, Integer.MAX_VALUE, 60, TimeUnit.SECONDS,
        new SynchronousQueue<Runnable>(), SolrjNamedThreadFactory("concurrentUpdateScheduler"))
```

Which I think can queue infinite jobs.

When building solrClient we can also see
`ConcurrentUpdateSolrClient.Builder(solrHome).withThreadCount(Config.solrUpdateThreads)`, this **`threadcount`** is set to 4. I'm not sure yet how it works with thread pool but definietly error happens in solr client (so in biocache-service side).



By the way, addUserAssertion internally does 2 things.
1. add user assertion into Cassandra database
2. re-index corresponding doc in solr (in this step an exception occurs)

The result is solr doc is NOT updated properly.

But if there's a weekly task run scheduled to re-index everything then the only impact is, re-index is not on time. It eventually will be updated by the scheduled task.

@djtfmartin Comments welcomed for the ThreadPoolExecutor.

**Comment by nickdos** [comment]
Hit a bug that could be related (create new issue of not). When I click the `Flag an issue` button I see this popup:

![image](https://user-images.githubusercontent.com/532845/130729250-a167da70-e366-4dc6-b56f-ff376a86e447.png)

When I click the link `click here`, the page reloads but nothing changes. I'm not logged in and same popup appears.

That link looks OK so wondering why it doesn't log me in?

https://auth-test.ala.org.au/cas/login?service=https://biocache-test.ala.org.au/occurrences/d6f4fe0f-b360-4fb6-95d6-549de5e9a346

**Comment by alexhuang091** [comment]
Hi Nick, I've been complaining this issue to a lot of people since data-quality project. But seems only I met this issue.

After click `login`, input usrname+password, I still see the `login`


---
My solution:
1. click the `sign up`, or go to the footer, click `sign in` there so you are prompt to login to `auth`, then you'll be logged in
<img width="342" alt="Screen Shot 2021-08-25 at 3 04 45 pm" src="https://user-images.githubusercontent.com/61677987/130729765-8b13b95c-2408-4b1f-b0e0-21aab0ca1396.png">

**Comment by nickdos** [comment]
I don't think that is the issue - I see "logout" and "Profile" buttons on the search page, just not on record view/page.

**Comment by timhicks-ala** [comment]
Hi @nickdos - can this one be revisited in Alex's absence?

**Comment by nickdos** [comment]
Hi @timhicks-ala - can you paste link to support ticket pls?

**Comment by timhicks-ala** [comment]
@nickdos - I believe these two are the only open ones relating to this issue:
https://support.ehelp.edu.au/a/tickets/92259
https://support.ehelp.edu.au/a/tickets/107689

Another four in history appear to have been closed when the issue seemed resolved for each user:
https://support.ehelp.edu.au/a/tickets/27529
https://support.ehelp.edu.au/a/tickets/27612
https://support.ehelp.edu.au/a/tickets/98084
https://support.ehelp.edu.au/a/tickets/107343

**Comment by nickdos** [comment]
One of the open ones is for verifcation and I've got 2 open tickets for that in my list. Dave tracked that down to the collectory `contacts.json` not working and we should get that out next week. The other one is similar to the older tickets and seems to be the random `"There was problem flagging the issue. Please try again later."` issue that I've not been able to replicate. 

I suspect it might be a case of the user loading the page up and leave it as an open tab/window for _N_ days and then coming back and clicking the "flag an issue" button (JS code runs) and then the POST fails due to the login session having expired. Usually reloading the page and trying again works.
