### ISSUE TITLE
Record issues facet is not showing

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/biocache-hubs#151]
Record issues facet is not showing. I tried in both BioCache and AVH.

**Comment by nickdos** [comment]
Probably a config issue. Appears to be present in both ALA and AVH now:

![image](https://cloud.githubusercontent.com/assets/532845/20205198/fcec0f10-a82a-11e6-914e-52da9a0e148f.png)

**Comment by nielsklazenga** [comment]
Yup, I can see it now too.
