### ISSUE TITLE
Searching by catalog number

### ISSUE THREAD

**Issue by santiagomtzdelariva** [AtlasOfLivingAustralia/biocache-hubs#152]
I put these two catalog numbers, one per line, and the result is this:

OPP570042-8 - 7ba37098-3751-4e49-8cec-127a001d15e5 (ID)
OPP567978-5 - 0151a9c2-02f6-434e-ba86-3f9154bc4a0d

http://biocache.ala.org.au/ws/occurrences/batchSearch

{
"message": "Request method 'POST' not supported", "errorType": "Server error"
}

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/biocache-service#69
