### ISSUE TITLE
Batch taxon search doesn't work

### ISSUE THREAD

**Issue by santiagomtzdelariva** [AtlasOfLivingAustralia/biocache-hubs#153]
I have tried with: Rosa canina

And I always the same result: 

{
"message": "Request method 'POST' not supported", "errorType": "Server error"
}

I've seen that this functionality works in the ALA portal. It seems that in the process creates a "Occurrence query cache": http://biocache.ala.org.au/occurrences/search?q=qid:1442490757647

Is it possible that this functionality is turned off?

**Comment by nickdos** [comment]
This looks like a biocache-service issue. The batch taxon search does a POST to 

http://biocache.ala.org.au/ws/occurrences/batchSearch

which is handled by:

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/d4c0bc0131d853399a3b31b4cd6aa4029501b6b8/src/main/java/au/org/ala/biocache/web/OccurrenceController.java#L704

```java
@RequestMapping(value = "/occurrences/batchSearch", method = RequestMethod.POST, params="action=Download")
```

straight from the form on the page, so I'd try debugging that endpoint as a first step.
