### ISSUE TITLE
Allow search 'as-processed' or 'as-supplied'

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/biocache-hubs#155]
# Background

A request from APNI/APC. At the moment, someone in a herbarium may have a sample with a label in front of them. If they put the name on the label in the search bar, they may not find the occurrence, since it has been either matched to a higher taxon, soundex matched or otherwise processed.  At this point, they phone APNI.

The information they're seeking is in the occurrence record but it tends to be a bit hard to access.
# Use Case

An option to search for terms on an as-supplied, rather than an as-processed basis. As well as names, this should apply generally so that things like the decimal latitude, collector/observer, date and so on can be entered as shown on the label.

**Comment by nielsklazenga** [comment]
Non-starter, I think.

The names that are provided by the herbaria are not necessarily the names that are on the labels, so I am not sure this will resolve anything. I would like the parsed (partly processed) names, before they are matched to APC/AFD, to be indexed. That would help with matching of names in the biocache to names in external applications, which might employ a different taxonomy.

Dates that are delivered are never the dates that are on the labels, as the dates delivered are ISO 8601 and dates on labels are not. At least herbaria will not generally deliver `verbatimEventDate` for complete dates and they will generally deliver `verbatimEventDate` in ISO 8601 (or HISPID format) for incomplete dates. We tend to not even database truly verbatim event dates if they can be converted to ISO 8601.

Collectors are not being processed in ALA, apart from strings with multiple collectors being split up. Herbaria deliver ABCD, which have the collectors already split up; they are just concatenated in the AVH aggregator to transform them to Darwin Core `recordedBy`. Again, the provided string is not what people get to see on the label.

All herbaria (I think), except MEL, use sexagesimal latitudes and longitudes on the labels while providing decimal ones.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
