### ISSUE TITLE
Batch taxon search - add toggle for synonym matching

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#160]
Currently the batch taxon search form uses the `raw_name` field for each name entered.  I have feeling this was for AVH users. But general ALA users have found it confusing when the batch taxon search gives different results than the simple search (feedback via support email).

Suggest a "toggle" switch is added above the form to specify if `raw_name` or `taxa` field is used to `AND` the names in the form.

**Comment by nielsklazenga** [comment]
I think it is confusing as well. It will be good to have both options.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
