### ISSUE TITLE
customisable field list for downloads

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#17]
_migrated from:_ https://code.google.com/p/ala/issues/detail?id=117
_date:_ Thu Aug  8 16:35:29 2013
_author:_ moyesyside

---

Original Issue reported by Project Member Reported by milo_nic...@hotmail.com, Oct 11, 2012 - [https://code.google.com/p/ala-portal/issues/detail?id=285](https://code.google.com/p/ala-portal/issues/detail?id=285)

Project Member Reported by milo_nicholls@hotmail.com, Oct 11, 2012 
Add a field picker to allow users downloading a data set to choose the fields included

**Comment by nickdos** [comment]
Some ideas:
 * of 500,000 records
 * might need to replace popup (modal) with separate (new) page with all these options. Advantage of this is the page can be called from other apps (like regions.ala.org.au)
 * fields picker could be grouped to categories of fields that can be collapsed as a group?

**Comment by M-Nicholls** [comment]
See - https://github.com/AtlasOfLivingAustralia/data-management/issues/9
