### ISSUE TITLE
Rename headings on record page

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#172]
Suggested by Lee:

>  I was looking at some records in the ALA and AVH and noted that the headers for the intersections of records with our spatial layers are not good (in one case wrong). See below (one image from 'AVH' and one from ALA).
> 
> Could I suggest that you use
> 
> Environmental classes at this location
> Environmental values at this location
> 
> instead of 
> 
> Additional political boundaries information
> Environmental sampling for this location

**Comment by nickdos** [comment]
Will park this issue for now - makes sense to look at a bunch of issues like this during a review phase of work...

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
