### ISSUE TITLE
Add dymanic facets to ALA biocache via request param

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#174]
In order to answer some support calls, we need to be able to generate a URL that will show a non-standard facet in the UI, which is normally not used. 

Suggest we use the `facets` param as a comma separated list of additional facets to display (similar to the WS). These extra facets should appear in the "Miscellaneous" section of the facets menu.

**Comment by nielsklazenga** [comment]
That would be great to have, not just for support calls.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
