### ISSUE TITLE
using qc parameter in biocache causes JS error

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocache-hubs#176]
example:
http://biocache.ala.org.au/occurrences/search?taxa=acacia&qc=cl22:%22New%20South%20Wales%22

Cause:
qc is not url encoded. this causes a string literal to prematurely close.

**Comment by nickdos** [comment]
On reflection, the `qc` param should be hidden from the user and only used by "hubs". So i'm going to mark this as "won't fix" for now.
