### ISSUE TITLE
Sorting of facet values fails for some fields

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#177]
Fields that have a different `value` to their `label` do not sort as the user would expect when viewing the "show more..." popup modal. Examples of such fields are `user`, `data provider`, `data resource`, `dataset`.

E.g. data resource facet shows:

![search__text_sightings___occurrence_records___atlas_of_living_australia](https://cloud.githubusercontent.com/assets/532845/14663827/1df1cbec-0708-11e6-8dc4-fd5805265220.png)

when sorting on the first column - it's actually sorting on `data_resource_uid` in this case.

Only fix I can think of is to use the non-code versions of the field (won't work for userId) or to disable sorting for the few fields that this applies to... Suggestions welcome

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
