### ISSUE TITLE
Default "contact curator" email - change from Dave Martin

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#179]
Record page has a "contact curator" on left hand side. For many non-collection based datasets, this button shows Dave Martin as the contact (e.g. ALA sightings). This should be changed to be the data management team and provide a general ALA phone number (same as web site).

**Comment by ansell** [comment]
Is this an issue of having to modify the collectory database (MySQL?) in bulk to do the switch?

**Comment by ansell** [comment]
The current code here in biocache-hubs seems to be as follows:

https://github.com/AtlasOfLivingAustralia/biocache-hubs/blob/76d6a2fca8f52cf04544401edd14a3bbeeaff060/grails-app/views/occurrence/_recordSidebar.gsp#L207

That doesn't seem to have a default case here in biocache-hubs so it may be that Dave Martin has been assigned explicitly as a contact by the collectory or another set of scripts in these cases

The contacts array is derived from the following code that also doesn't seem to have a default value applied if both collection and dataResource do not have contacts:

https://github.com/AtlasOfLivingAustralia/biocache-hubs/blob/76d6a2fca8f52cf04544401edd14a3bbeeaff060/grails-app/controllers/au/org/ala/biocache/hubs/OccurrenceController.groovy#L180

                JSONArray contacts = null

                if (record.processed.attribution.collectionUid) {
                    collectionInfo = webServicesService.getCollectionInfo(record.processed.attribution.collectionUid)
                    contacts = webServicesService.getCollectionContact(record.processed.attribution.collectionUid)
                }

                if(record.raw.attribution.dataResourceUid && (contacts == null)){
                    try {
                        contacts = webServicesService.getDataresourceContact(record.raw.attribution.dataResourceUid)
                    } catch(Exception e){
                        log.warn("Problem retrieving contact details for ${record.raw.attribution.dataResourceUid} - " + e.getMessage())
                    }
                }

**Comment by ansell** [comment]
Does anyone know what the effects of the following code in the collectory are? Ie, would Dave Martin be pulled in by this code:

https://github.com/AtlasOfLivingAustralia/collectory-plugin/blob/ec60b0e23a26419a3dd27ad9c67bf762bb4e94c1/grails-app/domain/au/org/ala/collectory/DataProvider.groovy#L113

    /**
     * Returns the best available primary contact that can be published.
     * @return
     */
    @Override
    ContactFor inheritPrimaryPublicContact() {
        if (getPrimaryPublicContact()) {
            return getPrimaryPublicContact()
        }
        else {
            for (con in listConsumers()) {
                def related = _get(con)
                if (related.inheritPrimaryPublicContact()) {
                    return related.inheritPrimaryPublicContact()
                }
            }
            return null
        }
    }

**Comment by nickdos** [comment]
I'd prefer Dave Martin is not the default fall-back "curator" - could we change this to be "ALA data management" `<data_management@ala.org.au>`?

**Comment by djtfmartin** [comment]
Im pretty sure this is just set for this single data resource. Should be just a matter of editing the metadata through the collectory.

**Comment by nickdos** [comment]
Just changed this for ALA sightings via Collectory: http://collections.ala.org.au/dataResource/show/dr364

**Comment by nickdos** [comment]
Closing as it appears to be a collectory data issue, not biocache code one.
