### ISSUE TITLE
Change month chart from pie to bar type, so to be consistent with BIE.

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#18]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=119
*date:* Thu Aug  8 16:35:54 2013
*author:* moyesyside
 ---

Original Issue reported by Reported by john.t...@austmus.gov.au, Jul 11, 2012 - [https://code.google.com/p/ala-portal/issues/detail?id=254](https://code.google.com/p/ala-portal/issues/detail?id=254)

Reported by john.tann@austmus.gov.au, Jul 11, 2012 
Overview of feature/enhancement:
In the CHARTS tab of the Occurrence Records page, add a bar chart for MONTH.
ie on this page: [http://biocache.ala.org.au/occurrences/taxa/urn:lsid:biodiversity.org.au:apni.taxon:298046#chartsView](http://biocache.ala.org.au/occurrences/taxa/urn:lsid:biodiversity.org.au:apni.taxon:298046#chartsView)

User story describing steps to use functionality:
A Bar chart for MONTH is really useful. It gives a clue to flowering time, or in the case of animals, when they are probably most likely to be active. It can really provide a good service.

What the feature should look like (example URLs accepted):
[http://bie.ala.org.au/species/Acacia+longifolia#records](http://bie.ala.org.au/species/Acacia+longifolia#records) 
See the third chart.
 Jul 18, 2013 Project Member `#1` moyesyside@gmail.com 
done

**Comment by nickdos** [comment]
Summary: change month chart from pie to bar type, so to be consistent with BIE.

**Comment by nickdos** [comment]
Fixed. Note I copied the charts2.js from bie-webapp2 over to this project (with some changes merged by hand), for the month chart to show month names instead of numbers. I tested charts against prod and all the other charts appear and function as in prod, except for month which is now fixed. Re-open if regression bugs found.
