### ISSUE TITLE
Auto-complete on Species/Taxon field in Advanced Search form

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/biocache-hubs#184]
When you use the auto-complete suggestions on the Species/Taxon field in the Advanced Search form, the author is added to the search string and no records are found, because the processed names don't have authorship.

**Comment by nickdos** [comment]
This no longer happens (testing latest version of both ALA and AVH). I'm pretty sure this was fixed in the new BIE a while ago.
