### ISSUE TITLE
maps not visible on record details page

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/biocache-hubs#185]
http://biocache.ala.org.au/occurrences/247f873b-1394-4041-b974-127e92161b53 there should be a map of the record location on the left side above the images

**Comment by nickdos** [comment]
Map shows for me - was probably the BIE indexing mess-up

**Comment by nickdos** [comment]
Not showing for me now... might be a config issue as my localhost version is showing?

**Comment by nickdos** [comment]
Looks to be fixed - closing.
