### ISSUE TITLE
Make map toolbar collapsable (list.gsp)

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#186]
@nickdos commented on [Mon Aug 01 2016](https://github.com/AtlasOfLivingAustralia/biocache-service/issues/103)

A user (who appears to be using a narrow screen) has requested the map toolbar be removable but I think it should expand/collapse like the legend icon does.

![search__text_red___occurrence_records___atlas_of_living_australia](https://cloud.githubusercontent.com/assets/532845/17279959/a523eb40-57c6-11e6-8d88-dc3b3bcde3f8.png)

Also test display with a narrow screen - might need to make it "fold"?

**Comment by nickdos** [comment]
Old version had widgets above the map... maybe this simpler solution is worth considering:

![image](https://cloud.githubusercontent.com/assets/532845/17281655/8e7d6690-57e0-11e6-8cc6-d1fc260996a9.png)

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
