### ISSUE TITLE
record display issue

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#189]
http://biocache.ala.org.au/occurrences/aea47f1d-e1b5-4c01-97b4-48406a790854

![image](https://cloud.githubusercontent.com/assets/532845/18237471/326193ee-7375-11e6-8a23-0aa06e6b3dc1.png)

Missing the border under title area - maybe a closing div is missing or stuffed in some way.

**Comment by nickdos** [comment]
Check if it related to having no institution logo present.

**Comment by santiagomrv** [comment]
I think that this issue can be closed.
![captura de pantalla 2016-10-29 a las 19 25 50](https://cloud.githubusercontent.com/assets/22981165/19831582/e0ba33d4-9e0d-11e6-88a6-9c5f8072cf76.png)

**Comment by nickdos** [comment]
yes ws fixed a while ago.
