### ISSUE TITLE
Catalog number search

### ISSUE THREAD

**Issue by santiagomtzdelariva** [AtlasOfLivingAustralia/biocache-hubs#199]
Hi guys,

I'm testing this function in generic-hub version=1.3.1 with biocache-hubs:1.1.1.
My config file is pointing to ala biocache-service. When i write these catalog numbers: CANB 886168.1 , CHR:CHR 522793 (one per line),  i previously checked that these catalog numbers exist in ala, but the ala service only find one record, the first one: http://biocache.ala.org.au/occurrences/search?q=qid:1476944799340#tab_recordsView (result of search by catalog number)

is it a bug or am i doing something wrong?

CANB 886168.1 -> http://biocache.ala.org.au/occurrences/27ccf7a8-39de-4a62-acae-b80ccfdfdf48
CHR:CHR 522793 -> http://biocache.ala.org.au/occurrences/38ac9c04-aca5-4592-934a-85506e6908ff

**Comment by santiagomtzdelariva** [comment]
I also tested this with biocache plugin 1.1.2 and it doesn't work.

**Comment by djtfmartin** [comment]
Thanks @santiagomtzdelariva. Looks like a bug.

**Comment by nickdos** [comment]
That second record has  catalogue number "CHR 522793" not "CHR:CHR 522793" (which has the collection code on the front. The search only works on the catalog number part of the code.
