### ISSUE TITLE
Biocache download checklist: more fields please

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#20]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=122
*date:* Thu Aug  8 16:36:43 2013
*author:* moyesyside
 ---

Original Issue reported by Reported by john.t...@austmus.gov.au, May 31, 2012 - [https://code.google.com/p/ala-portal/issues/detail?id=247](https://code.google.com/p/ala-portal/issues/detail?id=247)

Reported by john.tann@austmus.gov.au, May 31, 2012 
Being able to download a checklist is great. Adding more fields, such as common name, lifeform, or other taxonomic levels would be very useful. 

Overview of feature/enhancement:
I was wanting to get a list of the birds in Australia. Most bird people refer to birds by their common name.

For some of us, when we want to know the species in an area, we may only be familiar with common names. If a beast has no common name, and its scientific name appears in a list, what is it? A frog, a plant, or something else?

If ALA provides the species list as a spreadsheet, adding other known names will help.

User story describing steps to use functionality:
When downloading a checklist, please provide
GUID
Vernacular name
Lifeform
Kingdon
Phylum
Class
Order
Family
Genus
Species
Subspecies

**Comment by nickdos** [comment]
Only missing fields are life form and subspecies (which will be in scientific name). Won't change these.
