### ISSUE TITLE
Collection manager can't see "verify annotation" button

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#209]
Margaret is listed as the collection manager for ANWC records but she can't see the "verify annotation" button. I can see it with ROLE_ADMIN access.

Edit: tracked it down to [issue with Collectory](https://github.com/AtlasOfLivingAustralia/collectory/issues/54) with the `contacts.json` service failing.

**Comment by nickdos** [comment]
Discovered collectory had an email address with uppercase letters but user's account contained all lowercase letters. Waiting to see if this fixed the issue.

**Comment by nickdos** [comment]
Needs testing - ask MC to try again...

**Comment by nickdos** [comment]
Broken again - MC and US can't see verify button but ROLE_ADMIN users can see it. A simpler solution could be to use ROLE_COLLECTION_ADMIN in a smilar way to ROLE_ADMIN check is done, as the collectory collection/dataresource permission checking seems brittle and overly complicated for the <5 users who actually use this feature.

**Comment by nickdos** [comment]
To test this, use an account that is NOT ROLE_ADMIN but has ROLE_COLLECTION_ADMIN. Check an existing annotation (not created by the current user) and look for the "Verify" button. Click through and try setting different verification status values - results should be fairly self obvious.

**Comment by Rita-C** [comment]
"flag an issue" threw error on `biocache-test`, log shows 403 returned from `[biocache-service](https://biocache-ws-test.ala.org.au/ws)`, will check with @brucehyslop .
Tested on local, seems ok.

**Comment by nickdos** [comment]
Seeing as bioche-test is currently in flux due to API gateway testing (and fact Dave has deprecated a bunch of services for it), I'm satisfied with the local testing for this issue.
