### ISSUE TITLE
Sandbox - missing vernacular name

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#21]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=123
*date:* Thu Aug  8 16:36:55 2013
*author:* moyesyside
 ---

Original Issue reported by Reported by john.t...@austmus.gov.au, May 31, 2012 - [https://code.google.com/p/ala-portal/issues/detail?id=246](https://code.google.com/p/ala-portal/issues/detail?id=246)

Reported by john.tann@austmus.gov.au, May 31, 2012 
Names submitted to the sandbox unexpectedly do not get a common name added

**What steps will reproduce the problem?**
1. Add a list of birds to sandbox
eg [http://sandbox.ala.org.au/hubs-webapp/occurrences/search?q=data_resource_uid:drt710#recordsView](http://sandbox.ala.org.au/hubs-webapp/occurrences/search?q=data_resource_uid:drt710#recordsView) 
2. Download the list from the sandbox

**What is the expected output? What do you see instead?**
Expected: A spreadsheet with my list of names and other columns with ALA-type interpretations, such as Common Name

What do you see instead?
A csv file with an empty column with the heading 'Vernacular Name - matched'.

What version of the product are you using? On what operating system?
FF13 on WinXP

Please provide any additional information below.
OK. I didn't provide a common name, but that was what I was wanting to find out.

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/sandbox#12
