### ISSUE TITLE
Trying to download a WKT with Firefox

### ISSUE THREAD

**Issue by santiagomrv** [AtlasOfLivingAustralia/biocache-hubs#210]
In biocache if i have drawn a polygon and i want to download the WKT,  in chrome its possible but when if i try to download the WKT in Firefox nothing happens.

**Comment by nickdos** [comment]
Console report:

    Empty string passed to getElementById().

Looks like it coming from Leaflet... needs more digging.

**Comment by nickdos** [comment]
Found fix at http://stackoverflow.com/a/27284736/249327.
