### ISSUE TITLE
Offline download - missing fields in full darwin core version

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#211]
@nickdos commented on [Thu Nov 10 2016](https://github.com/AtlasOfLivingAustralia/biocache-service/issues/114)

Using the new download UI, if you choose the "full darwin core" option for records download and look at the resulting download file, there are no references to either the collection or data resource (either IDs or name) in the download file.

They should be there I'd have thought.

Edit found config line:

https://github.com/AtlasOfLivingAustralia/downloads-plugin/blob/master/grails-app/conf/downloadsDefaultConfig.groovy#L60

that needs to be added to.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
