### ISSUE TITLE
Investigate images-client-plugin dependency on image-service

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#212]
Find out if the [images-client-plugin](https://github.com/AtlasOfLivingAustralia/images-client-plugin) can work on plain image URLs that are **not** served from http://images.ala.org.au/. 

The background is: international users of the ALA infrastructure use biocache-hubs but don't have image-service serving their images (like ALA does), so the images are usually plain image URLs. So if the images-client-plugin is dependent on image-service, then we either need to add extra config & code to make the dependency optional or else remove the plugin from biocache-hubs and make it a dependency on ala-hubs instead.

**Comment by djtfmartin** [comment]
This is something we've discussed in the GBIF developer meetings.

I think the general message that if projects need to support images with an ALA installation that they will need to setup the image-service is accepted as a reasonable approach.

**Comment by temi** [comment]
@djtfmartin @nickdos It is technically possible to show an image on leaflet without tiling capability of image-service. I could implement that feature with a flag to turn it on or off. What do you think?

**Comment by nickdos** [comment]
I also just noticed that the images-client-plugin has a dependency on lists.ala.org.au - see this issue: https://github.com/AtlasOfLivingAustralia/images-client-plugin/issues/12.

This could also be a problem for current users of ALA code (Spain, at al) if they don't have specieslist-webapp installed. 

Should we try and make this part of the code optional?

**Comment by temi** [comment]
@patkyn has added a parameter called addPreferenceButton and it is turned on only for user who are ala admin. However, it does not have an explicit variable to turn it on or off.

https://github.com/AtlasOfLivingAustralia/bie-plugin/blob/master/grails-app/views/species/show.gsp#L973

**Comment by temi** [comment]
created pull requests for this -
https://github.com/AtlasOfLivingAustralia/images-client-plugin/pull/13
https://github.com/AtlasOfLivingAustralia/biocache-hubs/pull/213
https://github.com/AtlasOfLivingAustralia/bie-plugin/pull/59

**Comment by djtfmartin** [comment]
@nickdos yes i agree the lists.ala.org.au dependency should be optional

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
