### ISSUE TITLE
Explore your area not finding user location

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#214]
http://biocache.ala.org.au/explore/your-area

shows marker in middle of Australia.

2 issues at play:
 - Google not allowing location due to non-HTTPS connection
 - Grails code should be guessing location via IP address, as a fall back 

So investigate second point and then we need to deploy biocache under HTTPS.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
