### ISSUE TITLE
Consolidate "download map" into main download page

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#219]
This is a suggestion and needs UX validation... the main download button on the search results page allows users to download records, checklists & field guides but not printable maps. There is a separate "download map" button on the map tab for this. 

I wonder if this is an unnecessary separation and that we should include the map option in the main download page.

![image](https://cloud.githubusercontent.com/assets/532845/20585840/79957e9e-b252-11e6-8d3f-be85c744823b.png)

Note both download buttons above.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
