### ISSUE TITLE
Non-occurrence data

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#22]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=126
*date:* Thu Aug  8 16:37:39 2013
*author:* moyesyside
 ---

Original Issue reported by Reported by john.t...@austmus.gov.au, May 1, 2012 - [https://code.google.com/p/ala-portal/issues/detail?id=229](https://code.google.com/p/ala-portal/issues/detail?id=229)

Reported by john.tann@austmus.gov.au, May 1, 2012 
People have asked for access to associated data if it exists.

Often a dataset is a set of results of measurements for a purpose, and a lot of extra information is recorded as well as the occurrence information which ALA shows. For example someone may be measuring leaf-thickness, or height of trees, or associated taxa.

Currently ALA does not show this extra info.

Is there a way that this extra data can be discovered?

Difficulties: This data probably won't come in any standard form - eg one person may measure eye-colour whereas the next person could measure iris-colour. However if we can pass this information on to a user, it would be a first step.

**Comment by nickdos** [comment]
We now display such data under the "Additional properties" section.
