### ISSUE TITLE
Add count of facet values to biocache record view

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/biocache-hubs#224]
use case is to get a count of the number of species in an area - initial solution is to add a count to the species and scientific name facets.  If adding to one facet add to all facets.

Hopefully is fairly easy to implement and would offer immediate benefits to some identified users - e.g. state of the forests report providing a count of species in each forest type

**Comment by nickdos** [comment]
Is this to see how many different species there are for a given query? How do we deal with subspecies, varieties, etc., do we simply count it at the species level and ignore the lower taxa? Also, this will probably not include unmatched taxa, so we need to make that clear probably.

At the moment the user can do this by clicking the on the "show more" link under the "Species" facet and then clicking the download icon at the bottom of the popup (next to the close button). They can then simply view the CSV file in Excel and look at the last row number (minus 1).

**Comment by nickdos** [comment]
Easiest way would be to add the total in the popup after "Species" - e.g. "Species (455 items)"

![image](https://cloud.githubusercontent.com/assets/532845/22447026/0531eeb6-e7a4-11e6-9f5c-6beeed620915.png)

**Comment by nickdos** [comment]
After discussion with Miles - decided the count could go in facets column next to each facet group. E.g. 
Taxon
Species (455)

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
