### ISSUE TITLE
Error: unknown with no message in log

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-hubs#225]
The User Experience for biocache-hubs has been setup so that specific errors are never shown to users on the assumption that the log will contain the stacktrace so a developer can debug the unknown error. However, in debugging a new biocache setup I have run into an error that has no stacktrace in the logs. This is currently an intentional design choice that should be rethought to enable advanced users to help debug issues.

https://github.com/AtlasOfLivingAustralia/biocache-hubs/blob/master/grails-app/views/error.gsp

Ala-hub has a similar error.gsp page that also never shows errors to users:

https://github.com/AtlasOfLivingAustralia/ala-hub/blob/master/grails-app/views/error.gsp

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
