### ISSUE TITLE
Image popup not loading

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#229]
http://biocache.ala.org.au/occurrences/search?taxa=Citrus+gracilis#tab_recordImages

clicking on thumbnail image shows black image popup. 

Failed JS resource (500) for http://lists.ala.org.au/ws/speciesListItem/getPreferredSpeciesImage?callback=jQuery18309317123272547854_1488173910146&_=1488173919607

likely due to lack of image ID in request.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
