### ISSUE TITLE
Spatial search with large WKT string

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#231]
E.g. this WKT string:

`MULTIPOLYGON(((149.875107998114 -28.80885041848034,149.8808855082762 -28.86084800971875,149.8192587334632 -28.88780972366963,149.8173328967599 -28.91091976421831,149.6420817558825 -28.97832404908739,149.7210410611828 -29.11120678227683,149.7807419993547 -29.25371869902109,149.9425122833355 -29.41163730950358,149.7306702448912 -29.44245069682265,149.640155919426 -29.57533342994782,149.6690434701471 -29.62733102119502,149.655562613167 -29.65621857187681,149.4514239216134 -29.77176877454732,149.4263880443581 -29.81028550878703,149.5380865737861 -29.94894575212603,149.6054908588133 -30.09530934229804,149.6440075930874 -30.11649354614943,149.6863760008206 -30.21278538178806,149.7152635515284 -30.23396958563578,149.7094860414005 -30.26093129960806,149.8019262036764 -30.35337146184037,149.8674046519535 -30.41499823666326,149.8539237950031 -30.51129007228095,149.8481462849327 -30.66920868270001,149.8154070608261 -30.71157709036191,149.7845936734526 -30.79823974241112,149.7537802860927 -30.91571578185953,149.7094860416891 -30.91764161855566,149.6228233896381 -31.0177851275716,149.6247492263778 -31.07748606565854,149.6594142872451 -31.14296451389478,149.6016391858584 -31.16607455442317,149.549641594639 -31.2508113697523,149.5111248603641 -31.22770132918864,149.4764597995022 -31.17377790122711,149.4148330247083 -31.23925634942813,149.3532062498997 -31.27199557351751,149.3551320866319 -31.3143639811924,149.3763162904773 -31.31436398120015,149.4398689019947 -31.27199557354924,149.5034215135277 -31.26429222672262,149.5573449415168 -31.30666063441651,149.582380818787 -31.30280896100078,149.6016391859347 -31.33747402183203,149.6555626138863 -31.29510561417763,149.7191152254372 -31.32784483831264,149.8000003673973 -31.33747402190451,149.8500721219548 -31.36828740932211,149.9059213866232 -31.33362234851829,150.0002873855758 -31.34325153211508,150.0118424058997 -31.44339504116696,149.967548161516 -31.48961512224974,150.0368782832448 -31.60709116173463,150.0368782832645 -31.65138540612121,149.9848806919953 -31.6244236921279,149.9290314273013 -31.60131365155817,149.9213280804776 -31.6667920997788,149.8789596727855 -31.66486626305098,149.8481462853491 -31.60901699837861,149.8096295510655 -31.56664859069048,149.7903711839341 -31.56857442739592,149.8154070612345 -31.63212703891618,149.736447756 -31.64945956929956,149.776890326995 -31.68797630356352,149.7114118787652 -31.73227054792634,149.7133377154932 -31.76500977203882,149.6228233900029 -31.83433989365463,149.6401559204315 -31.85552409749794,149.7749644903032 -31.73612222137427,149.8115553878478 -31.72071552768786,149.848146285406 -31.7361222214008,149.7422252662356 -31.86322744438472,149.6748209813232 -31.97492597368308,149.7229668991476 -31.96144511671327,149.7441511030131 -32.00573936110751,149.7634094700992 -31.90367001535404,149.7961486942042 -31.85937577097931,149.8057778777937 -31.9113733622192,149.8269620816044 -31.83433989372849,149.8962922032667 -31.80352650635422,149.855849632314 -31.85937577100089,149.8154070613692 -31.93255756605976,149.8308137550846 -31.9537417699023,149.8674046526193 -31.91715087237886,149.9039955501413 -31.85167242416841,149.927105590687 -31.82278487348998,149.9559931413802 -31.81122985322566,149.9559931414165 -31.89211499514884,149.9116988970237 -31.91715087239485,149.8731821627877 -31.98070348389205,149.8231104082759 -32.05195944223499,149.9174764072101 -32.02114605486968,149.9887323655934 -32.00766519790812,149.9733256719058 -32.04810776886414,150.004139059339 -32.09625368668667,150.0214715897998 -32.18869384889083,150.1004308950288 -32.1598062982324,150.1081342419052 -32.2118038894715,150.1851677104403 -32.22528474648624,150.2256102814337 -32.25994980732499,150.2660528524221 -32.28305984788888,150.3084212601121 -32.28113401119163,150.2930145663889 -32.24261727693705,150.3257537904948 -32.20024886927481,150.3700480349114 -32.22721058326499,150.4393781565844 -32.21950723644002,150.4393781565627 -32.17136131862883,150.5125599516526 -32.14247376796829,150.529892482082 -32.16558380852394,150.5587800327831 -32.1713613186717,150.5568541960622 -32.15402878825894,150.6069259506037 -32.14825127813953,150.6358135013068 -32.15788046171221,150.6627752152584 -32.08277282993634,150.6993661128445 -32.15980629844746,150.749437867399 -32.1829163390147,150.7725479079468 -32.15788046176129,150.7802512547654 -32.08084699326619,150.7532895407525 -32.01922021845822,150.6916627659022 -31.95951928035012,150.6858852557479 -31.92678005623649,150.7455861938472 -31.90174417899614,150.7975837850987 -31.88826332202788,150.8129904787878 -31.84974658778444,150.86691390675 -31.83048822067955,150.8900239472971 -31.80352650671361,150.8341746825984 -31.77078728258193,150.7918062748926 -31.73804805845504,150.8534330497088 -31.72071552806533,150.8958014573739 -31.6610145899949,150.9747607626018 -31.62634952919956,151.0883851286685 -31.59168446841689,151.1538635769319 -31.62057201912716,151.1654185971708 -31.5281318569343,151.2116386782568 -31.45495006187844,151.2270453719469 -31.41835916434771,151.1962319845103 -31.36250989967571,151.250155412496 -31.39524912380686,151.3310405544554 -31.40102663397363,151.2828946366399 -31.4376175314924,151.3329663911989 -31.47035675562199,151.336818064612 -31.43954336822442,151.3734089621563 -31.42221083782575,151.3676314519914 -31.36443573645066,151.3271888810096 -31.35673238958619,151.3021530037044 -31.28162475779195,151.3137080239773 -31.26621806409672,151.3714831253826 -31.28355059452965,151.3849639823629 -31.25466304384811,151.3291147176681 -31.23155300327843,151.3156338606569 -31.18918459559996,151.346447248065 -31.17955541204911,151.3522247581863 -31.13718700437761,151.383038145586 -31.10829945370232,151.3483730847339 -31.07748606629069,151.3194855340182 -31.03896933203131,151.2790429630396 -31.0389693320165,151.2636362693051 -30.97349088378809,151.2020094944749 -30.96001002677838,151.1615669235047 -30.9792683938879,151.0614234144084 -30.96386170015164,151.0344617004336 -30.98889757740352,151.0036483130064 -30.95423251656823,150.9516507217307 -30.91378994558793,150.9555023951449 -30.88490239490275,151.0132774965335 -30.86371819108712,151.0614234143875 -30.91571578234069,151.0960884752177 -30.89645741522897,151.1480860664591 -30.85794068099936,151.1288276993131 -30.8271272935933,151.0479425573655 -30.84831149740039,151.0209808433614 -30.80594308971674,150.9940191293682 -30.78861055929492,150.963205741895 -30.64802447927544,150.9901674558774 -30.64032113243562,151.0190550065671 -30.61913692860937,151.0074999862719 -30.58254603106883,150.9574282317245 -30.57676852091297,150.9035048037482 -30.56521350061836,150.9189114973876 -30.41114656362892,150.8149163148548 -30.37262982934141,150.8572847225225 -30.31678056469643,150.8438038655074 -30.26478297345552,150.8052871312321 -30.2416729328918,150.8206938249175 -30.19352701508652,150.8245454983226 -30.14345526056447,150.851507212296 -30.11456770988794,150.8669139059828 -30.07027346550755,150.8476555388147 -29.98746248686543,150.8572847223588 -29.93546489563311,150.8245454982161 -29.89502232465952,150.8438038653271 -29.84495057014337,150.8168421513135 -29.77947212191025,150.8129904778739 -29.74865873450976,150.880394762858 -29.79487881563362,150.8418780285646 -29.72940036739615,150.909282313548 -29.77369461180757,150.9689832516684 -29.79487881566683,150.9940191289713 -29.86613477403639,151.0152033328279 -29.89117065130609,151.0768301076281 -29.83339554995599,151.1500119027177 -29.79873048915947,151.2251195345451 -29.82184052973686,151.3079305131851 -29.74865873469541,151.2905979827453 -29.700512816878,151.2405262281966 -29.69280947000947,151.2231936977642 -29.66199608260399,151.1885286369137 -29.63503436861682,151.1654185963243 -29.56377841024803,151.1866028001638 -29.5483717165565,151.2212678610312 -29.61577600150472,151.2482295750131 -29.60614681795273,151.2578587585558 -29.55029755329571,151.2193420242609 -29.48096743163346,151.2193420242373 -29.4251181669729,151.1866028000881 -29.36926890229983,151.207787003917 -29.32882633134671,151.244377901437 -29.25179286286299,151.2867463091115 -29.20942445520547,151.3849639815018 -29.24023784264159,151.4311840625966 -29.18246274128599,151.5717701426498 -29.14202017037796,151.6642103048855 -29.13624266027571,151.7316145898723 -29.18824025153685,151.7778346709955 -29.19786943511637,151.8067222217199 -29.25757037321262,151.8490906294069 -29.24408951624157,151.7970930380988 -29.12661347676376,151.7836121810711 -29.04380249812417,151.7508729569405 -29.03224747783722,151.7219854062112 -28.96099151946627,151.7065787125104 -28.9744723764475,151.6661361415215 -28.9513623358829,151.5987318565436 -28.92054894845845,151.5332534083091 -28.96291735610715,151.4947366740796 -29.04958000815212,151.4889591639565 -29.09002257911093,151.3907414916111 -29.16705604757121,151.3214113699319 -29.16513021083256,151.3098563496368 -29.12853931329192,151.2905979824911 -29.09772592588557,151.2944496558926 -29.03802498780157,151.2809687988592 -28.94173315217464,151.2520812481519 -28.92247478503933,151.1269018617537 -28.83966380635695,151.0421650463668 -28.83388629618736,151.028684189339 -28.75107531754735,150.9439473739473 -28.73374278710304,150.9208373333687 -28.68752270599564,150.8187679875517 -28.65670931855765,150.7609928861543 -28.65863515524801,150.6839594176448 -28.71063274645455,150.7321053355207 -28.81462792894479,150.5298924805983 -28.74722364393215,150.4220456246577 -28.75300115402832,150.2198327697505 -28.72026192983938,149.875107998114 -28.80885041848034)))`

displays on the map OK but the requests for counts, etc. fail with error `414 Request-URI Too Large`. 

Fix is to use POST for these requests and subsequent link for "Search for records in this area". With the QID passed back.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
