### ISSUE TITLE
Replace CartoDB base layer 

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#238]
https://github.com/AtlasOfLivingAustralia/avh-hub/issues/51

Remove the CartoDB base layer and replace with something similar (grey scale scheme)

**Comment by nielsklazenga** [comment]
That will fix the Norfolk/Lord Howe Island issue, right?

**Comment by nickdos** [comment]
@nielsklazenga: yes.

**Comment by nickdos** [comment]
That's good news, I've had an open ticket with CartoDB for ages on this. I'm closing this, as that was the only reason.
