### ISSUE TITLE
Changing items per page loses WKT query

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#239]
Reported by Frank Z...

http://avh.ala.org.au/occurrences/search?q=lsid%3Ahttp%3A%2F%2Fid.biodiversity.org.au%2Fnode%2Fapni%2F2909356&qc=data_hub_uid%3Adh9&wkt=POLYGON((142.01659977436066+-15.005634618357954,146.76269352436066%20-15.005634618357954,146.76269352436066%20-17.871415819156176,142.01659977436066%20-17.871415819156176,142.01659977436066%20-15.005634618357954))#tab_recordsView

change items per page to 50 and the wkt param is lost. Pagination work OK so probably just needs to copy the code from there.

**Comment by ansell** [comment]
The query above doesn't show any results for me, but a query I made up seems to work after changing the records per page on both avh-prod and avh-test:

https://avh-test.ala.org.au/occurrences/search?q=*:*&fq=&pageSize=50&wkt=MULTIPOLYGON(((147.45849609375%20-20.879342971957897,148.51318359375%20-17.476432197195518,142.88818359375%20-17.224758206624628,141.74560546874997%20-21.207458730482642,147.45849609375%20-20.879342971957897))) 

https://avh.ala.org.au/occurrences/search?q=*:*&fq=&pageSize=50&wkt=MULTIPOLYGON(((147.45849609375%20-20.879342971957897,148.51318359375%20-17.476432197195518,142.88818359375%20-17.224758206624628,141.74560546874997%20-21.207458730482642,147.45849609375%20-20.879342971957897)))
