### ISSUE TITLE
Faceting needs a re-think

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#24]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=130
*date:* Thu Aug  8 16:38:51 2013
*author:* moyesyside
 ---

Original Issue reported by Reported by john.t...@austmus.gov.au, Mar 28, 2012 - [https://code.google.com/p/ala-portal/issues/detail?id=208](https://code.google.com/p/ala-portal/issues/detail?id=208)

Reported by john.tann@austmus.gov.au, Mar 28, 2012 
Overview of feature/enhancement:
On the occurrence records page the FUNCTIONALITY of the faceting is very powerful.
However its usability is tough.

Earlier this week the ordering of the faceting changed. Before the change there were 'Form' and source-based faceting at the top - specimen type, collector, institution and so on. I was very familiar with the list and could quickly find important headings.

After the change, there is now taxonomic information at the top, and although this might make good logical sense, the order has changed and I no longer know my way around the list. This is probably how a newbie finds it - a bit confusing, and what does it all mean?

Any wonder with 41 categories, each with up to 3 options each. Over 100 lines, all with good information needing to be thought about and assessed: Do I need this facet? Or is there another one?

So, I think a re-think is necessary. How should this large amount of helpful information be better presented?

A few ideas, if only to kick this along... 
1. Use colour to split between what (taxonomy), who (source, institution, collector), where (location), when (dates), how (images, DNA), other

2. Present a core subset of filter categories to open with. These could be modified using the customise list.

3. Present a set of 6 facet categories, each open as drop-down lists. A little like the selectable regions in the REGIONS page, with the ability to select more than one facet and category.

4. The pie charts and bar charts work. Perhaps linking the charts to other facet categories? I'm not sure about this idea, as the charts are pretty clean now, and to sully them with more categories might make them unworkable. 

 May 5, 2012 `#1` john.tann@austmus.gov.au 
Some facets are now ordered alphabetically, rather than by popularity. Generally the order of each facet needs to be considered on its merits, eg collector, collection, scientific name, should be ordered by numbers of records; months and decades in chronological order; State conservation in an order that is consistent - say from least concern to extinct; and so on.

I think it is worth thinking about how these facets are used when re-laying out their presentation.

**Comment by nickdos** [comment]
This has been dealt with by adding the facet categories and customisable display of facets.
