### ISSUE TITLE
Add link to SP from record page

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#240]
Requested by @Tasilee:

> I was looking at some new records (e.g., http://biocache.ala.org.au/occurrences/87c176ff-6fc8-4417-b045-232f8d45695f) and wanted to view the record in the Spatial Portal - but there is no link, as far as I can tell? Can we add one, say below the map or similar?

Use a SOLR search query for just the record - e.g. http://biocache.ala.org.au/ws/occurrences/search?q=id:87c176ff-6fc8-4417-b045-232f8d45695f

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
