### ISSUE TITLE
clarify labels on advanced searched

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/biocache-hubs#242]
example from OZCAM involving confusion between datasetName (DwC - meaning a subset with a data set) and data resource (labelled as dataset name on the advanced search).

**Comment by nickdos** [comment]
Thanks Miles, could you add some more details, as there's not enough to go off...

Please provide a screenshot with the labels/text that are in question and then provide alternative text that should modified.

**Comment by ansell** [comment]
Verified that the label on the advanced search page changed from "Dataset name" to "Data Resource"
