### ISSUE TITLE
Spatial search polygon popup counts not working

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#244]
https://biocache.ala.org.au/search#tab_spatialSearch

Draw a polygon with the tools in the map, popup shows:

> species count: calculating...
> occurrence count: calculating...
> Search for records in this area

Counts never appear and JS error shows:

404 - https://biocache.ala.org.au/undefined/occurrence/facets.json

Which results from the var `BC_CONF.biocacheServiceUrl` being undefined in `map.common.js`. The page is populating this global var and it is declared above the import for the JS file, so I'm not sure why this is happening.

The same code when called from a search results page, works as expected.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
