### ISSUE TITLE
Two full screen icon in tab_mapView

### ISSUE THREAD

**Issue by shahmanash** [AtlasOfLivingAustralia/biocache-hubs#246]
The leaflet full-screen icon in rendered twice 

`<a class="leaflet-control-zoom-fullscreen" href="#" title="Full `Screen"></a>`

![double](https://user-images.githubusercontent.com/7394330/29962372-5821a286-8f03-11e7-9b73-d9a12252c3a1.png)

**Comment by nickdos** [comment]
Thanks - this should be fixed in our next major release (bootstrap3 and grails3 upgrade). No ETA yet. 

Issue is result of fullscreen JS file being loaded twice.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
