### ISSUE TITLE
Prevent apiKey param from being displayed in error messages

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#247]
When a user requests a record page and biocache-service times-out the response, the error message shows the requested URL which includes the `apiKey`:

> Failed to get json from web service (https://biocache.ala.org.au/ws/occurrence/721db934-edbc-4d29-8cde-4bfeaae34514?apiKey=api-key-to-use). class java.io.IOException Server returned HTTP response code: 502 for URL: https://biocache.ala.org.au/ws/occurrence/721db934-edbc-4d29-8cde-4bfeaae34514?apiKey=api-key-to-use, java.io.IOException: Server returned HTTP response code: 502 for URL: https://biocache.ala.org.au/ws/occurrence/721db934-edbc-4d29-8cde-4bfeaae34514?apiKey=api-key-to-use

Check if:
1. the `apiKey` is needed for this request and remove if not, otherwise
2. see if biocache-service accepts it via custom HTTP header and if not, then 
3. remove the URL from the error message

**Comment by ansell** [comment]
One way to reduce the issues with the apikey parameters becoming visible could be to require HTTP POST when people want to use an authenticated request.

**Comment by nickdos** [comment]
This was done in 8ca9e25ffe4b7f202e971559f59f0093bbc46448

**Comment by nickdos** [comment]
Closed as deployed in previous release - 2.1.7.
