### ISSUE TITLE
Enter either some help or contact details against single occurrence records in the biocache

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#25]
A user of the system wanted extra information about an occurrence record. 

It is something that they needed to contact the curator about, in this case it was information about the host for a lichen. Instead the user contacted info@ala.org.au, who incorrectly directed the email.

It would be good to either have some Help text to explain the procedure, or a mechanism to show the contact details, possibly name, phone no. and email link.

**What steps will reproduce the problem?**
1. Look up this record: [http://biocache.ala.org.au/occurrences/770dc39b-dbb1-41f7-b823-70857a99f5a8](http://biocache.ala.org.au/occurrences/770dc39b-dbb1-41f7-b823-70857a99f5a8)
2. Have a query about the host. The only obvious information on the page about getting more information for help is under the "Contact us" in the ALA footer.
3. Of course, they could have followed the URLs under Dataset to Collection or Data Set, but they didn't. They adopted step 2.

**What is the expected output? What do you see instead?**

Expected: Make it more obvious on the occurrence single record page how to get more information. Don't expect the user to follow the Dataset URLs.

Instead, possible Solutions:
1) Have some help text, maybe in a '?' to say something like:
"If you would like more information about this record, please contact the curator of the data set. Follow the Collection link or the Data Set Link to find curator contact details".

2) Have the contact details for the curator on the occurrence record page somewhere. Contact details could include, name, phone no., email.

Suggest:
If Collection contact details exist show them, 
else if Data Set contact details exist show them,
else Show nothing.

What version of the product are you using? On what operating system?

Please provide any additional information below.

If this is easy to do, I would give this reasonable priority.

Text from original email:
I have come across the following record and feel there is not enough detail on the host

[http://biocache.ala.org.au/occurrences/770dc39b-dbb1-41f7-b823-70857a99f5a8;jsessionid=07FA25BFADBC3AA7BF0004C08A0C7206](http://biocache.ala.org.au/occurrences/770dc39b-dbb1-41f7-b823-70857a99f5a8;jsessionid=07FA25BFADBC3AA7BF0004C08A0C7206)

As it is a preserved specimen, does it mean preserved on the host material?  Would there be a person who could tell me the type of tissue it is on e.g. leaf or stem or fruit.

This information is necessary as I am working on an Import Risk Assessment for Pyrus fruit being imported from the eastern states into Western Australia.

 Mar 18, 2012 Project Member `#1` moyesyside@gmail.com 
This will probably be requested by the AVH-ers too so we may as well roll into the hub work.
 Owner: nickdos@gmail.com

**Comment by nickdos** [comment]
Possible quick fix would be to rgab contact info from collectory WS (if present) and display. Alternative is to link to collectory page via popup that explains to look at contact section on collectory page and then open page.

**Comment by nickdos** [comment]
Deal with this issue when tackling #109
