### ISSUE TITLE
Var name instead of values for "Location>Refine your research"

### ISSUE THREAD

**Issue by JeGoi** [AtlasOfLivingAustralia/biocache-hubs#256]
All versions, only in the popup

![image](https://user-images.githubusercontent.com/13801368/37116602-c667bdaa-221c-11e8-8942-0e4338296803.png)

![image](https://user-images.githubusercontent.com/13801368/37116642-e6c48ff6-221c-11e8-944a-cafe60b3b2d9.png)

**Comment by nickdos** [comment]
Fixed in prod

![image](https://user-images.githubusercontent.com/532845/48590429-87a4f800-e993-11e8-9538-091d0dfd73ef.png)
