### ISSUE TITLE
Dots disappear on Occurrence map, but information remains

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#26]
_migrated from:_ https://code.google.com/p/ala/issues/detail?id=134
_date:_ Thu Aug  8 16:40:12 2013
_author:_ moyesyside

---

Original Issue reported by Reported by john.t...@austmus.gov.au, Mar 13, 2012 - [https://code.google.com/p/ala-portal/issues/detail?id=191](https://code.google.com/p/ala-portal/issues/detail?id=191)

Reported by john.tann@austmus.gov.au, Mar 13, 2012 
When mapping occurrence records in Biocache and choosing to colour-by something, some dots can disappear as expected, but their information remains. This becomes annoying when interrogating a point.

**What steps will reproduce the problem?**
1. search for and display on a map some search records. For example gudgeon fish from Australian Museum
[http://biocache.ala.org.au/occurrences/search?q=collection_uid:co112&fq=family:ELEOTRIDAE#mapView](http://biocache.ala.org.au/occurrences/search?q=collection_uid:co112&fq=family:ELEOTRIDAE#mapView)
2. Colour by something, for example 'Record issues'. Toggle some of the colours off
3. Click on one of the coloured dots - there is information presented for not only the dots on the screen, but also for the dots that have been toggled off. You can also click on the screen where a dot once was, and get information for that now-invisible dot.

What is the expected output? 
Info for only the dots that are present.

What do you see instead?
Information for dots that are not present

Please provide any additional information below.

This becomes an issue for a map with a lot of dots, and you are wanting to reduce the density of dots to get a clearer picture.

 info with no dot.gif 105 KB   View   Download Apr 6, 2012 Project Member `#1` moyesyside@gmail.com 
(No comment was entered for this change.)
 Owner: nickdos@gmail.com Apr 9, 2012 Project Member `#2` nickdos@gmail.com 
Yes this is a bug - code for "info on mouse click" assumes all records as visible. 
 Status: Accepted

**Comment by nickdos** [comment]
This would be a substantial change but do-able. Click event on map would need to check if any "colour by" items are off and then modify the query to add the appropriate `&fq=-sensitive:generalised` for each inactive facet value (or visa versa).

**Comment by nickdos** [comment]
Also test to see whether all current `fq` params are being applied to map query and possibly any "inactive" values are applied via the map menu checkboxes.
