### ISSUE TITLE
Can't delete annotation when record has a second verified annotation

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#261]
Reported by Ursula Smith (see ticket). Trying to delete her annotation on this record:

https://biocache.ala.org.au/occurrences/a40ccd76-8d69-4eb9-a0c5-ce503d8df8b4 

(note this record has a verified annotation - this is important!).

She clicked "delete" but the annotation remained.

I then added another annotation, and when I deleted my annotation, Ursula's annotation was removed (not mine). Looks like an offset bug.

Also, after trying to delete my annotation (which deleted Ursula's), I can NO LONGER see a delete button on my annotation.

![image](https://user-images.githubusercontent.com/532845/39023376-95e79d52-447d-11e8-8e41-0e63d58069e9.png)

(yes I'm logged in and can see the verify button indicating I have ROLE_ADMIN)

**Comment by alexhuang091** [comment]
Hi @nickdos, I think it's no longer an issue.

In the pre-pipeline system, if an annotation is verified by an admin, you can't delete it. The verification needs to be deleted before the annotation can be deleted from the UI.

Current pipeline prod system works same way and there's no issue in deleting an annotation.

<img width="1676" alt="截屏2021-09-17 下午1 38 17" src="https://user-images.githubusercontent.com/61677987/133720367-c4eb62df-30de-4a43-8599-9dabc1f38a3c.png">

**Comment by nickdos** [comment]
Thanks @alexhuang091 I think that makes sense. Confirmed deletions seem to work fine, even with an additional annotation present, similar to example above.
