### ISSUE TITLE
Autocomplete fails if bieService.baseUrl is not set

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#262]
Some hubs do not require the BIE and thus the following config vars are set:

```
bieService.baseUrl =
skin.useAlaBie = false
```
However, with this scenario, the bieAutocomplete.js file generates a URL that is broken (404). E.g. APPD shows the following error:

>152.83.116.103 - - [29/May/2018:14:56:51 +1000] "GET /appd-hub/undefined/search/auto.json?callback=jQuery1111006052041046479106_1527569805766&q=fusarium&limit=100&timestamp=1527569811165&_=1527569805767 HTTP/1.1" 404 1659 "https://appd.ala.org.au/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:60.0) Gecko/20100101 Firefox/60.0"

which in turn trigger an error message in the browser:

![image](https://user-images.githubusercontent.com/532845/40640347-f8b654a6-6358-11e8-86d7-65ef9a77afe6.png)

Actions:
- [ ] create an `autocomplete` config var that is the URL to the autocomplete service for the hub. This could be the BIE version or the biocache-service version (see https://github.com/AtlasOfLivingAustralia/biocache-service/issues/53)
- [ ] modify [bieAutocomplete.js](https://github.com/AtlasOfLivingAustralia/biocache-hubs/blob/master/grails-app/assets/javascripts/bieAutocomplete.js) to refer to the `autocomplete` from above

The `autocomplete` var could be determined programatically be checking if `bieService.baseUrl` is empty and then using the biocache-service implementation.

**Comment by nickdos** [comment]
FreshDesk ticket: https://support.ehelp.edu.au/helpdesk/tickets/17427

**Comment by nickdos** [comment]
This is effectively a duplicate of https://github.com/AtlasOfLivingAustralia/biocache-hubs/issues/128.

**Comment by alexhuang091** [comment]
Did a test on auto-complete from `biocache-service`. Which field should I use? `nameComplete` or `name`?

https://biocache-ws.ala.org.au/ws/autocomplete/search?pageSize=20&q=r

![1](https://user-images.githubusercontent.com/61677987/133375637-52dbd6e7-a475-4ad3-83be-afb641902c3a.jpg)
