### ISSUE TITLE
Incorrect coordinates in production biocache are not being shown to admins

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#263]
_From @ansell on June 6, 2018 23:48_

The correct coordinates for some records that were incorrectly processed by biocache-store are only being shown to logged in (possibly ``ROLE_ADMIN``?) users:

https://biocache.ala.org.au/occurrences/2889ba55-73d8-4262-bbf2-ca4a3e967899

Correct, when logged in:

![screen shot 2018-06-07 at 9 33 55 am](https://user-images.githubusercontent.com/82365/41070742-d424a698-6a37-11e8-8b2f-a707c8cfb7ae.png)

Incorrect, when logged out:

![screen shot 2018-06-07 at 9 33 30 am](https://user-images.githubusercontent.com/82365/41070745-da553640-6a37-11e8-9084-8affd42d05b3.png)

Logged in users should see the full information instead of having some of it hidden by their privilege.

EDIT: To clarify, the database was/is corrupted, but because I was logged in as an admin it appeared correct to me. I am not currently being shown the corrupted fields when logged in unless I know to look at the "Original versus processed", which shows the "Original" are not corrupted, but the "Processed" are corrupted. Data corruption is a serious issue that should not be hidden from administrators

_Copied from original issue: AtlasOfLivingAustralia/ala-hub#24_

**Comment by nickdos** [comment]
_From @javier-molina on June 7, 2018 5:18_

The code to display occurrence consistently uses raw values in preference of processed ones for admins (default clubRoleForHub=ROLE_ADMIN) for latitude, longitude and geodetic datum. There is a message at the top of the page that reads 'Showing "Club View"' when this values are displayed, this functionality seems to operate as per design

https://github.com/AtlasOfLivingAustralia/biocache-hubs/blob/00a06e87a3cf38a53eb9a27c1312f99516cc059c/grails-app/views/occurrence/_recordCore.gsp#L740 

In the description for this ticket the correct values are are indeed raw values.

In both cases (again in the description) the 'Compare "original vs processed" values' will show all the relevant values

![screen shot 2018-06-07 at 2 46 02 pm](https://user-images.githubusercontent.com/8326394/41079552-84112f40-6a65-11e8-84f3-831cb7d22c23.png)
 

The perceived error is the result of the processed longitude been filled with a latitude and not any display issues.

**Comment by nickdos** [comment]
_From @ansell on June 7, 2018 6:33_

Thanks for looking into it. It is an issue for me that my account isn't showing the processed values in the same way as the users I need to support, but will need to discuss a change to the policy.

**Comment by nickdos** [comment]
_From @javier-molina on June 7, 2018 6:45_

Probably not the end solution but don't discard what some of us do: we have
additional unprivileged accounts to test things as a 'normal' user.

**Comment by nickdos** [comment]
_From @ansell on June 7, 2018 7:46_

Unprivileged accounts are useful for seeing what disappears. The issue in this case is that for some reason the erroneous data in cassandra disappeared for me in my admin view after running biocache-store processing over cassandra, but the erroneous data (not just "desensitized") was still present so the database is still corrupted. To me, not showing an admin all of the data by hiding some data from them that shows the database is corrupted signals that the Occurrence Record User Interface isn't working well at this point (even if I can get a full comparison including the database corruption using a separate feature).

**Comment by nickdos** [comment]
I think this is a symptom of the data that is coming from biocache-service when there are SDS modified lat/lng values. ROLE_ADMIN users see the original coordinates (not modified by SDS) whereas normal users see the SDS-modified values. These should correspond to 2 sets of rows in Cassandra. The SDS-modified versions are wrong. So this issue should be moved into biocache-service or biocache-store.

EDIT: I see the same values for when I'm logged in and not logged in, so I think this is no longer an issue?

Because the data is coming from biocache-service from effectively different columns, we should probably make this clearer somehow on the UI - Dave has commented about this in a previous issue, so I'll try and link them up.

**Comment by nickdos** [comment]
_From @ansell on June 8, 2018 6:2_

As a data analyst, I would like to see both the original and the SDS modified versions in the ala-hub interface without having to open a separate section and search for the coordinate fields in the processed version to make sure they are not incorrect or missing. 

I don't mind where the issue is located, but at some point I would like the template in ala-hub updated to show admins both sets of information in the same style as non-admins are shown both pieces of information (labelled appropriately).

The corrupted data in this particular case is disappearing gradually. I am running the process again using a different biocache-store command which might be fixing things that the first command Adam suggested I use didn't fix.

**Comment by nickdos** [comment]
I agree Peter. This might be a good opportunity to revamp the display of the record information as the current display is a bit unclear on what is original/raw data and what has been modified or augmented by the ALA. I'll move this issue into biocache-hubs as a starting point.

**Comment by ansell** [comment]
If admins were able to see the same information as non-logged in users, it would have made it easier to debug this user query https://github.com/AtlasOfLivingAustralia/biocache-store/issues/324 . Specifically, having both the raw and processed values is important to helping users.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
