### ISSUE TITLE
Images tab shown only if Multimedia facet is selected

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/biocache-hubs#267]
Currently, the results page will only show the "images" tab if the "multimedia" facet is selected and there are images in the resulting search. As a consequence, the images tab disappears if the user deselects multimedia from the "customise filters" popup modal - which is unintuitive.

Fix is to always show the images tab (make it dependent on a config var so other portal providers can remove it if they don't have any images in their database). When populating the image body, it should request the images whether or not the facet is requested (see above). If no images found, then display a simple text message (i18n coded).

Images tab should be displayed regardless of the selected facets, currently it displays only if the multimedia facet is selected as one of the available facets (filters).

![Screen Shot 2018-06-26 at 4.56.59 pm.png](https://images.zenhubusercontent.com/56b920d76caf56c9d38c5513/fb98a659-f768-4a1f-8177-1e847095261c)

If a particular search contains no images then a "No images found" message should be displayed.

**Comment by djtfmartin** [comment]
this is already done. Just need to enable with config.

See

https://github.com/AtlasOfLivingAustralia/ala-install/blob/master/ansible/roles/biocache-hub/templates/config/config.properties#L73
