### ISSUE TITLE
sandbox - double-quotes not handled well

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#27]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=136
*date:* Thu Aug  8 16:40:49 2013
*author:* moyesyside
 ---

Original Issue reported by Reported by john.t...@austmus.gov.au, Mar 7, 2012 - [https://code.google.com/p/ala-portal/issues/detail?id=186](https://code.google.com/p/ala-portal/issues/detail?id=186)

Reported by john.tann@austmus.gov.au, Mar 7, 2012 
Sandbox doesn't cope well with a file that has (an odd number of) double-quotes in it.

**What steps will reproduce the problem?**
1. Copy contents of first attached file (Double-quotes-is-a-problem.csv) with 10 records into sandbox
 * note that one record (J57153) has an odd number of double-quotes
2. View data - only 6 records
3. Copy contents of second attached file (Double-quotes-is-not-a-problem.csv) with 10 records into sandbox
 * note that each record has an even number of double-quotes
2. View data - all 10 records

What is the expected output?
All 10 records should appear in the viewed data
 
What do you see instead?
Some records are missing - those after the record with the odd number of double quotes.

What version of the product are you using? On what operating system?
8 march version of sandbox
 Double quotes is a problem.csv 1.1 KB   View   Download Double quotes is not a problem.csv 1.2 KB   View   Download Mar 15, 2012 Project Member `#1` moyesyside@gmail.com 
(No comment was entered for this change.)
 Labels: sandbox

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/sandbox#13
