### ISSUE TITLE
Populate data in record page from SOLR

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#270]
This would be an ALA-specific change that could be toggled on & Off via a config variable (default to off ==  cassandra data). 

Currently the records pages are populated from a query against Cassandra, so this issue will likely need a similar WS call to populate values from SOLR (TODO create related issue).

Potential problems:
- user assertions

**Comment by ansell** [comment]
Other potential problems are any fields that are in cassandra but not in solr.

Being able to get the Cassandra version of a record using biocache-hubs and biocache-service is also very useful for data debugging.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
