### ISSUE TITLE
Replace all JSONP calls with normal JSON (CORS)

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#274]
JSONP is no longer required as we have CORS headers to allow JSON calls via the browser to our web services. The JSONP calls automatically get a cache-busting param added (by jQuery) which prevents our web service cache from working for these requests. 

Action: replace all jQuery JSONP calls with regular JSON ones. Check that no cache-busting params are being added.

**Comment by ansell** [comment]
The majority of JSONP calls into ``biocache-service`` seem to be from ``bie``, but there are calls from ``biocache-hubs``/``ala-hub`` also:

This is the log analysis I did on one of the two ``biocache-service`` production instances (``prod-bws-b5-1``) using yesterdays log file:

```
~# grep 'callback' /var/log/nginx/access.log.1 | wc -l
25649
~# grep 'callback' /var/log/nginx/access.log.1 | grep 'bie.ala.org.au' | wc -l
19613
~# grep 'callback' /var/log/nginx/access.log.1 | grep 'biocache.ala.org.au' | wc -l
4777
```

**Comment by nickdos** [comment]
Well spotted @ansell - I'll add a related issue for that and link it back here.

**Comment by ansell** [comment]
The longest current JSONP calls, in terms how how long ``biocache-service`` takes to answer them in the worst cases I can find, are those from ``explore-your-area`` to ``/ws/geojson/radius-points.jsonp``. The longest of these queries are around 80 or so seconds, and they are frequently duplicated in the log files. It would be very useful if those calls could be converted to JSON as a priority and then we can cache them to prevent multiple SOLR queries being executed for them.

**Comment by ansell** [comment]
Switched this to priority-medium as the Explore Your Area changes a few months ago that were tracked separately have substantially reduced this and it doesn't seem to be a performance critical issue currently.

**Comment by nickdos** [comment]
Found a few remaining calls:

[search results page](https://biocache.ala.org.au/occurrences/search?taxa=Pogona+minor#tab_mapView) (map tab) calls: https://biocache-ws.ala.org.au/ws/mapping/bounds.json?q=lsid%3Aurn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3A74b0b3d4-2feb-457d-b94c-91c7a0391d26&callback=jQuery34106789436365428312_1578271327218&_=1578271327219

**Comment by nickdos** [comment]
Ready for code review, for anyone picking this off the QA column.

**Comment by djtfmartin** [comment]
Happy to review. is there a PR ?

**Comment by ansell** [comment]
One comment from me based on visual inspection only of the code changes:

https://github.com/AtlasOfLivingAustralia/biocache-hubs/commit/4539cc44819d8535d59c2bbdf7451f3ecd375d86#comments
