### ISSUE TITLE
Include unassigned records when mapping subspecies

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#28]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=137
*date:* Thu Aug  8 16:40:59 2013
*author:* moyesyside
 ---

Original Issue reported by Reported by john.t...@austmus.gov.au, Mar 5, 2012 - [https://code.google.com/p/ala-portal/issues/detail?id=185](https://code.google.com/p/ala-portal/issues/detail?id=185)

Reported by john.tann@austmus.gov.au, Mar 5, 2012 
Overview of feature/enhancement:
When mapping occurrence records, please include all the records of a species when colouring a map by subspecies.

When working with subspecies, often there will be many records that have been identified to species level, but unassigned at subspecies level. When colouring a map by subspecies it will be useful to display all the records of that species, even where they are unassigned.

User story describing steps to use functionality:
* Person chooses species, eg Yellow chat
[http://biocache.ala.org.au/occurrences/search?taxa=yellow+chat#mapView](http://biocache.ala.org.au/occurrences/search?taxa=yellow+chat#mapView)
* Choose map
* Colour by subspecies
* All dots remain on map, some are coloured representing subspecies, and some are coloured representing the unassigned records of that species.

What the feature should look like (example URLs accepted):
See attached file
 subspecies.gif 121 KB   View   Download Mar 5, 2012 Project Member `#1` moyesyside@gmail.com 
agree the species not assigned to a subspecies should be visible somehow....
 Owner: nickdos@gmail.com Jul 10, 2012 Project Member `#2` nickdos@gmail.com 
The subspecies facet does not include an "other" category. This appears to be a back end enhancement?

**Comment by nickdos** [comment]
Appears to be fixed - they appears under the "Not specified" category.
