### ISSUE TITLE
bioache interface is trying to filter on duplicate_type which doesn't exist

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/biocache-hubs#282]
e.g. https://biocache.ala.org.au/ws/occurrences/search?q=*:*&facets=duplicate_type&pageSize=0&flimit=1000

duplicate_type field doesn't exist in the index - duplicate_status does

also affects spatial portal re support ticket https://support.ehelp.edu.au/a/tickets/22278

**Comment by nickdos** [comment]
Is this a biocache-hubs issue? If so could you indicate where this link is coming from, as there is not enough info to progress.

**Comment by nickdos** [comment]
![image](https://user-images.githubusercontent.com/532845/48106097-19bf4900-e28e-11e8-8723-84b16d729fc8.png)
