### ISSUE TITLE
HTML parsing on record details pages

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/biocache-hubs#284]
TML tags are parsed and displayed as text - there are some fields that need to be displayed as formatted html e.g. with links:

e.g. caption for: https://biocache.ala.org.au/occurrences/c31644ae-cb2b-4111-9966-afa8cac42f01

**Comment by nickdos** [comment]
I'm thinking is is a `won't fix`. The reason being, is we don't control the HTML content and it can (probably does) contain broken HTML, which would then break the display of the whole page. E.g. a missing closing tag would render the entire page as un-readable. 

The alternative is to run the content through a HTML parser first and only display it "rendered" if it passes that test.  Is it worth the extra trouble of doing this?

**Comment by M-Nicholls** [comment]
we don't need full HTML parsing I guess, it's more that we need be able to provide working links to other pages or sites for things like:
associated occurrences in tissue records - a biocache search
links to external repositories - e.g genbank or BOLD records

**Comment by nickdos** [comment]
Will investigate using an HTML parser/checker (I vaguely remember implementing something similar a few year back).

**Comment by nickdos** [comment]
Deployed on test - similar record https://biocache-test.ala.org.au/occurrences/a1a542e4-ffc3-488d-b2f9-c6fa72af8353

**Comment by nickdos** [comment]
Deployed to prod
