### ISSUE TITLE
Photographer/artist label for images

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/biocache-hubs#286]
Some images are drawings or paintings. Eg. https://images.ala.org.au/image/details?imageId=dff468a3-bf24-469a-841a-e59cd7de8079 If possible, relabel Photographer to Artist for those images.

EDIT: biocache link is more useful: https://biocache.ala.org.au/occurrences/3ccfffab-b0b0-46bb-970c-7e16137d7c8d

**Comment by nielsklazenga** [comment]
I noticed the same thing the other day. The actual term that is used in both [Audubon Core](http://tdwg.github.io/ac/termlist/#dcterms_creator) and the [GBIF Multimedia extension](http://rs.gbif.org/extension/gbif/1.0/multimedia.xml) is [creator](http://dublincore.org/2012/06/14/dcterms#creator). That would work for both photographs and illustrations.

**Comment by charvolant** [comment]
Creator is also what the image service returns

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
