### ISSUE TITLE
Boolean queries in advanced search screen fields of AVH / biocache

### ISSUE THREAD

**Issue by elywallis** [AtlasOfLivingAustralia/biocache-hubs#288]
Issue arises from issue logged by Murray Fagg (ANBG) on support: https://support.ehelp.edu.au/a/tickets/25388 

See also related issue #287 

Request is to be able to search in AVH, Advanced search, Collector field for two different names, to produce a single result. Use case is that Murray is trying to get information on lifetime collecting effort for someone who has changed their name during their life (example given is a woman who marries and changes her name). 

Issues identified:
* searching for people is always tricky because there's no names index to reference. How to find out if one A. Smith is the same as another? Also, that M. Nightingale is the same person as M.E. Nightingale? Sometimes, you just have to search and then facet to get the result you want.
* a persistent identifier for people would be very useful. There are a few that would be good to encourage use of: ORCID https://orcid.org/  RAId https://www.raid.org.au/ The botanical community also keeps a list of collector numbers - could these help?
* Collector field is on AVH advanced search page but not in ALA Biocache advanced search
* More general issue is one of Boolean searching and use of operators such as AND OR and " " It's not clear in the ALA interface which fields support Boolean queries

Comment from @nickdos (see #287 ) [snip]:  this will be a general "enhancement" issue to improve the advanced search interface. Its a tricky one because what Murray is asking for is straight forward if you type the query in by hand (in the URL) but is tough to do in a UI as you end up having a complex form that works some of the time for some of the users (small percent) and leaves the rest of the user base just confused. But I think we could make some small improvements in the short term and delay other changes for when we split out a simpler "simple" interface and a more powerful "expert" interface (UX review suggested this).

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
