### ISSUE TITLE
A record eventDate of '1984' is a problem

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#29]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=139
*date:* Thu Aug  8 16:41:23 2013
*author:* moyesyside
 ---

Original Issue reported by Reported by john.t...@austmus.gov.au, Jan 31, 2012 - [https://code.google.com/p/ala-portal/issues/detail?id=171](https://code.google.com/p/ala-portal/issues/detail?id=171)

Reported by john.tann@austmus.gov.au, Jan 31, 2012 
When only year is provided as eventDate, data quality tests incorrectly report a data validation issue.

**What steps will reproduce the problem?**
1. View an occurrence record with only the year recorded (eg eventDate=1868)
Data validation reports "Invalid collection date" 
Example [http://biocache.ala.org.au/occurrence/b01d329d-db2d-4eaf-ab27-4377bf11766f](http://biocache.ala.org.au/occurrence/b01d329d-db2d-4eaf-ab27-4377bf11766f)

What is the expected output?
Issue should be flagged, but not described as "invalid".

Note.
1. An eventDate of "1984" is a valid Darwin Core entry
See [http://rs.tdwg.org/dwc/terms/eventDate](http://rs.tdwg.org/dwc/terms/eventDate)
2. If a date is supplied as "year" (only) rather than eventDate, this does not show as an issue. See for example, [http://biocache.ala.org.au/occurrence/d5bf7ea7-b709-4855-ae4c-9365fd2fc936](http://biocache.ala.org.au/occurrence/d5bf7ea7-b709-4855-ae4c-9365fd2fc936)

 Jun 3, 2012 `#1` john.tann@austmus.gov.au 
A user has picked up the wrong formatting of dates. See flagged issue in:
[http://biocache.ala.org.au/occurrences/3e8fd01a-c741-419a-8c9f-4957f42961e8](http://biocache.ala.org.au/occurrences/3e8fd01a-c741-419a-8c9f-4957f42961e8)

In this case the eventDate was supplied as 1946-07 (valid Darwin Core format) 
ALA incorrectly converted that date to: Collecting date Year: 1946, Month: 07, Day: 1946-07
ALA data quality tests incorrectly reported an "invalid collection date"

**Comment by nickdos** [comment]
Now fixed - its a warning.
