### ISSUE TITLE
Searches with long URLs trigger error on download page

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#291]
As reported by a user today: https://support.ehelp.edu.au/a/tickets/25821

Also reported https://support.ehelp.edu.au/a/tickets/42606

Occurrence search https://goo.gl/MGFuaq

When you click on the download button, it returns an error: `This site can’t be reached - ERR_SPDY_PROTOCOL_ERROR` (in Chrome). The URL appears to be too long, due to extra params and encoding that the downloads-plugin employs.

Work-around is to get a `qid` for the query by going via the SP (info on layer shows qid).

Fix is to avoid long query strings and to add an extra step to generate a `qid` to then pass-on to the download page.

**Comment by nickdos** [comment]
Code fix is probably required in the download-plugin but I've deliberately kept issue in this repo, as we are planning on consolidating issues across repos for major products.

**Comment by nickdos** [comment]
Notes: 4000 limit for Apache. 
The biocache search URL is 3407
The download URL is 3973 (fails). 
Threshold is around 3795 chars but depends on the values, as some fail before that or after depending on the string values.

**Comment by nickdos** [comment]
Started work on this on a new branch - https://github.com/AtlasOfLivingAustralia/biocache-hubs/tree/QID-enhancements.

Some notes:

- set limit to 3000 characters (configurable) 
- redirects to QID param when QID is generated.

TODO still:
- [ ] Check QID is valid via the `/webportal/params/{qid}` call
- [ ] Create a better/more meaningful `query title` by parsing the output of `/webportal/params/details/{qid}`. Not sure if  this should be done in controller (synchronous) or done in the browser via AJAX (async).
- [ ] A nice-to-have addition is to detect a long `WKT` request on either the search page ([spatial search](https://biocache.ala.org.au/#tab_spatialSearch)) or when a user creates a polygon on the search results page, and then trigger a POST from the browser (to a controller in biocache-hub) that generates the QID.

**Comment by nickdos** [comment]
I was initially thinking long URLs could redirect to the `q=qid:foo123` request but after trying it, I realised it has the following limitations which make it confusing or broken for regular biocache searching:
- `fq` params are not "indicated" in the queryString returned from biocache-service. In the absence of any `fq` params in the URL, the interface has no way to show the user that the query has any `fq` filters applied (they are invisible).
- It is possible to get the list of `fq` filters by querying the service `/webportal/params/details/{qid}` but if the user then wants to remove a filter (which they can do with regular searches), then this breaks the `qid` query and requires creating a new one. This is complicated but probably not impossible.

Which begs the question of simply (silently) switching to POST requests when the query string gets longer than the threshold value (3000). `qid` searches could also be converted to proper POST requests, which would overcome the problems above.

**Comment by nickdos** [comment]
Update: fixing https://github.com/AtlasOfLivingAustralia/downloads-plugin/issues/49 has resulted in a reduction of the biocache-service URL from 8031 chars to 4272 chars. This will alleviate the issue but not fix it completely. 

QID or POST fix is a better long term solution.

**Comment by nickdos** [comment]
Ready for testing.
- [ ] code review [downloads-plugin changes](https://github.com/AtlasOfLivingAustralia/downloads-plugin/compare/2.0.7...master)
- [ ] code review [biocache-hubs changes](https://github.com/AtlasOfLivingAustralia/biocache-hubs/compare/2.1.2...master)
- [ ] functional testing biocache-test - view records with outlier layer count
- [ ] functional testing biocache-test - downloading records with long parameter lists  (se tickets at top)
- [ ] function testing for general regression bugs ([confluence page](https://confluence.csiro.au/display/ALASD/Biocache+manual+%28sanity%29+testing))

**Comment by Rita-C** [comment]
> Started work on this on a new branch - https://github.com/AtlasOfLivingAustralia/biocache-hubs/tree/QID-enhancements.
> 
> Some notes:
> 
>     * set limit to 3000 characters (configurable)
> 
>     * redirects to QID param when QID is generated.
> 
> 
> TODO still:
> 
>     * [ ]  Check QID is valid via the `/webportal/params/{qid}` call
> 
>     * [ ]  Create a better/more meaningful `query title` by parsing the output of `/webportal/params/details/{qid}`. Not sure if  this should be done in controller (synchronous) or done in the browser via AJAX (async).
> 
>     * [ ]  A nice-to-have addition is to detect a long `WKT` request on either the search page ([spatial search](https://biocache.ala.org.au/#tab_spatialSearch)) or when a user creates a polygon on the search results page, and then trigger a POST from the browser (to a controller in biocache-hub) that generates the QID.



> Started work on this on a new branch - https://github.com/AtlasOfLivingAustralia/biocache-hubs/tree/QID-enhancements.
> 
> Some notes:
> 
>     * set limit to 3000 characters (configurable)
> 
>     * redirects to QID param when QID is generated.
> 
> 
> TODO still:
> 
>     * [ ]  Check QID is valid via the `/webportal/params/{qid}` call
> 
>     * [ ]  Create a better/more meaningful `query title` by parsing the output of `/webportal/params/details/{qid}`. Not sure if  this should be done in controller (synchronous) or done in the browser via AJAX (async).
> 
>     * [ ]  A nice-to-have addition is to detect a long `WKT` request on either the search page ([spatial search](https://biocache.ala.org.au/#tab_spatialSearch)) or when a user creates a polygon on the search results page, and then trigger a POST from the browser (to a controller in biocache-hub) that generates the QID.

**Comment by Rita-C** [comment]
@nickdos , is https://github.com/AtlasOfLivingAustralia/biocache-hubs/tree/QID-enhancements part of the fix?

**Comment by nickdos** [comment]
No, that was an experimental branch that I've shelved. Did it slip into review?

**Comment by Rita-C** [comment]
> No, that was an experimental branch that I've shelved. Did it slip into review?

It wasn't in the review, I was reading all comments.

**Comment by Rita-C** [comment]
Code review and tests completed.
Moved to "waiting for" for https://github.com/AtlasOfLivingAustralia/biocache-hubs/issues/326 to be rectified.
