### ISSUE TITLE
BioCache search results: Changing ‘Sort Order’ changes other things

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#30]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=141
*date:* Thu Aug  8 16:41:52 2013
*author:* moyesyside
 ---

Original Issue reported by Reported by john.t...@austmus.gov.au, Jan 18, 2012 - [https://code.google.com/p/ala-portal/issues/detail?id=168](https://code.google.com/p/ala-portal/issues/detail?id=168)

Reported by john.tann@austmus.gov.au, Jan 18, 2012 
**What steps will reproduce the problem?**
1.Search for a taxa in BioCache, eg [http://biocache.ala.org.au/occurrences/search?taxa=shark](http://biocache.ala.org.au/occurrences/search?taxa=shark)
2.Default Sort options are:
Results per page = 20; Sort by = ‘DATE ADDED’; Sort order = REVERSE

What is the expected output? 
List of results to change from newest DATE at the top, to oldest DATE at the top

What do you see instead?
‘Sort by’ changed to ‘BEST MATCH’ (this should not have happened)
ie  Changing the ‘Sort order’, also changed the ‘Sort by’.

Part 2
I cannot set both ‘Results per page’ AND ‘Sort order’

1. What steps will reproduce the problem?
Search for a taxa in BioCache, eg [http://biocache.ala.org.au/occurrences/search?taxa=shark](http://biocache.ala.org.au/occurrences/search?taxa=shark)
2. Set ‘Results per page’ = 100
3. Set  ‘Sort order’ = NORMAL

What is the expected output? 
‘Results per page’ to remain at 100

What do you see instead?
‘Results per page’ reverted to 20

What version of the product are you using? On what operating system?
FF9, IE8 on WinXP 

Please provide any additional information below.
*Also enhancement* Can there be an option for ‘Results per page’ = 1000, please?

 Feb 7, 2012 Project Member `#1` moyesyside@gmail.com 
(No comment was entered for this change.)
 Owner: nickdos@gmail.com

**Comment by nickdos** [comment]
2 related bugs reported... both still in prod.

**Comment by nickdos** [comment]
Fixed.
