### ISSUE TITLE
Wrong link URL in Spatial search

### ISSUE THREAD

**Issue by CorinnaPaeper** [AtlasOfLivingAustralia/biocache-hubs#301]
The link to the Spatial Portal in the 'Import an existing GIS area' section in the Spatial search (https://biocache.ala.org.au/search#tab_spatialSearch) throws an error. For some reason the URL is https://biocache.ala.org.au/%7B0%7D

![image](https://user-images.githubusercontent.com/35747214/59896289-56aa0b80-942b-11e9-92c3-a6c3d00043be.png)

**Comment by nickdos** [comment]
Thanks @CorinnaPaeper - I'll take a look.
