### ISSUE TITLE
Add basisOfRecord field to advanced search form

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#302]
Basis of record is not one of the options provided on the advanced search page but I'm thinking it is important enough to include.

https://biocache-test.ala.org.au/search#tab_advanceSearch

Would be easy addition.

**Comment by elywallis** [comment]
Thumbs up from me - I think that a lot of users would be made very happy if BasisOfRecord could be used as a search term

**Comment by nickdos** [comment]
This was always in the code but the problem was the facets listed in the configuration, which are "cached" (and used to populate the drop-down values) was missing `basisOfRecord` for a short period. That was fixed at some point.
