### ISSUE TITLE
IE 11 bug for map popups

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#307]
Using IE 11 (or Edge 11) on a PC, some map functions are not working. Seen support ticket https://support.ehelp.edu.au/a/tickets/36604.

When viewing a search list page, with map tab visible, click on a record on the map.
E.g. https://biocache.ala.org.au/occurrences/search?q=lsid%3Aurn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3Ae9d6fbbd-1505-4073-990a-dc66c930dad6#tab_mapView

Expected behaviour is a popup div shows the record details. E.g.

![image](https://user-images.githubusercontent.com/532845/63239696-e1727f80-c28f-11e9-91a5-c14020b03577.png)

In IE 11, the "spinning" icon appears in the centre of the map but the popup does not appear.

**Comment by charvolant** [comment]
This popup issue has also appeared during faceting. https://support.ehelp.edu.au/a/tickets/38459

**Comment by M-Nicholls** [comment]
map pop-ups tested successfully in test on both IE11 and edge

The missing section on collectory pages mentioned above (https://support.ehelp.edu.au/a/tickets/38459) is not resolved in test on either browser

**Comment by M-Nicholls** [comment]
new issue for collectory pages: https://github.com/AtlasOfLivingAustralia/collectory-plugin/issues/156
