### ISSUE TITLE
Update all Leaflet plugins to be 1.5 version compatible

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#308]
See epic for background.

See regions app for example of calling `biocache-service` from Leaflet version 1.5

https://github.com/AtlasOfLivingAustralia/regions/blob/master/grails-app/assets/javascripts/region_page.js#L967

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
