### ISSUE TITLE
Update LeafletJS to latest version (1.5.x)

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#309]
We are currently running on [version 0.7.7](https://leafletjs.com/download.html) which had its last release in 2013 and has not been updated since 2015. A [recent IE11 bug](#307 ) has brought this issue into focus.

The Leaflet API changed after 0.7.7 and thus all the Leaflet plugin will require updating as well.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
