### ISSUE TITLE
Improve species display for 'Explore Your Area'

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#31]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=142
*date:* Thu Aug  8 16:42:02 2013
*author:* moyesyside
 ---

Original Issue reported by Reported by john.t...@austmus.gov.au, Dec 20, 2011 - [https://code.google.com/p/ala-portal/issues/detail?id=161](https://code.google.com/p/ala-portal/issues/detail?id=161)

Reported by john.tann@austmus.gov.au, Dec 20, 2011 
Overview of feature/enhancement:
Improve the means of displaying a long list of species in 'Exploer Your Area'. 
[http://biocache.ala.org.au/explore/your-area](http://biocache.ala.org.au/explore/your-area)

User story describing steps to use functionality:
Problem
Currently the number of species in my area that is displayed by default is limited to the first 50, listed in alphabetical order by scientific name. To increase the number displayed there is a 'Show more species' link at the bottom of the list, ie scroll down to the bottom of the list, and add 50 more.
If the list is long, eg plants with 5km of Black Mountain, and the plant you are interested in begins with a letter that is not 'A', then you need to scroll, click, scroll, click, scroll, click, and so on.
Very boring, and on a slow link can take ages. On a portable device in the field (which is where you might truly want to use this feature) it can be maddening.

What the feature should look like (example URLs accepted):
A suggestion
iPhones and iPads use a scrolling and jumping method that is alphabetical. Very good for long lists.
Can you do something like that?

Can you allow sort by likelihood (ie number of records), or common name?

 Feb 7, 2012 Project Member `#1` moyesyside@gmail.com 
We could investigate a load all instead of the next 50 or ajax style loading the rest of the list.

 Owner: nickdos@gmail.com

**Comment by nickdos** [comment]
Two enhancements since this issue was created, has provided equivalent functionality: link to "view all results" in main biocache search page and sorting by record count.
