### ISSUE TITLE
Results from biocache-service/ws/occurrences/GUID/assertions can be empty with no content type

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-hubs#311]
Currently, queries to biocache-service/ws/occurrences/GUID/assertions are assumed to return JSON documents. However, these responses seem to be able to be, `HTTP 200` `Content-Length: 0` responses as part of the normal execution. Note these responses are also missing a `Content-Type` header.

This causes entire records to not display correctly as the grails error fatally errors out the biocache-hub page:

https://biocache.ala.org.au/occurrences/f5fe00d4-c1be-4ac6-8322-d0b2b14c6e69

https://biocache-ws.ala.org.au/ws/occurrences/f5fe00d4-c1be-4ac6-8322-d0b2b14c6e69/assertions

The biocache-service code does not appear to be noteworthy, but there may also be an issue there:

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/master/src/main/java/au/org/ala/biocache/web/AssertionController.java#L337

Failures to fetch the assertions should not be causing the biocache-hub page to fail completely, so in either case, it should be fixed here.

**Comment by adam-collins** [comment]
Appears to be fixed. An empty JSON array is returned by that service today.
