### ISSUE TITLE
Change label for alau_user_id field

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#314]
Change requested by @peggynewman , is due to move to iNaturalist from Biocollect for sightings. We are using the existing SOLR field `alau_user_id` to store iNaturalist user names (and it already has user names from Flickr).

Change i18n labels, e.g.

`facet.alau_user_id=Atlas user`

to 

`facet.alau_user_id=Observer`

**Comment by peggynewman** [comment]
This field value ends up with a link on it to https://sightings.ala.org.au/spotter/<alau_user_id>
Will that link be removed as well?
Most of the data resources with these fields are BioCollect projects. The Flickr one looks to be the only non-Biocollect one.

**Comment by nickdos** [comment]
FIxed in c4a6957

**Comment by nickdos** [comment]
Testing:
https://biocache.ala.org.au/occurrences/f9dd1c91-bec7-4032-89cc-dffe0981fee2
vs
https://biocache-test.ala.org.au/occurrences/f9dd1c91-bec7-4032-89cc-dffe0981fee2

**Comment by M-Nicholls** [comment]
tested successfully in Test
