### ISSUE TITLE
Record page "User ID" appears twice

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#316]
Unintended consequence of renaming the label for `alau_user_id` to `User ID`.

https://biocache-test.ala.org.au/occurrences/f9dd1c91-bec7-4032-89cc-dffe0981fee2

Shows `User ID` as well as `User id`.

![image](https://user-images.githubusercontent.com/532845/64929783-c33b7780-d86d-11e9-9c8e-0a1348f55b10.png)

Fix is to check for both (including if they have the same text value) and only show the linked version.

**Comment by nickdos** [comment]
Deployed to biocache-test

**Comment by ansell** [comment]
"User ID" and "User id" are still both showing on:

https://biocache-test.ala.org.au/occurrences/f9dd1c91-bec7-4032-89cc-dffe0981fee2

**Comment by ansell** [comment]
This is broken for the following record in `3.2.3-SNAPSHOT` that was just deployed:

https://biocache.ala.org.au/occurrences/04eacba3-cec1-4d6b-8822-78444655081d

**Comment by ansell** [comment]
So I did the QA test for a sightings record on production where it is still broken. Fixed on test: 

https://biocache-test.ala.org.au/occurrences/04eacba3-cec1-4d6b-8822-78444655081d
