### ISSUE TITLE
alau_user_id field link broken for ALA users

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/biocache-hubs#318]
Sample record:
https://biocache.ala.org.au/occurrences/04eacba3-cec1-4d6b-8822-78444655081d

The User ID field contains: David Sando
And links to: https://sightings.ala.org.au/spotter/David%20Sando

... but this errors. The link needs to be: https://sightings.ala.org.au/spotter/1267

If a change goes through it should also regression test the field for iNaturalist users. 

Example record:
https://biocache.ala.org.au/occurrences/94f19c5b-1065-4ac1-9b77-2abf4c2bcbc4

The User ID field contains: peggydnew
And links to:  https://inaturalist.ala.org.au/people/peggydnew

**Comment by ansell** [comment]
`1267` is there as a raw value on the record, so this may just be a UI issue:

https://biocache-ws.ala.org.au/ws/occurrences/04eacba3-cec1-4d6b-8822-78444655081d

**Comment by nickdos** [comment]
Deployed to biocache-test.

**Comment by peggynewman** [comment]
Lovely. Works a treat for both record links above in biocache-test.

**Comment by ansell** [comment]
This is broken in the `3.2.3-SNAPSHOT` that was just deployed to the current biocache-test system (it was newly deployed last week).

**Comment by ansell** [comment]
So I did the QA test for a sightings record on production where it is still broken. Fixed on test:

https://biocache-test.ala.org.au/occurrences/04eacba3-cec1-4d6b-8822-78444655081d

**Comment by nickdos** [comment]
This has broken with Pipelines changes. 

- [ ] BioCollect records now have `alaUserId` field but code is likely expecting `ala_user_id` or `alau_user_id`. Fix to use camelcase version
- [ ] iNaturalist records are missing the expected `user_id` field in the JSON data. TODO link to issue to fix this. When data issue is fixed, check the field it marked-up as link, as per this issue details above.

**Comment by adam-collins** [comment]
It expects `raw.occurrence.userId` and `alaUserName`. I make the assumption that `alaUserName` is now `raw.occurrence.recordedBy`. This appears to resolve the issue for iNat and biocollect user links.

It does not resolve this issue for flickr links as they no longer have `raw.occurrence.userId`.
