### ISSUE TITLE
Sandbox enhancements

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#32]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=145
*date:* Thu Aug  8 16:42:48 2013
*author:* moyesyside
 ---

Original Issue reported by Project Member Reported by moyesyside, Sep 28, 2011 - [https://code.google.com/p/ala-portal/issues/detail?id=149](https://code.google.com/p/ala-portal/issues/detail?id=149)

Project Member Reported by moyesyside@gmail.com, Sep 28, 2011 
1) Mandatory authentication for data upload
2) Non-sequential IDs for data resources
3) Block view all - unless the user has ALA privileges
4) Dynamic facets

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/sandbox#14
