### ISSUE TITLE
Inferred associated records (duplicates) UI improvments

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#320]
The current duplicate display does NOT provide a link to the other records. E.g.

https://biocache.ala.org.au/occurrences/674aa318-8f9a-4218-a43f-6c47f0070c82

shows:

![image](https://user-images.githubusercontent.com/532845/66106770-0a619080-e602-11e9-9887-8cf0f62ee95a.png)

Suggestion is to link the record UUID to go to that record.
Also check this link is simply not displayed due to a data issue.

**Comment by nickdos** [comment]
Fixed with commit 584bc1ff

**Comment by nickdos** [comment]
Deployed to test site for QA.

**Comment by Rita-C** [comment]
Test and code review done.
