### ISSUE TITLE
Add identificationStatus field to Customise Filters

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/biocache-hubs#321]
This would be useful for iNaturalist for distinguishing Research Grade from Needs ID.

**Comment by ansell** [comment]
The changes necessary for this are the same as https://github.com/AtlasOfLivingAustralia/avh-hub/issues/99

Majorly, it requires a full CAB release of biocache-service at this point to add a single line to the i18n file (unless i18n file changes are exempt from CAB).

**Comment by nickdos** [comment]
We can now add i18n values via an external file, thanks to the changes added for LA hubs. Assuming this is now possible, we should be able to update files without going through CAB, as it would be covered as a "content update".

**Comment by ansell** [comment]
Would be useful to clear up the way we will be using the externalised i18n files and switch to using them.

**Comment by nickdos** [comment]
I'm in favour of moving to external i18n file. Creating a separate issue for this: https://github.com/AtlasOfLivingAustralia/ala-infrastructure/issues/536

**Comment by peggynewman** [comment]
Boo yah, can we add eventID to this?

**Comment by nickdos** [comment]
Adding the field is easy, assuming its indexed in biocache-service. The only thing to check, is whether the field has a human readable label in i18n entry, as @ansell hinted at above. If not, then we need to deploy updated versions of the hubs to allow the i18n files to be external and thus easily updated without deploying war files.

**Comment by ansell** [comment]
Best to do each field separately, so have created a new issue for eventID (but we can put them together in the same CAB release) https://github.com/AtlasOfLivingAustralia/biocache-hubs/issues/338

**Comment by alexhuang091** [comment]
This is what `biocache-service` returns and we thus show on UI (suppose `identificationStatus` is under `Identification` category). There's no solr field named `identificationStatus`, so which field to use? `identificationVerificationStatus` ?

<img width="529" alt="截屏2021-09-16 下午1 35 56" src="https://user-images.githubusercontent.com/61677987/133546086-6debdfab-f4b5-4fda-bdf8-ba26469672f2.png">

**Comment by adam-collins** [comment]
This is moved to (I cannot find the link, might be a different project)
