### ISSUE TITLE
Remove hard-coded dataResourceUid codes in taglib

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#328]
See https://github.com/AtlasOfLivingAustralia/biocache-hubs/blob/master/grails-app/taglib/au/org/ala/biocache/hubs/OccurrenceTagLib.groovy#L554

There are 3 instances of ALA-specific data resource IDs in the code here.

Fix: move hard-coded DR IDs to config var.

**Comment by nickdos** [comment]
Testing this change:

1. search for each of the DRs that were moved into config:
  dr364 -> https://biocache-test.ala.org.au/occurrences/search?q=data_resource_uid%3Adr364
  dr1411 -> https://biocache-test.ala.org.au/occurrences/search?q=data_resource_uid%3Adr1411
  dr360 -> https://biocache-test.ala.org.au/occurrences/search?q=data_resource_uid%3Adr360
2. Click on a record for each of the searches above and check that:
3. Check the`User ID` field contains a link andthe  link resolves to a page that corresponds to the observer/collector name. Link will be different for each DR.

**Comment by nickdos** [comment]
tested by @Rita-C - moved into ready-for-cab

**Comment by ansell** [comment]
The tests for this are broken for me locally and on travis, opening a new issue as this is already "in production"
