### ISSUE TITLE
Inconsistency of botanical taxonomic classifiation

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#33]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=146
*date:* Thu Aug  8 16:43:19 2013
*author:* moyesyside
 ---

Original Issue reported by Project Member Reported by waterand...@gmail.com, Sep 1, 2011 - [https://code.google.com/p/ala-portal/issues/detail?id=142](https://code.google.com/p/ala-portal/issues/detail?id=142)

Project Member Reported by waterandbirds@gmail.com, Sep 1, 2011 
**What steps will reproduce the problem?**
**1.**
Results set page
[http://bie.ala.org.au/search?q=Pteridium+esculentum](http://bie.ala.org.au/search?q=Pteridium+esculentum)
Pteridium esculentum Cockayne (G. Forst.)

**2.**
Species Profile page
[http://bie.ala.org.au/species/Pteridium%20esculentum](http://bie.ala.org.au/species/Pteridium%20esculentum)
Pteridium esculentum (G. Forst.) Cockayne
 
**3.**
Classification
[http://bie.ala.org.au/species/Pteridium%20esculentum#classification](http://bie.ala.org.au/species/Pteridium%20esculentum#classification)
Pteridium esculentum : Bracken

4. 
Occurrence records or single occurrence record
species: Pteridium esculentum | Austral Bracken
[http://biocache.ala.org.au/occurrences/taxa/urn:lsid:biodiversity.org.au:apni.taxon:313681](http://biocache.ala.org.au/occurrences/taxa/urn:lsid:biodiversity.org.au:apni.taxon:313681)
[http://biocache.ala.org.au/occurrences/f7463506-90a0-458b-905a-a219f172e275](http://biocache.ala.org.au/occurrences/f7463506-90a0-458b-905a-a219f172e275)

**What is the expected output? What do you see instead?**
Expected, should use APNI as a model.
[http://www.anbg.gov.au/cgi-bin/apni?taxon_id=2875](http://www.anbg.gov.au/cgi-bin/apni?taxon_id=2875)

Pteridium esculentum (G.Forst.) Cockayne

Instead:
Pteridium esculentum Cockayne (G. Forst.)
or
Pteridium esculentum (G. Forst.) Cockayne
or
Pteridium esculentum : Bracken
or 
Pteridium esculentum | Austral Bracken

**Please use labels and text to provide additional information.**
Reported by Arthur Chapman.

 Sep 1, 2011 Project Member `#1` waterandbirds@gmail.com 
From Jim Croft.

The first page is a mistake - either in the data or in the rendering. The zoological code allows free standing parenthetical authors, but the botanical code does not.
 
jim

 Sep 1, 2011 Project Member `#2` waterandbirds@gmail.com 
Another comment from Jim:

If you are going to render plant names without authurs, which is most instances is quite acceptable, remove the whole author string.
 
jim

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/bie-service#1
