### ISSUE TITLE
Add a prominent link/button to original record webpage (if it has one)

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#333]
This applies to records from datasets that have their own publically available record page, such as iNaturalist, BioCollect, eBird, etc.

E.g. https://biocache.ala.org.au/occurrences/9151d649-cc90-41a4-b6f7-f2c72898c40c

link will be the `occurrenceID` field: https://www.inaturalist.org/observations/8913486

Currently there is a link to the original record but it is mixed in with the other data fields and is thus easy for a user to not notice it. We want to encourage users to click through to the dataset's version of the record page, as it helps them generate traffic and also helps with potential errors, as it is better if users can report issues on the source system, as opposed to relying on the Flag an issue mechanism which requires another human intervention to flow through.

- [ ] Add a prominent link or button near top of record page to the original dataset record page (needs to check if the `occurrenceID` field contains a valid URL)
- [ ] On the dialog that appears, when you click "flag an issue", also show a link (possibly with some help text?) to the dataset record page, so we can nudge people to reporting issues on the dataset owners version.

**Comment by elywallis** [comment]
Note that some museums will also have their records on their own online collections sites. For example Museums Victoria Collections Online
Long necked Turtle in MV Collections https://collections.museumvictoria.com.au/specimens/1252045 
and same record in ALA https://biocache.ala.org.au/occurrences/2c639b9e-0ccc-4271-8ef6-a3bfa2a26304

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
