### ISSUE TITLE
Add "info" value to display of indexed fields table

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#336]
See https://biocache.ala.org.au/fields

Some fields have an additional "info" value that is not being shown in the table display. E.g. https://biocache.ala.org.au/fields?filter=native shows the field `natural_occurrence` which has the following JSON attributes:

```json
{
   "name":"natural_occurrence",
   "dataType":"string",
   "indexed":true,
   "stored":true,
   "multivalue":false,
   "docvalue":false,
   "info":"Equivalent to establishment means in darwin core. Values include native, non-native",
   "downloadName":"natural_occurrence"
}
```

Either add the `info` values to the  `Description` column in the table (append to any existing values - preferred as the table is already too wide) or create another column called "Info".

**Comment by alexhuang091** [comment]
how if an item has both `descriptin` and `info`, put them into one cell, separated by a `<br/>` ?

**Comment by adam-collins** [comment]
Still need to add `info` and `infoUrl`
