### ISSUE TITLE
Fieldguide links fail to show records on the first page

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-hubs#337]
The link that Fieldguide is generating inside of the PDF file as the "original query link" doesn't show records on the first page of results when you view it on `biocache.ala.org.au`.

However, when you go the Maps, Charts, and Images tabs it seems to be working, and when you click on Page 2 it works, and when you click back to Page 1 it works again

It fails for me in both Firefox and Safari `https://biocache.ala.org.au/occurrences/search?file=records-2020-02-26&reasonTypeId=10&dwcHeaders=true&fileType=csv&qa=none&sourceTypeId=0&email=example%40example.org&q=qid%3A1582585638879&&pageSize=0&&facet=true&`

**Comment by nickdos** [comment]
`pageSize=0` is the offending param. 

Easy fix would be to catch this value and substitute the default `pageSize` as I can't think of any use-case where having a zero `pageSize` would be useful...

**Comment by ansell** [comment]
If fieldguide had a maintainer, I would be inclined to strip all pageSize variables there and rely completely on the default pageSize of the hub at the other end of the link.

Removing/ignoring `pageSize=0` is a good second alternative.

**Comment by nickdos** [comment]
@ansell would you mind QA'ing this issue ([code change](https://github.com/AtlasOfLivingAustralia/biocache-hubs/commit/4938c4bc982b762a286ebf2832086328beb96602) and confirm in test)? thanks

**Comment by ansell** [comment]
Confirmed this is fixed on biocache-test, it now shows a page of results as expected.
