### ISSUE TITLE
Add eventID field to customise filters (facets)

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-hubs#338]
Request to add i18n for `eventID` field and add it to `Customise Filters` as a user-selectable facet.

https://github.com/AtlasOfLivingAustralia/biocache-hubs/issues/321#issuecomment-591729303

**Comment by peggynewman** [comment]
Hooray! Thank you.

**Comment by nickdos** [comment]
Testing this, I'm finding there are 3 facet values which return no results...

https://biocache-test.ala.org.au/occurrences/search?q=data_resource_uid:%22dr359%22

Turn on "event ID" facet under "Customise filters" and then click the `choose more...` link. Then order by count (click count column) and try the first 3 options. They all fail with "no results found" all the other values return the expected result set. Can't work out any pattern to explain why they are failing.

![image](https://user-images.githubusercontent.com/532845/77502677-9a94da00-6eaf-11ea-9a7c-4a9b8a3a5e14.png)

**Comment by ansell** [comment]
@nickdos This appears to be a regression with the data quality project changes. Turning off all four of the data quality project filters makes the records show again for those event id's, which makes me think the data quality project changes should be rolled back at this point until they aren't regressing the rest of the interface.

**Comment by ansell** [comment]
Working URL:

https://biocache-test.ala.org.au/occurrences/search?q=data_resource_uid%3A%22dr359%22&disableQualityFilter=dates&disableQualityFilter=taxon-identification&disableQualityFilter=location&disableQualityFilter=quality-assertions&fq=event_id%3A%225099941%22

Failing URL (which should be working):

https://biocache-test.ala.org.au/occurrences/search?q=data_resource_uid%3A%22dr359%22&fq=event_id%3A%225099941%22

**Comment by nickdos** [comment]
> https://biocache-test.ala.org.au/occurrences/search?q=data_resource_uid%3A%22dr359%22&fq=event_id%3A%225099941%22

Works for me. How is it failing?

**Comment by ansell** [comment]
<img width="1674" alt="Screen Shot 2020-03-30 at 9 32 40 am" src="https://user-images.githubusercontent.com/82365/77862785-6fbcd400-7269-11ea-9715-8b3dbc0339b6.png">

The immediate conclusion is that the hidden default filters are hiding the records for that event id completely.

**Comment by nickdos** [comment]
Here's what I see:

![image](https://user-images.githubusercontent.com/532845/77862873-fd98bf00-7269-11ea-8871-469352e9ccf7.png)

**Comment by ansell** [comment]
Can you check https://biocache-test.ala.org.au/buildInfo ?

This is what it shows for me, which seems to imply I am looking at a Data Quality project version:

<img width="772" alt="Screen Shot 2020-03-30 at 9 39 09 am" src="https://user-images.githubusercontent.com/82365/77862935-61bb8300-726a-11ea-9356-b238d2258676.png">

**Comment by nickdos** [comment]
Yep, still DQ branch - that was just a guess.

**Comment by alexhuang091** [comment]
https://biocache-test.ala.org.au/occurrences/search?q=data_resource_uid%3A%22dr359%22&fq=event_id%3A%225099941%22

doesn't work because the 251 records returned have 'Not supplied coordinate uncertainty' but location quality filters needs `coordinate_uncertainty:["0" TO "10000"]` so they are all filtered out

**Comment by ansell** [comment]
@alexhuang091 That is going to be a big issue if it gets into production in that form as it will cause chaos with our data providers.

There needs to be some indication on that page of what happened and a way to disable the filters to let the query execute normally. 

Probably best to track that bug separately on https://github.com/AtlasOfLivingAustralia/DataQuality/issues/58 

Until the data quality version of ala-hub is ready for wider testing it should only be deployed to biocache-dq-test.ala.org.au rather than biocache-test.ala.org.au

**Comment by ansell** [comment]
The discussion for the other part of the issue with the proposed `coordinate_uncertainty` filter being far too broad at this point is being tracked separately at https://github.com/AtlasOfLivingAustralia/DataQuality/issues/31

**Comment by alexhuang091** [comment]
Yes, all future release will be deployed to biocache-dq-test.ala.org.au

We'll discuss to see how to show the result properly to the users.
