### ISSUE TITLE
Explore your area - inconsistent record count between facets & map points

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#34]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=147
*date:* Thu Aug  8 16:43:42 2013
*author:* moyesyside
 ---

Original Issue reported by Reported by brynk.ala@gmail.com, Jan 12, 2011 - [https://code.google.com/p/ala-portal/issues/detail?id=129](https://code.google.com/p/ala-portal/issues/detail?id=129)

Reported by brynk.ala@gmail.com, Jan 12, 2011 
**What steps will reproduce the problem?**
1. go to this url - [http://biocache.ala.org.au/explore/your-area#-35.3|149.2|11](http://biocache.ala.org.au/explore/your-area#-35.3|149.2|11)
2. left-click 'fungi' facet to limit results to fungi classification - note facet count in brackets is (280)
3. now, 3 results will appear - the dark red result near the 'canberra international airport' has 160 occurrence records and the result near yarralumla has 359

if you go to [http://biocache.ala.org.au/occurrences/searchByArea?q=kingdom:Fungi|-35.3|149.2|10](http://biocache.ala.org.au/occurrences/searchByArea?q=kingdom:Fungi|-35.3|149.2|10) you will see that there are 500-odd fungi records which is consistent with the sum of the dots on the map

maybe the facet count is not rolling up counts from sub-groups?

firefox 3.6.11 on xp sp 3

**Comment by nickdos** [comment]
Can no longer reproduce - closing issue.
