### ISSUE TITLE
Allow searching on dataset_name field (survey name)

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#341]
This has been requested by people in the collections community (reported to @elywallis) and relates to values that are provided in the DwC `dataset_name` field (not to be confused with the `data_resource` field (see #242).

There are at least 2 use cases:
- [x] Allow users to facet on `dataset_name`. Add `dataset_name` field to the list of facets that are shown on a results page (can be activated via the "customise filters" button. This also requires `dataset_name` to be included in the `grouped_facets_ala.json` file so it gets displayed in the appropriate section.
- [ ] Allow users to search for a substring against the `dataset_name` field. Currently `dataset_name`  is a `string` field in the SOLR schema and can only be "found" when an exact match query is used.  Therefore to allow Google-style searching, a new SOLR field needs to be created (`text` type) and then the `dataset_name` (and possibly `data_resource` as well) need to be copied into this field. Once this field is searchable, the advanced search page needs an additional field for `Survey/dataset name` to be added, to allow users to be able to search it.

**Comment by nickdos** [comment]
Second action: 

https://github.com/AtlasOfLivingAustralia/ala-install/search?q=collector_text&unscoped_q=collector_text 

edit files:
- [ ] https://github.com/AtlasOfLivingAustralia/ala-install/blob/726b21a0738320261f6e94e20ca65bd2bc284a92/ansible/roles/biocache-cli/files/vocab/indexFields.txt
- [ ] https://github.com/AtlasOfLivingAustralia/ala-install/blob/79d11379928728fc3ddced424c5d030655291125/ansible/roles/biocache-cli/files/solr-template/biocache/conf/schema.xml
- [ ] https://github.com/AtlasOfLivingAustralia/ala-install/blob/580166f58ef051c093fde8ac5595cca9bf48a2ca/ansible/roles/solrcloud_config/templates/biocache_schema.xml
- [ ] https://github.com/AtlasOfLivingAustralia/ala-install/blob/580166f58ef051c093fde8ac5595cca9bf48a2ca/ansible/roles/solrcloud_config/templates/biocache_schema_docvalues.xml

**Comment by nickdos** [comment]
Hold off until infrastructure upgrade stage 1 is complete & implement after its live.

**Comment by nickdos** [comment]
Post-upgrade, this should be a simple change to SOLR index.

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/ala-install/commit/75ea0b71cb50922006b71f983979b3f5e90eba5f

**Comment by adam-collins** [comment]
Appears done, `text_datasetName` is a field on the search page.
