### ISSUE TITLE
Add IBRA-7 Subregions facet to Customise Filters list

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-hubs#342]
Request from a user to add the `IBRA-7 Sub-regions` facet `cl1049` to the Customise Filters list in the hub interface.

Refs ticket 76181 in freshdesk

**Comment by nickdos** [comment]
Just tested locally and i18n is already there:

![image](https://user-images.githubusercontent.com/532845/76927469-28fae000-6933-11ea-8d15-febdeea8a2d1.png)

**Comment by nickdos** [comment]
Deployed to https://biocache-test.ala.org.au. 

@ansell please QA

**Comment by ansell** [comment]
LGTM: 
<img width="1314" alt="Screen Shot 2020-03-18 at 5 08 56 pm" src="https://user-images.githubusercontent.com/82365/76930691-2d2afb80-693b-11ea-969c-145ad00b8eb3.png">
