### ISSUE TITLE
Hide Verbatim associated media from record view (ALA)

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#345]
`verbatimAssociatedMedia` field is not useful to show and for some ALA records is showing a URL that is no longer maintained.

Therefore hide this field from record view page.

Further investigation shows this needs 2 set of changes:
- [x] Modification of GSP code to check if `additional properties` fields are listed in the `dwcExcludeFields` variable (config set)
- [x] add `verbatimAssociatedMedia` to the `dwc.exclude` list in ansible inventories repo

**Comment by ansell** [comment]
@nickdos Do you have an example of a URL on production which currently shows `verbatimAssociatedMedia` for testing purposes?

**Comment by nickdos** [comment]
https://biocache.ala.org.au/occurrences/dad63624-a88a-42d4-9c96-b020c549e0b4

**Comment by ansell** [comment]
Verified that that record no longer shows the verbatim associated media field on the record view page on biocache-test
