### ISSUE TITLE
Record page: rename Locality field as LGA

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#353]
Looking at a record in JSON (https://biocache.ala.org.au/ws/occurrences/ce6f38ab-0ccc-411e-85e9-388b1bbe63f4) the field shown on the UI as `Locality` (value: `Gympie (R)`) is actually `processed.location.lga`.

- [ ] correctly label the field as `LGA` and 
- [x] ~~add a check to include the real `locality` field, if present in the data (if not already present)~~

https://biocache.ala.org.au/occurrences/545cf4e6-c73e-492f-871f-4db3202d2cd4 shows 2 fields labelled `Locality` so second action not needed.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
