### ISSUE TITLE
Search result sorting problem

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#358]
Sorting of search results seems to be inconsistent. Do some testing and check all the sort options & combinations are working as expected.

- [x] change sort direction (to ascending) on default sort values... sort_field changes to "best match" from "date added"
- [x] change sort field to "record date" and order "descending", then click page 2 of results. The sort direction changes to "ascending"

Steps to reproduce the original issue:
    View a list of records, eg: https://biocache.ala.org.au/occurrences/search?q=lsid:urn:lsid:biodiversity.org.au:afd.taxon:a1408f1a-50e5-4f9c-8cdf-bd6f27a12828#tab_recordsView
    Scroll down and click "Next" a couple of times. The pages advance as expected, by default sorted by "Date added" and in "Descending" order.
    Change the order to "Ascending". The page will refresh, sorting records in ascending order, and returning to page 1 of results. The "sort by" option also changes from "Date added" to "Best match".
    Scroll down and click "Next". The page advances but the order switches back to "Descending" and sort by returns to "Date added".

See also AtlasOfLivingAustralia/avh-hub/issues/78 & #372.

----
From #372:
This is hard to explain, so steps to reproduce:
1. View a list of records, eg: https://biocache.ala.org.au/occurrences/search?q=lsid:urn:lsid:biodiversity.org.au:afd.taxon:a1408f1a-50e5-4f9c-8cdf-bd6f27a12828#tab_recordsView
2. Scroll down and click "Next" a couple of times. The pages advance as expected, by default sorted by "Date added" and in "Descending" order.
3. Change the order to "Ascending". The page will refresh, sorting records in ascending order, and returning to page 1 of results. The "sort by" option also changes from "Date added" to "Best match".
4. Scroll down and click "Next". The page advances but the order switches back to "Descending" and sort by returns to "Date added".

**Comment by nickdos** [comment]
Explanation for fix 2. We are using the Grails pagination tool, which assumes the params for sort order and sort field as fixed (to what Grails uses). So I needed to map the 'dir' param that biocache uses to Grails' `order` param.

**Comment by Rita-C** [comment]
I like the `steps to reproduce` in #372, it provides background information and should be included in a bug ticket. Can I suggest to copy it over given #372 is closed, @nickdos ? cc @timhicks-ala

**Comment by nickdos** [comment]
@Rita-C good idea, go ahead a copy into here, thanks.

**Comment by nickdos** [comment]
@Rita-C could you please test this issues is fixed on https://biocache-test.ala.org.au/ ? Thanks.

**Comment by Rita-C** [comment]
Tested different combinations of `sort` and `order`, then clicked next page/page number, pages displayed as expected.
