### ISSUE TITLE
Map shows no dots for shapefile upload search

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#36]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=195
*date:* Thu Aug  8 17:18:32 2013
*author:* moyesyside
 ---

Original Issue reported by Project Member Reported by nickdos, Jun 20, 2012 - [https://code.google.com/p/ala-hubs/issues/detail?id=84](https://code.google.com/p/ala-hubs/issues/detail?id=84)

Project Member Reported by nickdos@gmail.com, Jun 20, 2012 
[http://biocache.ala.org.au/occurrence/search?q=qid:1340175979066](http://biocache.ala.org.au/occurrence/search?q=qid:1340175979066)

(qid might not be cached for ever so link may fail)

click on map tab, map zooms to correct bounds but no dots are shown.

Hint: might be due to very long query string, so maybe try qid query instead of wkt?

**Comment by nickdos** [comment]
Can't reproduce.
