### ISSUE TITLE
Missing i18n label for user assertion drop-down

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#365]
The "Other" category in the dop-down optoins for user assertions, is showing a raw value `userAssertionOther` but should display (just) `Other`:

![image](https://user-images.githubusercontent.com/532845/87500991-523d3a00-c6a1-11ea-9802-ad23e1b490f7.png)

**Comment by nickdos** [comment]
Code review requested https://upsource.ala.org.au/biocache-hubs/review/BH-CR-54

**Comment by nickdos** [comment]
Hi @Rita-C - when you get the chance, could you please do CR and test fix, thanks?

**Comment by Rita-C** [comment]
Tested OK
![Screen Shot 2021-01-19 at 8 43 47 am](https://user-images.githubusercontent.com/29115246/104965272-7a339e80-5a32-11eb-93bd-aa53de3d0cef.png)
