### ISSUE TITLE
Facet modal popup missing "Count" heading

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#368]
This is a bug that has crept in since version `2.1.7`. See screenshot:

![image](https://user-images.githubusercontent.com/532845/88010239-bfe0de80-cb57-11ea-89f3-aeaf8f402c72.png)

I suspect i18n tag or value is the culprit.

**Comment by nickdos** [comment]
@Rita-C could you please QA this issue ([code chang](https://github.com/AtlasOfLivingAustralia/biocache-hubs/commit/89ae92763906a63830251782e077a862a2fc5de4)e and on test site)? Thanks

**Comment by Rita-C** [comment]
Count heading appears on prod, already deployed?
![Screen Shot 2020-08-31 at 10 41 59 am](https://user-images.githubusercontent.com/29115246/91673290-d32f9280-eb76-11ea-84a4-47df55767532.png)

**Comment by nickdos** [comment]
Not deployed - broke on test after PR from LA community, which was detected during QA testing. So I then fixed it after that.

**Comment by Rita-C** [comment]
Count heading shown on the page, defect fixed.
