### ISSUE TITLE
Encode square bracket characters in query URLs

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-hubs#369]
Bug identified in testing of biocache-hubs with Tomcat-8 and Tomcat-9 relating to the lack of encoding of the square bracket characters in query URLs.

The regression is (at least) in the following:

* Choose Advanced Search
* Enter dates into the "Begin date" and "End date" input boxes and click `Search`

Observe the following failure if using Tomcat-8 or Tomcat-9 due to the lack of encoding of the `[` and `]` characters:

`https://biocache-test.ala.org.au/occurrences/search?q=occurrence_date%3A[2020-07-20T00%3A00%3A00Z+TO+2020-07-29T00%3A00%3A00Z]`

<img width="1177" alt="Screen Shot 2020-07-30 at 1 24 00 pm" src="https://user-images.githubusercontent.com/82365/88877034-f5787c80-d267-11ea-83a6-d66ed5c5e8ea.png">

```
java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
	org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:479)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:684)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:748)
```

The solution is to encode the `[` as `%5B` and the `]` as `%5D`:

`https://biocache-test.ala.org.au/occurrences/search?q=occurrence_date%3A%5B2020-07-20T00%3A00%3A00Z+TO+2020-07-29T00%3A00%3A00Z%5D`

**Comment by nickdos** [comment]
Adding copy here from Slack:

We might be able to fix this with a Tomcat config setting relaxedQueryChars see https://tomcat.apache.org/tomcat-9.0-doc/config/http.html
> The HTTP/1.1 specification requires that certain characters are %nn encoded when used in URI query strings. Unfortunately, many user agents including all the major browsers are not compliant with this specification and use these characters in unencoded form. To prevent Tomcat rejecting such requests, this attribute may be used to specify the additional characters to allow. If not specified, no additional characters will be allowed. The value may be any combination of the following characters: " < > [ \ ] ^  { | }` . Any other characters present in the value will be ignored.

@ansell wrote:
I will add `relaxedQueryChars='[]'  to aws-biocache-service-test-1  (biocache-ws-test)

**Comment by ansell** [comment]
That addition should still only be a temporary measure until we transform our apps to encode those characters.

**Comment by nickdos** [comment]
I'm thinking that, because this is a legacy system with a planned replacement, we might just leave that setting in there. Its not just the hubs that call these services but lots of other ALA and third party clients do too. We also have API docs that have examples that are not encoded, etc. Unless there is a clear "threat" of keeping this setting on, then we have nothing to loose vs trying to find and fix all cases of un-encoded client calls "in the wild" (arguably a greater risk).

**Comment by ansell** [comment]
It is all setup using Ansible now, so we can sustainably maintain it for as long as Tomcat maintains support for it in the future. The threats behind the requirements to URL encode characters are generally around Cross-Site-Scripting (XSS) but these two square bracket characters aren't particularly sensitive for HTML as far as I know.

**Comment by ansell** [comment]
Closing this as won't fix
