### ISSUE TITLE
Different colour scheme for decades

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#37]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=202
*date:* Thu Aug  8 17:20:02 2013
*author:* moyesyside
 ---

Original Issue reported by Project Member Reported by moyesyside, Oct 24, 2011 - [https://code.google.com/p/ala-hubs/issues/detail?id=21](https://code.google.com/p/ala-hubs/issues/detail?id=21)

Project Member Reported by moyesyside@gmail.com, Oct 24, 2011 
The colour scheme in use for decades is intended to help show a continous variable, but makes it hard to pick out different months.

Reported by Aaron. See screenshot
 aaron-image002.png 89.5 KB   View   Download Jan 5, 2012 Project Member `#1` nickdos@gmail.com 
I've been looking for a better colour scheme but did not find anything. Will ask Mark when he's in.
 Status: Started

**Comment by nickdos** [comment]
![image](https://cloud.githubusercontent.com/assets/532845/5796675/2b8b29b2-a000-11e4-8fde-9da24451d99e.png)

**Comment by nickdos** [comment]
Old issue, colours are now different and differentiate better.
