### ISSUE TITLE
Sound files on records should display link to file in images.ala.org.au

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#370]
See AtlasOfLivingAustralia/helpdesk/issues/48.

- [ ] Sound file do not have a link back to the associated record in the images.ala.org.au system, like images do. E.g. the link should be: [View sound details](https://images.ala.org.au/image/592a1700-895f-44f1-86f8-02f22ef4ed24)

E.g. https://biocache.ala.org.au/occurrences/61e5e397-60fd-4bb7-945b-172e01a0900f

![image](https://user-images.githubusercontent.com/532845/90718322-00697e80-e2f5-11ea-866b-dcdca07e865c.png)
 should have licensing info under the sound player.

vs
https://biocache.ala.org.au/occurrences/359e50ce-9264-4e9e-bd0d-46b1d8ed72d3
![image](https://user-images.githubusercontent.com/532845/90719906-de71fb00-e2f8-11ea-9ac7-ccec7fd3abc6.png)

- [ ] Also check to see that sounds files display the license info - can't find a record to confirm this, so code should be checked.

**Comment by alexhuang091** [comment]
Hi @nickdos 

The related sound url returned by search is `https://images.ala.org.au/image/proxyImage?imageId=3b32f5f0-529b-41b7-8e8d-d073a6ddda86`, it should be `https://images.ala.org.au/image/3b32f5f0-529b-41b7-8e8d-d073a6ddda86`

These 2 links are different(you can have a try). We need to convert to link 2 and display, right?



<img width="928" alt="截屏2021-08-13 下午3 53 22" src="https://user-images.githubusercontent.com/61677987/129311625-431ad0fb-f5cf-45cb-a0ea-bd30ab51e77b.png">

**Comment by nickdos** [comment]
I'm not sure without looking at code. Might be the sound-player widget needs one form of the URL and to display the metdata (license info), you need to generate the JSON data version?

https://images.ala.org.au/image/3b32f5f0-529b-41b7-8e8d-d073a6ddda86.json

**Comment by alexhuang091** [comment]
> I'm not sure without looking at code. Might be the sound-player widget needs one form of the URL (first one) and to display the metdata (license info), you need to generate the JSON data version?
> 
> https://images.ala.org.au/image/3b32f5f0-529b-41b7-8e8d-d073a6ddda86.json

Thanks Nick, I see what you mean. So I'll check how to return both from `biocache-service` and make changes on biocache-hubs accordingly.

**Comment by nickdos** [comment]
Could be done in hubs controller, directly and not involve biocache-service, maybe?

**Comment by alexhuang091** [comment]
Hi Nick, above `record` object is returned from `biocache-service`

`JSONObject record = webServicesService.getRecord(id, hasClubView)`

`record.sounds` contain all the information of sound. It effectively only has `https://images.ala.org.au/image/proxyImage?imageId=3b32f5f0-529b-41b7-8e8d-d073a6ddda86`

you mean extra the id and call https://images.ala.org.au/image/{id}.json from `hubs`?

**Comment by alexhuang091** [comment]
In `biocache-service` we just need the `soundID` to construct the media url
<img width="976" alt="截屏2021-08-13 下午5 31 14" src="https://user-images.githubusercontent.com/61677987/129321390-a9dbc292-55cb-4bf3-a352-c5268f0e2a7b.png">
<img width="485" alt="截屏2021-08-13 下午5 34 24" src="https://user-images.githubusercontent.com/61677987/129321404-98237cb5-1671-4877-b61c-4ec07af144d0.png">

**Comment by nickdos** [comment]
> you mean extra the id and call [https://images.ala.org.au/image/{id}.json](https://images.ala.org.au/image/%7Bid%7D.json) from `hubs`?

Yes, I should've been clearer, sorry. So grab that URL, extract the `{id}` part and then call the JSON service to then get the license and other metadata. Do this from the hubs controller (via a service method) and add it to the `model` object that can be used to display the info via the GSP. Similar to how the `compare` object is added - see https://github.com/AtlasOfLivingAustralia/biocache-hubs/blob/develop/grails-app/controllers/au/org/ala/biocache/hubs/OccurrenceController.groovy#L373

**Comment by alexhuang091** [comment]
Hi Nick, quick question.

How to construct the link [View sound details](url)?

- It should point to `https://images.ala.org.au/image/{imageID}`
- Or it should be the value in `metadata.references` which not necessarily point to `images.ala.org.au`




<img width="757" alt="截屏2021-08-16 下午12 34 26" src="https://user-images.githubusercontent.com/61677987/129503904-9f8da5b6-9adb-45ba-a60b-425aebdd202b.png">

<img width="707" alt="截屏2021-08-16 上午10 09 39" src="https://user-images.githubusercontent.com/61677987/129504168-49a6d4a8-9413-4275-be63-0e1123fdfa2e.png">

**Comment by nickdos** [comment]
No idea - you'll need to look at the code that generates the link for the sound player... you might also be able to use browser inspect tool to get the sound URL, as well? Was that the question - not 100% sure what you're asking....
