### ISSUE TITLE
Searches that trigger an error show "no records found"

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#371]
E.g. https://biocache.ala.org.au/occurrences/search?q=-latitude%3A*&fq=-country%3A*&fq=-state%3A*&fq=-locality:*

shows `No records found for -latitude:*`.

There are 2 issues that need fixing:

- [x] when biocache-service returns 0 results, the UI should show the full query, similar to how it is displayed when results are found. E.g. 

> 593,861 results for -latitude:* with filters: [exclude] State/Territory:* and [exclude] Country:* 

- [x] If biocache-service has returned an error, then this should be presented to the user (see URL above).

https://biocache.ala.org.au/ws/occurrences/search?q=-latitude%3A*&fq=-country%3A*&fq=-state%3A*&fq=-locality:* 

returns: 

```
status: "ERROR",
errorMessage: "Error from server at http://aws-sc5b.ala:8983/solr/biocache: undefined field locality"
```

Display the error in the UI so the user can change the query to fix the issue.

**Comment by nickdos** [comment]
Deployed to test for QA.

**Comment by Rita-C** [comment]
tested both scenarios, displayed messages as expected.
