### ISSUE TITLE
Ascending/descending order option not persisting when paging through records

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/biocache-hubs#372]
This is hard to explain, so steps to reproduce:

1. View a list of records, eg: https://biocache.ala.org.au/occurrences/search?q=lsid:urn:lsid:biodiversity.org.au:afd.taxon:a1408f1a-50e5-4f9c-8cdf-bd6f27a12828#tab_recordsView
2. Scroll down and click "Next" a couple of times. The pages advance as expected, by default sorted by "Date added" and in "Descending" order.
3. Change the order to "Ascending". The page will refresh, sorting records in ascending order, and returning to page 1 of results. The "sort by" option also changes from "Date added" to "Best match".
4. Scroll down and click "Next". The page advances but the order switches back to "Descending" and sort by returns to "Date added".

**Comment by nickdos** [comment]
Might be related (or duplicate) of #358

**Comment by timhicks-ala** [comment]
@nickdos I agree it's basically a duplicate, with some additional information.

Speaking of #358, I'd argue this is not low priority as it's pretty fundamental ALA functionality to be able to browse and sort records, and it's highly visible to users.

**Comment by nickdos** [comment]
Yes, agree with priority comment. I'll take a look at it.
