### ISSUE TITLE
Flag an issue: add link to support article (documentation)

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#378]
Based on support tickets and Twitter posts by users, there is an expectation that ALA can review and correct flagged issues, ourselves. Thus when issues remain uncorrected for months & years, it can seem like ALA is at fault. 

We currently provide no information about the process of dealing with user annotations:

![image](https://user-images.githubusercontent.com/532845/92419019-25dc0080-f1ae-11ea-8f21-c482467d065f.png)

- [ ] Provide a short sentence explaining that suggested corrections need to be corrected at the source institution and ALA cannot guarantee the institution will take action. 

- [ ] Add a link to a support article that provides more information about the process.

**Comment by timhicks-ala** [comment]
I have the start of an article drafted on the topic - it will require some (planned) work in a testing environment to fully document the process.

**Comment by alexhuang091** [comment]
hi @timhicks-ala, is the article done so I can start to work on this issue.

**Comment by adam-collins** [comment]
Adding a link. Feedback on appearance welcome. It looks like this 
<img width="607" alt="Screenshot 2024-01-30 at 10 42 49 am" src="https://github.com/AtlasOfLivingAustralia/biocache-hubs/assets/8031500/bcab4bba-805a-43d2-84c5-0c354add4a4c">

**Comment by timhicks-ala** [comment]
So the "?" links to the article? Looks fine to me if so.
