### ISSUE TITLE
Records from DigiVol don't show "Flag an issue" button

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#379]
E.g. https://biocache.ala.org.au/occurrences/92a48434-98b7-4d80-8371-fb612ac6950f

It appears there is special code to detect "VP" records and add custom content to the left hand column (`This record was transcribed from the label by an online volunteer. It has not yet been validated by the owner institution Biodiversity Volunteer Portal.`).

- [x] Fix code so the "Flag an issue" button is displayed
- [x] ~Add~ Change text to "DigiVol" to any references to "VP" (branding changed about 4 years ago)
- [x] The button called `See draft in Biodiversity Volunteer Portal` is broken - ~investigate and fix~ (~or~ remove it completely) 
- [x] Occurrence Id field is not linked, despite showing a URL - it should be so test that and fix too

**Comment by Rita-C** [comment]
@nickdos Occurrence Id link was removed by https://github.com/AtlasOfLivingAustralia/biocache-hubs/issues/6

**Comment by nickdos** [comment]
That was 2014 - requirements change...
https://biocache.ala.org.au/occurrences/86b5a094-c78f-4e1b-beab-5d773d09d3a7 shows it as being a link but
https://biocache.ala.org.au/occurrences/92a48434-98b7-4d80-8371-fb612ac6950f is not. Maybe there is something in the link generating taglib that is failing (html sanitising code).

**Comment by Rita-C** [comment]
`occurrenceID` of https://biocache.ala.org.au/occurrences/86b5a094-c78f-4e1b-beab-5d773d09d3a7  is a link 
`occurrenceID`of https://biocache.ala.org.au/occurrences/92a48434-98b7-4d80-8371-fb612ac6950f  is a text
The rendering page displays whatever the value it received.

**Comment by nickdos** [comment]
raw vs processed table shows as being just a string but maybe controller code is doing some markup???
