### ISSUE TITLE
Do not cache failed logger reason requests

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-hubs#380]
Failed logger reason requests appear to be cached currently, causing download requests to not be able to be triggered because reasons cannot be selected in the UI.

We should be keeping whatever logger reason values are in the cache previously rather than caching failed requests to prevent outages caused by intermittent request failures to logger-service:

https://github.com/AtlasOfLivingAustralia/biocache-hubs/blob/159be29ea6f306aa5f095215f61497f17c51398e/grails-app/services/au/org/ala/biocache/hubs/WebServicesService.groovy#L297-L302

**Comment by alexhuang091** [comment]
@nickdos this function will only be used when `useDownloadPlugin=false`

**Comment by nickdos** [comment]
@alexhuang091 that service populates the drop-down options on the "download reasons" form on prod (which uses the download plugin)

![image](https://user-images.githubusercontent.com/532845/129312192-30753c09-7dd0-44ad-bd2c-1a87c433504b.png)

So needed for ANY download implementation.

**Comment by adam-collins** [comment]
Fixed in downloads plugin https://github.com/AtlasOfLivingAustralia/downloads-plugin/pull/102
