### ISSUE TITLE
Remove "User Assertion Status" line on user annotations

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#383]
Related to #382. See screenshot:

![image](https://user-images.githubusercontent.com/532845/96390773-e6b7bb00-1201-11eb-8597-d40bd8d12d00.png)

- [x] The first line of the table ("User Assertion Status") should be removed, as it is showing the status for only a single assertion but multiple assertions can be added to the table. This is doesn't make sense to summarise all assertions, which may be unrelated.
~- [ ] The status code is shown under any replies but we may need to show the status for each "pending" annotations.~

**Comment by nickdos** [comment]
Code review requested https://upsource.ala.org.au/biocache-hubs/review/BH-CR-54

**Comment by Rita-C** [comment]
Testing - 
"User Assertion Status" line is removed;

The status code is shown under any replies but we may need to show the status for each "pending" annotations.
@alexhuang091 , can you provide some test cases, e.g. what should be displayed or not displayed when annotation going through different status?

**Comment by Rita-C** [comment]
Passed test as the second point was removed.
