### ISSUE TITLE
Minor i18n bugs

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#384]
Bugs picked up by @vjrj for his PR #308 

- Reconfiguration of baseNames in order to include biocache-plugin and download-plugin external resources
- Added some facet messages to allow their translation
- Minor typo: basicOfRecord vs basisOfRecord

Adding issue to track on board.

**Comment by nickdos** [comment]
Code QA'ed - still needs testing.

**Comment by Rita-C** [comment]
Tested on https://biocache-test.ala.org.au/occurrences/search?fq=abcd_identification_qualifier:*
![image (3)](https://user-images.githubusercontent.com/29115246/105112818-dc1a0400-5b17-11eb-8c85-25e5af5990fa.png)
