### ISSUE TITLE
Ability to set query based alert when no records found

### ISSUE THREAD

**Issue by Rita-C** [AtlasOfLivingAustralia/biocache-hubs#386]
@m-hope commented on [Fri Oct 30 2020](https://github.com/AtlasOfLivingAustralia/alerts/issues/66)

When sorting out a workaround for issue https://github.com/AtlasOfLivingAustralia/alerts/issues/65, I found that if you are trying to set a query based alert where the query currently does not return any records, you don't get the "alert" button to set the query.  I don't know if there is an alternative way to do this, but it would be good to either still have the alert button on the "no records found" page, or let the user know what the alternate mechanism is if there is one.

Note: I did try attaching "#alertNewRecords" to the query (which seems to be how the alert button works), but it did not seem to do anything and the query/alert did not appear in the manage alerts page.

---

@Rita-C commented on [Mon Nov 23 2020](https://github.com/AtlasOfLivingAustralia/alerts/issues/66#issuecomment-731903755)

Hi @m-hope,
The alert buttons are generated in `biocache-hubs`, I'm moving this ticket to `biocache-hubs`.

**Comment by nickdos** [comment]
Tested with a txt query for "permamixer" (expected 0 records) - works as expected.

![image](https://user-images.githubusercontent.com/532845/104862546-89114700-5987-11eb-927a-2268854f9f34.png)
