### ISSUE TITLE
EYA map attribution overlaps for Google base layers

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#389]
Reported by a @timhicks-ala. 

When view the explore your area page (layer to Road or Satellite), the map attribution text (bottom-right corner of map) added by Leaflet is overlpaping the rendered attribution for Google base layers (default layer is OK being OSM). See screenshot:

![image](https://user-images.githubusercontent.com/532845/100294956-65abca80-2fdc-11eb-8112-c8fea6caf3c8.png)

Fix so it moves up slightly, similar to the maps on other pages (search results).

**Comment by nickdos** [comment]
No code added, skipping code review step.

**Comment by nickdos** [comment]
Fix on local:

![image](https://user-images.githubusercontent.com/532845/100295172-12864780-2fdd-11eb-9001-f35bfb847cc7.png)

**Comment by Rita-C** [comment]
Hi @nickdos , the overlapping does not occur on prod, see image here, it uses `open street` map.
![Screen Shot 2021-01-18 at 11 19 32 am](https://user-images.githubusercontent.com/29115246/104860362-49def800-597f-11eb-8cd4-d462efce2b6f.png)

**Comment by timhicks-ala** [comment]
@Rita-C , you'll see it happen in prod if you change the layer to Road or Satellite rather than Minimal: 
![road](https://user-images.githubusercontent.com/57081387/104860447-cb368a80-597f-11eb-9d3f-a469aa8e9b67.png)

**Comment by Rita-C** [comment]
Thanks @timhicks-ala , I've updated the ticket to reflect your comment above.

Tested and passed on `https://biocache-test.ala.org.au/explore/your-area`

**Comment by Rita-C** [comment]
Road view still overlaps, reopen the issue.

**Comment by nickdos** [comment]
**Road** view only overlaps if you change the view to **satellite** first, then change it to **road**. If you go from **minimal** to **road**, it displays it fine.

**Comment by alexhuang091** [comment]
Haven't figured out why. The direct cause is `onAdd` and `onRemove` are called when changing from satellite to road. It causes bottom-margin to be 0

![1](https://user-images.githubusercontent.com/61677987/137677274-3a956e3b-050e-4217-af7e-8300cf5aee10.jpg)

**Comment by nickdos** [comment]
Wondering if we mark this as won't fix - minor UI issue that requires a modification to vendor code, which is not desirable.

**Comment by nickdos** [comment]
Requires Leaflet core code change - such a minor issue, decided to not fix for now. Reopen if really needed.
