### ISSUE TITLE
Download documentation - needs an edit

### ISSUE THREAD

**Issue by mbohun** [AtlasOfLivingAustralia/biocache-hubs#39]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=230
*date:* Mon Aug 12 03:24:21 2013
*author:* johntan...@gmail.com
 ---

Records downloaded through the BioCache come with a README file which contains a link to information about the Download Fields:
[https://docs.google.com/spreadsheet/ccc?key=0AjNtzhUIIHeNdHhtcFVSM09qZ3c3N3ItUnBBc09TbHc#gid=0](https://docs.google.com/spreadsheet/ccc?key=0AjNtzhUIIHeNdHhtcFVSM09qZ3c3N3ItUnBBc09TbHc#gid=0)

Some of the fields have explanations that are not helpful. For example:
Coordinate Precision	The precision of the coordinates
Coordinate Uncertainty In Meters	Distance from the occurrence

Although there is a link to the Darwin Core Terms for the fields, the description could be more helpful for a person needing to understand what they have downloaded.

Other editing requirements
ACRONYMS need explaining eg GUID, IBRA, IMCRA
Spelling 
Links to further assistance
Some issue flags missing definitions

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/bie-service#2
