### ISSUE TITLE
Fix test failures for data resource UID checks

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-hubs#390]
Three tests related to issue #328 are failing intermittently on Travis and locally with the following messages:

```
au.org.ala.biocache.hubs.OccurrenceTagLibSpec > test Biocollect sightings user link via getLinkForUserId() tag FAILED

    org.spockframework.runtime.SpockComparisonFailure at OccurrenceTagLibSpec.groovy:143

au.org.ala.biocache.hubs.OccurrenceTagLibSpec > test iNaturalist user page link via getLinkForUserId() tag FAILED

    org.spockframework.runtime.SpockComparisonFailure at OccurrenceTagLibSpec.groovy:154

au.org.ala.biocache.hubs.OccurrenceTagLibSpec > test Flickr user page link via getLinkForUserId() tag FAILED

    org.spockframework.runtime.SpockComparisonFailure at OccurrenceTagLibSpec.groovy:162
```

**Comment by nickdos** [comment]
@ansell - Can you code review the [commit above](https://github.com/AtlasOfLivingAustralia/biocache-hubs/commit/bc120bf1be10e174d3d0d2e1ead45aca13fcdffa), please?

**Comment by nickdos** [comment]
I'm wondering if a better solution, is to move this class into the integration tests directory and wire it as an integration test, so it can read the config from the plgin.groovy file and thus avoid duplicating values? Argument against that is, we will know if they are changed, as the tests will fail and we can fix them easily...

**Comment by ansell** [comment]
The build is working for me and Travis again now. I am not familiar with any Grails conventions to know what the impacts are of different choices.

Personally, I would close this as fixed rather than putting it into the release+CAB issue list because it isn't related to a bug or enhancement in the final artifact. I just needed a marker issue for fixing the build this morning. However, up to you what you want to do with it.

**Comment by nickdos** [comment]
Yeah, good point - will do.
