### ISSUE TITLE
Add button to pages for API copy & paste into R, Python, Curl, etc.

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#392]
Search pages - add a button (next to download button ?) called `API access` or similar, that shows a popup div with some common API access sections with copy buttons to copy the generated code into clipboard.

- ALA4R code snippet
- curl code snippet
- Python GET (no idea needs investigating)

As discussed today - @peggynewman @patkyn @sadeghim (and @matilda2812)

Note: as an initial first pass, it was decided to simplify this issue and just allow the JSON URLs to be copied to clipboard.

Any further enhancements should be specified in a new issue.

**Comment by alexhuang091** [comment]
Hi @nickdos, it will be like this, any suggestion?

<img width="674" alt="Screen Shot 2021-08-25 at 4 58 58 pm" src="https://user-images.githubusercontent.com/61677987/130741749-3d68138f-fb12-429c-866d-ca3e40b1bcd1.png">

**Comment by nickdos** [comment]
I'm wondering if it would be simpler to just have a button that showed the JSON URL... more like

```
JSON web service URL [ input ]  [Copy]
```

Button could say `JSON API`. DOn't make it orange like Download button, as its not as important. Keep it a standard white button.

**Comment by nielsklazenga** [comment]
Just noting that JSON API is a specification (https://jsonapi.org/) and that the ALA API does not follow this specification, so, if at all possible, it might be better to find another label for such a button.

**Comment by nickdos** [comment]
Goop point @nielsklazenga/

How about button just shows `{ json }`?

**Comment by nickdos** [comment]
Just looking at this again and I think the button should be labelled as "Copy URL" (instead of `{ JSON }`).

Might be worth adding a second button (as [button group](https://getbootstrap.com/docs/3.4/components/#btn-groups)) with label "Open URL" with tooltip "Open URL in new window". ?

I think the title text should be changed and include a link to API docs. Change from:

> Copy the JSON web service URL

to

>  ALA REST API ([documentation](https://api.ala.org.au/))

**Comment by Rita-C** [comment]
> Just looking at this again and I think the button should be labelled as "Copy URL" (instead of `{ JSON }`).
> 
> Might be worth adding a second button (as [button group](https://getbootstrap.com/docs/3.4/components/#btn-groups)) with label "Open URL" with tooltip "Open URL in new window". ?
> 
> I think the title text should be changed and include a link to API docs. Change from:
> 
> > Copy the JSON web service URL
> 
> to
> 
> > ALA REST API ([documentation](https://api.ala.org.au/))

The popup text is not ALA REST API (documentation)
![Screen Shot 2022-02-16 at 4 00 28 pm](https://user-images.githubusercontent.com/29115246/154199460-1e39f0b6-4521-471c-89d1-e08e7806e4c6.png)

**Comment by nickdos** [comment]
It's fine as is. Was only a suggestion, not set in stone.

**Comment by Rita-C** [comment]
Code reviewed and tested.
