### ISSUE TITLE
Alerts for biocache searches with long queries fail.

### ISSUE THREAD

**Issue by Rita-C** [AtlasOfLivingAustralia/biocache-hubs#394]
@nickdos commented on [Thu Sep 13 2018](https://github.com/AtlasOfLivingAustralia/alerts/issues/39)

See https://support.ehelp.edu.au/helpdesk/tickets/23079

User was trying to get an alert for a species list (295 taxa) via the records link on the list page. See https://lists.ala.org.au/speciesListItem/list/dr8953. The records alerts resulted in an error "Request URI too long". Shortening the list to 50 taxa (https://lists.ala.org.au/speciesListItem/list/dr8954) seemed to work, as the alerts button forwarded onto "my alerts" page (expected behaviour) but the alert was not added to the list of custom alerts. So it appears to simply silently fail in this case.

---

@ansell commented on [Thu Sep 20 2018](https://github.com/AtlasOfLivingAustralia/alerts/issues/39#issuecomment-422980262)

Creating a QID and using it for the query is possibly a workaround (and is basically free in terms of storage, so you don't have to worry if you need to create a new one when they add a new species)

---

@Rita-C commented on [Tue Dec 01 2020](https://github.com/AtlasOfLivingAustralia/alerts/issues/39#issuecomment-736130294)

biocache-hub generates URL to create the alert, the `queryDisplayName` is too long in this case:
[JS code](https://github.com/AtlasOfLivingAustralia/biocache-hubs/blob/68d60a3b80d1c55f0c5a90727445af63be5339af/grails-app/assets/javascripts/search.js#L490)
suggest to truncate `queryDisplayName` in biocache-hub.

**Comment by nickdos** [comment]
@Rita-C the original user report had the error: `Request URI too long`, which suggests the URL itself might also be a problem. A possible workaround for this, is to convert the URL to the shortened form via a POST to get a `qid` reference instead, as @ansell suggested above. So I have a feeling both changes might be necessary (shortening title and using `qid`). Note the `qid` fix will require changes in biocache-hubs, so maybe create a related issue there?

**Comment by Rita-C** [comment]
@nickdos , I recreated this error by:
1. go to ` https://lists.ala.org.au/speciesListItem/list/dr8953`
2. click "view occurrence records" -> biocache page show as `https://biocache.ala.org.au/occurrences/search?q=qid%3A1607057431661`, **note** there is a `qid` here.

I think the `Request URI too long` was caused by the `query` is too long hence the URL for creating alerts is too long as shown at this [line](https://github.com/AtlasOfLivingAustralia/biocache-hubs/blob/68d60a3b80d1c55f0c5a90727445af63be5339af/grails-app/assets/javascripts/search.js#L490) - this is how the alerts URL is created.
```
url += "queryDisplayName="+encodeURIComponent(query);
```
`queryDisplayName` here is used as the alert display name, not used to make ws call, `qid` is passed to alerts to make ws call.

**Comment by nickdos** [comment]
No, I think both PA and I were confused and assumed it was using a long expanded query and not a `qid` (it used to be like that at one stage). I see now the problem was correctly diagnosed by you and was due to the title param.

**Comment by Rita-C** [comment]
To be tested once it's deployed.

**Comment by nickdos** [comment]
Confirmed it works on test site.
