### ISSUE TITLE
Add processed datum to download formats

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#396]
This is really a config fix (probably) but putting here anyway.

Download formats "legacy" and "DwC" should include the processed datum field. See support ticket https://support.ehelp.edu.au/a/tickets/97061.

The download file contains only a single column for datum called `Geodetic datum - processed` with a value of `AGD66`. Looking at the r[ecord view](https://biocache-dq-beta.ala.org.au/occurrences/8ca3791e-6628-4dc2-9ac5-f4b1b4fd3c7c), this is in fact the "Verbatim SRS" field and not the supplied datum field (which has a value of `GDA94`) and a processed version with a value `EPSG:4326`. 

Fix is to add the processed verbatim value (`datum`) to the download file, via ansible config. Check to see whether it already contains `raw_datum ` or `verbatim_srs `. See https://biocache.ala.org.au/fields?filter=srs%7Cdatum.

**Comment by ansell** [comment]
It may be possible to combine this with https://github.com/AtlasOfLivingAustralia/ansible-inventories/issues/18

**Comment by Rita-C** [comment]
@adam-collins , can you please review the changes? see above commits.

**Comment by nickdos** [comment]
Code is fine, move to QA.
