### ISSUE TITLE
Add "drop pin here" option to Explore your area

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/biocache-hubs#397]
Suggested in helpdesk ticket 97165 - a user finding records in a specific area has suggested adding a feature allowing you to drop the blue pin on the map independently of dragging/dropping it from another location or finding a new location.

I think as a feature request it has merit as other applications (eg. Google Maps) have this feature, and users may be used to "zooming/panning to a particular location, then asking what records are there, rather than the (subtly inverted) user story of "display records, then move to the right location".

In terms of implementation this could be an extra button on the map underneath "Use my location" that drops the pin in the centre of wherever the map is currently panned to.

**Comment by adam-collins** [comment]
You can drag the pin around. I think that is intuitive enough.
