### ISSUE TITLE
Support for a processed value for coordinatePrecision

### ISSUE THREAD

**Issue by mbohun** [AtlasOfLivingAustralia/biocache-hubs#40]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=233
*date:* Mon Aug 12 23:25:33 2013
*author:* natasha....@csiro.au
 ---

AT the moment the processors do not store a a processed value for the coordinate precision. This is causing all coordinatePrecision to be reported as "Unknown". 

I suggest as an interim measure we change the occurrence page to display the raw value instead of processed.:

<alatag:occurrenceTableRow annotate="false" section="geospatial" fieldCode="coordinatePrecision" fieldName="Coordinate precision">
                <c:set target="${fieldsMap}" property="coordinatePrecision" value="true" />
                <c:if test="${not empty record.raw.location.decimalLatitude || not empty record.raw.location.decimalLongitude}">
                    ${not empty record.processed.location.coordinatePrecision ? record.processed.location.coordinatePrecision : 'Unknown'}
                </c:if>
            </alatag:occurrenceTableRow>

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/biocache-store#28
