### ISSUE TITLE
possible issues found in biocache-hubs 3.0.0 test

### ISSUE THREAD

**Issue by alexhuang091** [AtlasOfLivingAustralia/biocache-hubs#406]
- In spatial search, when draw a rectangle or circle, it's easy to see below errors

<img width="599" alt="截屏2021-01-22 上午9 17 45" src="https://user-images.githubusercontent.com/61677987/105419423-caa93700-5c92-11eb-849b-e5705fc33387.png">
<img width="888" alt="截屏2021-01-21 下午2 11 48" src="https://user-images.githubusercontent.com/61677987/105419432-cda42780-5c92-11eb-9988-35eed1c36b75.png">

- When search url is https://biocache-test.ala.org.au/occurrences/search?taxa=#tab_chartsView
 
<img width="885" alt="截屏2021-01-21 下午3 36 17" src="https://user-images.githubusercontent.com/61677987/105419520-f75d4e80-5c92-11eb-9026-7041136610be.png">

-- When all returned records are filtered out by data quality filters, you can see. I think just a single 'no record can be displayed' will be better?
<img width="1567" alt="截屏2021-01-21 下午5 09 49" src="https://user-images.githubusercontent.com/61677987/105419721-3f7c7100-5c93-11eb-992c-a595df9fcdea.png">

**Comment by adam-collins** [comment]
Drawing a circle did not give me an error and I do not have a problem with the other 2 issues.
