### ISSUE TITLE
Support shape file friendly spreadsheet export

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#41]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=244
*date:* Sun Aug 18 18:42:16 2013
*author:* moyesyside
 ---

Support shape file friendly spreadsheet export

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/biocache-service#19
