### ISSUE TITLE
"Rights holder" for image reads from record instead of image data when viewing a record

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/biocache-hubs#410]
For example, this record: https://biocache.ala.org.au/occurrences/6784427d-732f-4004-b917-535faabea38d

The rightsholder for the record is "Museums Victoria", and the same value shows on the left under each image:

![image](https://user-images.githubusercontent.com/57081387/105920342-518f5280-608b-11eb-9e0e-7ccd56092259.png)

![image](https://user-images.githubusercontent.com/57081387/105920379-5f44d800-608b-11eb-98c2-ab9bcc6178d4.png)

However, when viewing the details for that image: https://images.ala.org.au/image/details?imageId=0bc6afc3-e037-44c1-9664-70499060d590

The rightsholder is shown on that page to be Parks Australia:

![image](https://user-images.githubusercontent.com/57081387/105920493-974c1b00-608b-11eb-8550-2df69b7261bf.png)

So the display of rightsholder on an occurrence record's page for an image may be reading the value from the record rather than image metadata. The License shown on a record page's image thumbnail is correct (in this case it shows CC-BY which matches the image), it's just the Rightsholder name that is wrong.

**Comment by nickdos** [comment]
Local fix:

![image](https://user-images.githubusercontent.com/532845/106230534-d45b0d80-6243-11eb-81eb-16fac92eefce.png)

**Comment by Rita-C** [comment]
Code reviewed, change is not available on [https://biocache-test.ala.org.au/occurrences/6784427d-732f-4004-b917-535faabea38d] yet
