### ISSUE TITLE
Explore your area: default sort of taxa by count

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#411]
Change the default sort order of taxa to be by record count (currently it is ny name).

Consider swapping focus to common names

- [x] Default to sort by number of records
- [x] Split names to Common Name and Scientific name, Common Name displayed first.

**Comment by Rita-C** [comment]
![Screen Shot 2021-02-18 at 12 59 08 pm](https://user-images.githubusercontent.com/29115246/108298614-5e6a1680-71f1-11eb-902b-257a64b0b53c.png)

**Comment by Rita-C** [comment]
> Move ticket back to investigate "isn't displaying links to species pages and records when a species name is clicked. Is this expected?"

@nickdos fixed above issue at commit [7afac23](https://github.com/AtlasOfLivingAustralia/biocache-hubs/commit/7afac23a51ca8eef6c354028bc63917fb96f1bbb), please review.

**Comment by nickdos** [comment]
Code reviewed as requested - all good
