### ISSUE TITLE
Add NSW Bionet to Advanced Search dropdown list 

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/biocache-hubs#412]
On the Advanced Search https://biocache.ala.org.au/search#tab_advanceSearch
there is a dropdown labelled "Institution or Collection" providing a whole list of State and Territory datasets, museums, herbaria, conservation agencies etc.
Can NSW BioNet included in this list? dr368? dp34?

**Comment by adam-collins** [comment]
This is currently available in the Data Resource search box
