### ISSUE TITLE
show number of records in correct format

### ISSUE THREAD

**Issue by alexhuang091** [AtlasOfLivingAustralia/biocache-hubs#415]
when DQ filters are turned OFF on ala-hub (via config) that it still shows the number of results using DQ "syntax" 

`NNNN records returned of 0 for "Foo"` should just be `N records returned for  "foo"`

![image](https://user-images.githubusercontent.com/61677987/108924304-8264a680-768e-11eb-97e1-cdce036df767.png)

**Comment by nickdos** [comment]
Needs to be tested on AVH test site, which is not using DQ filters yet. Moving to QA.
