### ISSUE TITLE
Support map download with google base layer in Biocache

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#42]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=256
*date:* Mon Sep  2 18:34:15 2013
*author:* moyesyside
 ---

Requested by several users.
This is available in spatial portal so we should look to moving this into a common service that can be accessed by all components

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/biocache-service#64
