### ISSUE TITLE
Verify annotation not working

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#428]
There seem to be a few issues with the Verify annotation function.

- [x]  The modal div reports `Record is marked as geospatially suspect, taxonomically suspect` when the only annotation is marked as `other issue`. See screenshot:

![image](https://user-images.githubusercontent.com/532845/111578321-092d1f00-8808-11eb-8a73-9bb26d5438c5.png)

- [x] Also note the user ID for the annotation (`XXX issue flagged by ...`) is empty above but is showing in the next screenshot (reported in a support ticket):

![image](https://user-images.githubusercontent.com/532845/111578826-f6671a00-8808-11eb-8a82-c0119ee41959.png)

When viewing the same record I don't see the user name -  https://biocache.ala.org.au/occurrences/72d3e802-5d4a-4fdd-a1b8-304868fd2413#userAnnotationsDiv nor do I see the verification reply, shown in the screenshot above.

- [x] Clicking the `Confirm` button does nothing. There are no JS errors but it has no effect at all. Cancel button does work.

Another user reported when they tried it, the `Confirm` button did work but they then got a long error popup. See:

![image](https://user-images.githubusercontent.com/532845/111578490-5a3d1300-8808-11eb-9f3d-1716d796fa95.png)

**Comment by alexhuang091** [comment]
Hi Nick, do you have the link to the record in first issue, thanks ?

**Comment by nickdos** [comment]
https://biocache.ala.org.au/occurrences/4db7b1b8-ad78-42c5-a6ec-bae270d3a0f2

**Comment by alexhuang091** [comment]
Hi Nick, for the second issue. Biocache-hubs calls `biocache-service/ws/occurrence/uid/assertions` for all assertions and it sometimes get this (https://biocache.ala.org.au/ws/occurrences/3fb03272-09f6-48df-8bc5-469ffdf89d32/assertions). This wrong data is the reason UI breaks.

The email field looks wrong, but more importantly the `uuid_field` is wrong
<img width="2262" alt="截屏2021-03-19 下午3 27 53" src="https://user-images.githubusercontent.com/61677987/111734212-c2096180-88cd-11eb-92c8-7e9e593dace4.png">


However, when I debug locally with local biocache-hubs and biocache-services (this connects to production database), I can't reproduce this issue. The assertions returned are always correct so UI always good.

so 
- it has something to do with load balancer, at lease there's 1 machine returning correct result and the other not.
- where the wrong result comes

**Comment by nickdos** [comment]
Thanks @alexhuang091 - I'm seeing the same output just now. I'll create an issue in biocache-service for this.

**Comment by nickdos** [comment]
Closing as we determined that one of the load balancers was causing this issue.
