### ISSUE TITLE
Speices list "View occurrence record" broken for dr487

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#43]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=258
*date:* Wed Sep  4 21:08:11 2013
*author:* moyesyside
 ---

[http://lists.ala.org.au/speciesListItem/listAuth/dr487](http://lists.ala.org.au/speciesListItem/listAuth/dr487)

click "View occurrence record" 

Get

Error 500: Internal Server Error

**Comment by nickdos** [comment]
Prod list tool is now throwing a different Grails error - moving to list tool issues.

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/specieslist-webapp#22
