### ISSUE TITLE
Associated record filter shows "D" and "R" labels - not clear to users

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#434]
E.g. https://biocache.ala.org.au/occurrences/search?q=lsid%3Aurn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3Ab1d9bf29-648f-47e6-8544-2c2fbdf632b1&disableAllQualityFilters=true&fq=taxon_name%3A%22Macropus+giganteus%22&qualityProfile=ALA#tab_mapView

![image](https://user-images.githubusercontent.com/532845/113796614-fcf70a80-9792-11eb-9aa5-0a86dd6cec74.png)

- [x] Fix i18n labels to show an appropriate label - e.g. `Representative record` and `Duplicate record` or what-ever is appropriate.

This is a regression bug - it used to show those labels. ~I wonder if the "default" labels are not [coming across from biocache-service](https://github.com/AtlasOfLivingAustralia/biocache-hubs/blob/develop/grails-app/init/biocache/hubs/BootStrap.groovy#L15)?~ Looks like there is no `facet.D` value there either.

**Comment by nickdos** [comment]
@alexhuang091 could you code review the[ commit for this issue](https://github.com/AtlasOfLivingAustralia/biocache-hubs/commit/03908aeb7edf6a32c25e114b122ac38b29bf11ae), please?

**Comment by alexhuang091** [comment]
> @alexhuang091 could you code review the[ commit for this issue](https://github.com/AtlasOfLivingAustralia/biocache-hubs/commit/03908aeb7edf6a32c25e114b122ac38b29bf11ae), please?

Thanks Nick, I'll do it

**Comment by alexhuang091** [comment]
Hi Nick, why I didn't see the `D` and `R` with the link you provided?

<img width="213" alt="截屏2021-04-07 上午10 39 07" src="https://user-images.githubusercontent.com/61677987/113794302-96232280-978d-11eb-95a0-2202875ca39f.png">

**Comment by nickdos** [comment]
Wrong facet - its under "Assertions"

**Comment by alexhuang091** [comment]
Hi Nick it's all good. I'll move it to QA.
