### ISSUE TITLE
fq disappeared after select and search in an area

### ISSUE THREAD

**Issue by alexhuang091** [AtlasOfLivingAustralia/biocache-hubs#437]
Steps to reproduce:

- https://biocache.ala.org.au/occurrences/search?q=data_resource_uid%3Adr2244&qualityProfile=ALA&fq=species_group%3A%22Fishes%22&fq=state%3A%22New+South+Wales%22#tab_mapView
- draw a square anywhere on the map with records
- click "Search for records in this area"
- You will see it's forgotten that I searched within NSW, and ignores the spatial area, but remembers I wanted data from a single data resource

--- issue analysis ---
The generated url in this case is https://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr2244&qualityProfile=ALA&fq[]=species_group:"Fishes"&fq[]=state:"New South Wales"&qc=&wkt=MULTIPOLYGON(((147.0690916478634+-34.29907681967288,147.0690916478634 -35.63150418320232,149.1564939916134 -35.63150418320232,149.1564939916134 -34.29907681967288,147.0690916478634 -34.29907681967288)))#tab_mapView

You can see there's `&fq[]=species_group:"Fishes"&fq[]=state:"New South Wales"` which is incorrect.

**Comment by nickdos** [comment]
Tim noticed a similar bug today on prod - draw a polygon and the counts never appear. Fix is to remove the `[]` appearing in `fq` param, as you said.

**Comment by alexhuang091** [comment]
Yes, my fix is based on the URL Tim provided in biocache channel at 12:12PM
