### ISSUE TITLE
Prevent apiKey being exposed in `flash.message` output

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#443]
Also fixes issue where we are using `raw()` output which is a security risk.

**Comment by nickdos** [comment]
@alexhuang091 could you please code review [this change](https://github.com/AtlasOfLivingAustralia/biocache-hubs/commit/18672aeb31e0f8823d54f9e11019908d680011eb)?

**Comment by alexhuang091** [comment]
> @alexhuang091 could you please code review [this change](https://github.com/AtlasOfLivingAustralia/biocache-hubs/commit/18672aeb31e0f8823d54f9e11019908d680011eb)?

Hi Nick, I'll review it later today.

**Comment by alexhuang091** [comment]
Hi Nick, it's all good.
