### ISSUE TITLE
Facet download broken

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#450]
Facet download from the link highlighted seems to be broken in production (at least for scientificName downloads)

<img width="1248" alt="Screen Shot 2021-05-19 at 9 15 26 pm" src="https://user-images.githubusercontent.com/444897/118878858-f27a7580-b8e7-11eb-9440-399f60deca60.png">

cc @nickdos

**Comment by alexhuang091** [comment]
It's not broken. It just takes long time to finish. 

The downloaded csv has 198k rows.

**Comment by alexhuang091** [comment]
facets are donwloaded in batch (batchsize = 1000)

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/a7712c1d384c5d0b8bda75d2d7e6c9cdda7e6e8a/src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java#L639

```
protected static final Integer FACET_PAGE_SIZE = 1000;

offset += FACET_PAGE_SIZE;
//get the next values
solrQuery.set("facet.offset", Integer.toString(offset));
```

If we change it to a larger value like 10000, download will be much faster?

Maybe make it a configurable value?

**Comment by alexhuang091** [comment]
@nickdos please have a look, it's still an issue on prod

**Comment by nickdos** [comment]
I'm OK with the current performance

All ACT - scienftificName facet (13k lines) and it took ~3 seconds to run.
All NSW - scienftificName facet (63k lines) and it took 20 seconds to run.

If we increase the pageSize, how much faster will it run?

**Comment by alexhuang091** [comment]
> I'm OK with the current performance
> 
> All ACT - scienftificName facet (13k lines) and it took ~3 seconds to run.
> All NSW - scienftificName facet (63k lines) and it took 20 seconds to run.
> 
> If we increase the pageSize, how much faster will it run?

Hi Nick, if you search for all records and download all scienftificName  facet, it will timeout.

**Comment by nickdos** [comment]
Let's wait for @djtfmartin  to advise (he's away). 

@djtfmartin we don't allow downloading of all records, so do we need to support all records - scientificName facets as well? NSW works in 20 seconds but all records times out.

**Comment by adam-collins** [comment]
For an all records search today I downloaded the 197659 scientific names in a second or so. For NSW only it was the same response time, very quick.
