### ISSUE TITLE
Improve usability of facet value listing on occurrences/search page

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/biocache-hubs#455]
The left hand side of the occurrences/search page is not usable for finding a facet where there are many unique values. There is a facet service that may be of use in biocache-service that does a 'begins with' filter on facets, and paging, used by spatial-hub.

Reproduce issue
1. open link https://biocache-test.ala.org.au/occurrences/search?q=data_provider_uid:dp5183
2. click 'customize filters', select 'genus', click 'update'
on the left expand the 'taxon' section
3. click 'choose more...' for the 'genus'
4. scroll down and notice that for every 100 genus values the next 100 are fetched. In alphabetical order.
5. given there are >5000 genus for this data provider this means scrolling to the end, waiting for the next 100 genus to load, then repeating for a total of 50+ times.
6. Fix the sortable column convention. It is not obvious that the columns are sortable. Maybe add arrows?

**Comment by peggynewman** [comment]
The Museum Victoria feedback suggests that the scientificName facet should be ordered alphabetically as it was in the old system. While there is a UI thingy to do this (ie click on 'scientificName' title) it's not obvious. I think this is a reasonable request.
