### ISSUE TITLE
include indication of annotations in downloads

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#46]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=271
*date:* Wed Oct  2 21:36:30 2013
*author:* moyesyside
 ---

Additional download fields to indicate the presence of user provided annotations.

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/biocache-service#20
