### ISSUE TITLE
Fix layout for filters - Occurrence search results page

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/biocache-hubs#461]
When Data Profiles section is expanded the filters on the LHS move down leaving a noticeable gap. See screenshot

![image](https://user-images.githubusercontent.com/8326394/125559717-649a50cf-aeec-49b7-9b18-c7a384fba314.png)

Layout of page needs to be redesigned using two columns so main content on the right does not affect LHS elements.

This is also a good opportunity to notice that filters are completely hidden in mobile view so that could be addressed too.
![Screen Shot 2021-07-14 at 2 17 51 pm](https://user-images.githubusercontent.com/8326394/125560494-785ebff7-28b5-4058-81b6-0c2cc45fa499.png)

**Comment by alexhuang091** [comment]
Currently, we have 2 divs and 2 columns in each div.

We can consolidate them into 2 columns, the right column has dq-filters on top and result records down under.

![1](https://user-images.githubusercontent.com/61677987/125563733-654acbe0-2587-41bb-b48e-172e39ee7792.jpg)

**Comment by alexhuang091** [comment]
It will be like this, I just need to tune the top margin of the `xxxx records returned of` 
<img width="2526" alt="Screen Shot 2021-07-14 at 5 28 08 pm" src="https://user-images.githubusercontent.com/61677987/125581166-8d397884-2c1a-447d-b144-7929af11932d.png">
