### ISSUE TITLE
hide spatial layer values on record details page

### ISSUE THREAD

**Issue by mbohun** [AtlasOfLivingAustralia/biocache-hubs#47]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=272
*date:* Tue Oct  8 21:36:02 2013
*author:* milo_nic...@hotmail.com
 ---

specifically requested by the seedbanks - to be able to hide all or configure which values are displayed of the spatial layer sampling.  Another potential solution would be to make the lists of values collapsable/expandable

**Comment by nickdos** [comment]
New grails version no longer shows SP layers.
