### ISSUE TITLE
Advanced search: "State, territory or province" is not filtered by country selection

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/biocache-hubs#470]
With pipelines, the "State, territory or province" field in biocache advanced search now includes states from other countries, where previously it was only Australian states and territories. This field is not automatically filtered when selecting country, so it is possible to select (for example) Australia as the country, then Alberta as the state.

It's possible to click the field and type a state's name to search, so there is a work-around, but it's not obvious or ideal.

This occurs both on ALA biocache and AVH advanced search (Australian states do appear at the top of the list on ALA, but not AVH, so there is an additional difference between these two lists somewhere).

The ideal solution would be to filter the contents of the State field depending on the Country selection.

![biocache states](https://user-images.githubusercontent.com/57081387/126739664-a43b96a8-8e5e-44d9-9920-041dec4f9b78.png)

![avh states](https://user-images.githubusercontent.com/57081387/126739667-ed8da0c8-66b9-440c-8d74-d6a873103c13.png)

**Comment by sbearcsiro** [comment]
@nickdos Userdetails and CAS have something like this - the data is currently in a JSON file in userdetails and has some JSON endpoints for CAS to re-use it:

https://github.com/AtlasOfLivingAustralia/userdetails/blob/dev/grails-app/controllers/au/org/ala/userdetails/RegistrationController.groovy#L250

Could be refactored or re-used for this.

**Comment by alexhuang091** [comment]
The 2 APIs we can use are

`https://auth-test.ala.org.au/userdetails/ws/registration/countries.json`
`https://auth-test.ala.org.au/userdetails/ws/registration/states.json?country=xx`

**Comment by alexhuang091** [comment]
There will have 2 issues if to use Simons endpoints:
1. The country list biocache-hubs currently has come from solr, it contains all the values in the `country` field, it has a 'United States'. But the endpoints returns states of 'United States of America'

So in total 250 countries, there are about 50 don't have a exact matching name. For these countries we can show the original states list (all states mixed)

2. When a country is selected, `biocache-hubs` uses the endpoints to get the states of the country and populates the states list so user can only select one from the dropdown list. We just need to make sure the states list is correct and complete.

With these said the country names, states are all configured in external files on userDetails. If there's any change needed, fix will be trivial. 

@nickdos

**Comment by nickdos** [comment]
> 1. The country list biocache-hubs currently has come from solr, it contains all the values in the `country` field, it has a 'United States'. But the endpoints returns states of 'United States of America'

Looking at the advanced search, "Country" drop-down is showing "United States of America", which comes from SOLR...

Where are you seeing "United States"?

**Comment by alexhuang091** [comment]
> Where are you seeing "United States"?

Hi Nick, yes, what's in Solr is '**United States of America**', but to get the states of a nation, the 2 steps are:

https://auth-test.ala.org.au/userdetails/ws/registration/countries.json. -> to get a country's iso code
which returns

```
{
    "isoCode": "US",
    "name": "United States"
},
```

then we use `https://auth-test.ala.org.au/userdetails/ws/registration/states.json?country=US` to get all states in US.


Since Solr returns **United States of America**, we can't get the isoCode, so fail in 1st step.

**Comment by alexhuang091** [comment]
There are about 50 countries from Solr that can't be matched to country names returned from the `ws/registration/countries.json`

**Comment by nickdos** [comment]
OK - you wrote the opposite above, so was confused.

> The country list biocache-hubs currently has come from solr, it contains all the values in the country field, it has a 'United States'.

`It has "United States"` - "it" can only refer to subject of sentence which is SOLR...

**Comment by alexhuang091** [comment]
Hi Nick,

1. I use full country names from solr, that's **United States of America**
2. to get states of a country, you need an isoCode.

So you need to get the isoCode of **United States of America** but I can't. the API only has isoCode of **United States**

----

You mean to use the isoCode in the `country drop down list`? Anyway there must be a mechanism to match full names from solr and from API.

**Comment by nickdos** [comment]
ISO codes are 2 letter codes - "AU", "US", etc. "United States" is NOT a iso code, it's just a label. Looks like the SOLR service is just returning the labels (sad face) but I'm pretty sure it also has the ISO codes stored, so maybe we just need to access them in some way... might need a modification of a service or simply using a different field?

**Comment by alexhuang091** [comment]
Thanks Nick. Let me check it after the sound metadata is done.

**Comment by nickdos** [comment]
https://biocache-ws.ala.org.au/ws/occurrence/facets?q=acacia&facets=countryCode

**Comment by alexhuang091** [comment]
Hi Nick, so currently if you select `country` 'Australia' and `state` Victoria then you go to
`search?q=state:Victoria+AND+country:Australia`

If change it to populate **country code in the dropdown list.** User selects `AU` and `Victoria`, he goes to
 `search?q=state:Victoria+AND+countryCode:AU`, you happy with that?

---

one possible enhancement is: After we get the country code list from Solr, we can map it to a list of full country names (via API) and use it to populate the country list. But since full country names from API do not match names in Solr (API uses 'United States' but Solr has 'United States of America') so we have to use country code to query.

So in the dropdown list user see full names from API like 'United States', but when he clicks submit to search he still goes to 
`search?q=state:Victoria+AND+countryCode:AU`

**Comment by nickdos** [comment]
Didn't think about it changing the other country field like that... was hoping it could be used for a mapping between the 2 systems that have labels that don't match up. 

Issue seems to be SOLR - no easy way to map `US` to `United States of America`... I'll have a dig to see if there is another way.

**Comment by alexhuang091** [comment]
Hi Nick, yes you are correct. If can get the mapping from Solr, it will be perfect.

**Comment by nickdos** [comment]
It all works as expected, with the exception of the "United States of America", as described above. Maybe we need to create a separate issue for this but leave it in the backlog for now?

**Comment by alexhuang091** [comment]
> It all works as expected, with the exception of the "United States of America", as described above. Maybe we need to create a separate issue for this but leave it in the backlog for now?

Yes I think so. A separate issue for the "United States of America" and maybe other countries.
