### ISSUE TITLE
Data assertion chart is ineligible

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#475]
Overlapping labels make it impossible to read:

<img width="622" alt="Screen Shot 2021-08-02 at 3 02 51 pm" src="https://user-images.githubusercontent.com/444897/127874131-368ead9f-8990-48ed-ab14-142cb89c2798.png">

**Comment by alexhuang091** [comment]
Hi @djtfmartin `"growToFit": true` can be added to /config/charts.json so it will look like this:


<img width="986" alt="截屏2021-08-05 下午1 30 39" src="https://user-images.githubusercontent.com/61677987/128286604-a3ea6873-7d6f-4d9b-ac8b-1e5759913831.png">
<img width="1007" alt="截屏2021-08-05 下午1 30 47" src="https://user-images.githubusercontent.com/61677987/128286613-d870fc5f-81fa-4729-adc7-c6328ccc9f2a.png">

**Comment by alexhuang091** [comment]
@nickdos please have a look at this, if you're happy I'll make the code change.

**Comment by nickdos** [comment]
Yep, looks better, so go ahead.

**Comment by alexhuang091** [comment]
ansible config changes made
