### ISSUE TITLE
Improved Biocache download metadata and documentation

### ISSUE THREAD

**Issue by mbohun** [AtlasOfLivingAustralia/biocache-hubs#48]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=277
*date:* Tue Oct 15 21:17:05 2013
*author:* natasha....@csiro.au
 ---

At the moment the metadata for the download is based on the default fields that are included in the download. It would be nice if it could include all the fields that were requested in the download.

Very apparent when users are constructing the download URL using customised field lists.

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/biocache-service#21
