### ISSUE TITLE
Data Quality counts not updating

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#481]
This might be an intermittent bug related to AUTH login state, as I've only seen it happen a few times.

While viewing [this search page](https://biocache.ala.org.au/occurrence/search?q=-country%3A*#tab_mapView), I see the filter counts remain as the spinning icon:

![image](https://user-images.githubusercontent.com/532845/130537179-d62a9c70-d053-4f8a-815f-764dd936c1b8.png)

The following JS error shows in the browser console:

`Access to XMLHttpRequest at 'https://auth.ala.org.au/cas/login?service=https%3A%2F%2Fbiocache.ala.org.au%2Foccurrences%2FdataQualityExcludeCounts%3Fq%3D-country%253A*%26qualityProfile%3DALA' (redirected from 'https://biocache.ala.org.au/occurrences/dataQualityExcludeCounts?q=-country%3A*&qualityProfile=ALA') from origin 'https://biocache.ala.org.au' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
`VM302:1 GET https://auth.ala.org.au/cas/login?service=https%3A%2F%2Fbiocache.ala.org.au%2Foccurrences%2FdataQualityExcludeCounts%3Fq%3D-country%253A*%26qualityProfile%3DALA net::ERR_FAILED`

**Comment by alexhuang091** [comment]
Seems the visit to `https://biocache.ala.org.au/occurrences/dataQualityExcludeCounts?q=-country%3A*&qualityProfile=ALA` <br/><br/>is redirected to `https://auth.ala.org.au/cas/login?service=https://biocache.ala.org.au/occurrences/dataQualityExcludeCounts?q=-country%3A*&qualityProfile=ALA`

but the thing is, how can we go to the `occurrences/dataQualityExcludeCounts` page, it's only supposed to be called from `search.js` when `list.gsp` (the main page) is loaded.

**Comment by nickdos** [comment]
@sbearcsiro - do you have some insight why the JSON call on this page is getting redirected to CAS. I think the page itself is under the `authenticateOnlyIfLoggedInFilterPattern ` filter, so might be related to that. 

When I went back to the tab and clicked reload, it worked just now.

**Comment by adam-collins** [comment]
Seems to be working today.
