### ISSUE TITLE
Record page pipleines fixes

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#484]
Seems record pages are not showing processed values when they differ from raw values (both should be shown):

- [ ] Review all displayed fields and check for raw and processed versions being displayed if different values present
- [ ] Map seems to be showing the coordinates from `raw` but should be `processed`, so is same as results page

This record triggered this issue: https://biocache.ala.org.au/occurrences/ca628d0b-8d9c-4318-9628-be6869297184

Note values in "Original versus Processed" table are not all reflected in main section 

![image](https://user-images.githubusercontent.com/532845/131271925-c1955542-9eab-4c19-bb75-3fe63ad6d5bf.png)

![image](https://user-images.githubusercontent.com/532845/131271941-131e4282-33ea-45fd-b1d4-20e106da62ec.png)

Note decimal latitude and longitude should include a `Supplied as ....` line but don't.

**Comment by javier-molina** [comment]
Alex confirmed this has been tested.
