### ISSUE TITLE
Freeze header on Original vs Processed Dialog

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/biocache-hubs#486]
It will be helpful to have the header frozen when you scroll down the `"Original versus Processed" Comparison Table` in the record view page:

<img width="893" alt="image" src="https://user-images.githubusercontent.com/1578598/131300276-4370005e-6e25-4e49-9b65-3907bca809c3.png">

**Comment by adam-collins** [comment]
I do not see much use for this other than user screenshots. No harm adding it.
