### ISSUE TITLE
biocache-hubs should handle JSON error properly

### ISSUE THREAD

**Issue by alexhuang091** [AtlasOfLivingAustralia/biocache-hubs#489]
Last time we updated `biocache-service` so when no record found, a `404` error is returned instead of `200`

https://github.com/AtlasOfLivingAustralia/biocache-hubs/blob/c8c6304779f6f5356d3d987904ab850d1c11e379/grails-app/services/au/org/ala/biocache/hubs/WebServicesService.groovy#L447-L453

now `biocache-service` has new changes so when there's solr exception or qid invalid exception, status code will be set to proper error code, instead of `200`, so there are lots of possible error code. 

https://github.com/AtlasOfLivingAustralia/biocache-service/pull/685

now the error returned from `biocache-service` looks like this 
```
{
    "message": "No stored query available for qid:1595830161238",
    "errorType": "Unrecognised QID",
    "statusCode": 400
}
```

we now need to parse the whole JSON to get `message` field and display to user, but if we call `JSON.parse(conn.getInputStream(), "UTF-8")` there will be an exception

**Comment by javier-molina** [comment]
Alex confirmed this has been tested.
