### ISSUE TITLE
BioCache faceting fails when choosing refine with multiple values

### ISSUE THREAD

**Issue by mbohun** [AtlasOfLivingAustralia/biocache-hubs#49]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=281
*date:* Tue Nov  5 15:12:32 2013
*author:* john.t...@austmus.gov.au
 ---

In BioCache, the dialog box that opens when wanting to refine a facet gets stuck, sometimes. Sometimes with an empty dialog box, sometimes with a full dialog box, sometimes with a partially filled dialog box. It depends on the browser.

In BioCache
Example using Chrome25 for "Frogs" [http://biocache.ala.org.au/occurrences/search?taxa=frogs#tab_recordsView](http://biocache.ala.org.au/occurrences/search?taxa=frogs#tab_recordsView)
Facet on Scientific name, Country, or Specimen type, - spinning wheel
Facet on Common name, or IBRA, or Collector - no problems

This is a browser-dependent problem:
Google Chrome - spinning wheel - see diagram
FF25 - not apparent in FF25
IE9 - pop-up box incomplete - see diagram

**Comment by nickdos** [comment]
Fixed already
