### ISSUE TITLE
error in 'Draw a circle' in Spatial search

### ISSUE THREAD

**Issue by alexhuang091** [AtlasOfLivingAustralia/biocache-hubs#491]
<img width="2527" alt="Screen Shot 2021-09-07 at 9 07 12 am" src="https://user-images.githubusercontent.com/61677987/132264897-120ae683-f5b6-465e-978f-24a920cef364.png">

**Comment by alexhuang091** [comment]
when the circle is small it's ok. When it's large, the error occurs

**Comment by alexhuang091** [comment]
The problem is the pop up doesn't pops, so the code failed to call
`document.getElementById("speciesCountDiv").innerHTML = speciesCount;`
`document.getElementById("occurrenceCountDiv").innerHTML = occurrenceCount;`

https://github.com/AtlasOfLivingAustralia/biocache-hubs/blob/84c536c6a8627ef78b917cf8a8680f44bc924682/grails-app/assets/javascripts/map.common.js#L113-L127

**Comment by nickdos** [comment]
This uses a Leaflet plugin - I have a feeling we're stuck on an old version of Leaflet due to plugin deps... might be a newer version of plugin that fixes this bug???

**Comment by adam-collins** [comment]
Seems OK today.
