### ISSUE TITLE
Spatial search can't remove drawn areas

### ISSUE THREAD

**Issue by alexhuang091** [AtlasOfLivingAustralia/biocache-hubs#492]
https://user-images.githubusercontent.com/61677987/132268793-2aa93c44-bb97-4a69-a2ce-a0e9f1c4f6df.mov

**Comment by adam-collins** [comment]
Still a problem

**Comment by adam-collins** [comment]
Seems we all missed the 'save' button. It appears right next to the 'delete' icon when in 'delete' mode. There is also a 'cancel' button.

There are 2 ways to delete a drawn area. 
1. Click 'delete' icon, click on the area to remove, click 'save' button beside the 'delete' icon.
2. Click on the area, click on the link in the area's popup 'remove this area'.

I am more inclined to remove the 'delete' icon than change its behaviour.
