### ISSUE TITLE
DQ filter info modal - missing `0` for groups with zero records in filter set

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#495]
When DQ filters are being applied, each DQ group looks like:

![image](https://user-images.githubusercontent.com/532845/132324173-83b7394e-282d-4d9b-b40e-b5515753c75e.png)

When the group has `0 records excluded` and you click the `i` info icon, the modal popup (on prod) shows:

![image](https://user-images.githubusercontent.com/532845/132324321-aab13c6a-9c2d-480a-a6ab-0c704e5e0e78.png)

However on biocache-test, the same popup is showing:

![image](https://user-images.githubusercontent.com/532845/132324498-4254ae3c-e74e-4516-adc8-647790c24a8c.png)

Note the missing `0` in front of `records`.

**Comment by alexhuang091** [comment]
on prod, if you 
1. disable the category (by unticking the checkbox)
2. click the <i>

you'll see same thing

**Comment by alexhuang091** [comment]
@nickdos fix deployed to test, please check when you have time

**Comment by nickdos** [comment]
https://avh-test.ala.org.au and https://biocache-test.ala.org.au both tested and all good ✅
