### ISSUE TITLE
lifeform facet filter fails

### ISSUE THREAD

**Issue by mbohun** [AtlasOfLivingAustralia/biocache-hubs#50]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=282
*date:* Tue Nov  5 19:05:34 2013
*author:* john.t...@austmus.gov.au
 ---

In BioCache, using Lifeform filter with other filters fails.
Sometimes...

Three examples: The first two fail, the third example is OK
Example 1 (fail)
quick search = everything
Filter on Australia + Birds (Problem - results leave Australia out)
[http://biocache.ala.org.au/occurrences/search?q=*%253A*&fq=country%253AAustralia&fq=species_group:Birds#tab_recordsView](http://biocache.ala.org.au/occurrences/search?q=*%253A*&fq=country%253AAustralia&fq=species_group:Birds#tab_recordsView)

Example 2 (Fail)
quick search = animals
Filter on Australia + Birds (Problem - results leave Australia out)
[http://biocache.ala.org.au/occurrences/search?q=animals&fq=country%253AAustralia&fq=species_group:Birds#tab_recordsView](http://biocache.ala.org.au/occurrences/search?q=animals&fq=country%253AAustralia&fq=species_group:Birds#tab_recordsView)

Example 3 (success)
quick search = birds
Filter on Australia + Birds (NOT a Problem - Australia is included)
[http://biocache.ala.org.au/occurrences/search?q=lsid%3Aurn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3A5ed80139-31bb-48a8-9f57-42d8015dacbb&fq=country%3AAustralia&fq=species_group:%22Birds%22#tab_recordsView](http://biocache.ala.org.au/occurrences/search?q=lsid%3Aurn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3A5ed80139-31bb-48a8-9f57-42d8015dacbb&fq=country%3AAustralia&fq=species_group:%22Birds%22#tab_recordsView)

Operating system: Win7
Browser: FF25, Chrome30, IE9

**Comment by nickdos** [comment]
Examples now work.
