### ISSUE TITLE
Refactor `taxa` searches

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#503]
Currently, biocache-hubs uses a dedicated `taxa` param for simple and quick search inputs. This is handled by the `AdvancedSearchParams.groovy` class to reformat as a regular biocache-service query with the controller performing the names lookup directly in biocache-hubs (via https://bie-ws.ala.org.au/ws/species/lookup/bulk). It was written before biocache-service implemented its own `taxa` pseudo field but is now mostly redundant. The `bulk lookup` service is suboptimal for this task and biocache-service uses the new names matching service, which does a better job.

Required change is to rewire the simple, quick & species/taxon search inputs to use the regular `?q=taxa:{$query}` syntax instead of the existing `?taxa=${query}` syntax. Existing/historical URLs that use the `taxa` param should continue to work but anyone using the UI to search should be using the new syntax (regular `q` param). For this new case, no names lookups should be performed in biocache-hubs, as biocache-service will handle that task.

See below for inputs needing changing.

Simple search input:
![image](https://user-images.githubusercontent.com/532845/133717394-d73d9416-cb33-47c4-a0c4-21a2da59c83e.png)

4 x species/taxon inputs:
![image](https://user-images.githubusercontent.com/532845/133717431-ee342156-d887-4798-b4df-1b54639465f6.png)

Quick search input:
![image](https://user-images.githubusercontent.com/532845/133717505-021910f2-2bcb-4530-8597-cc8c48f2411c.png)

Also, investigate the [batch taxon search tab](https://biocache.ala.org.au/search#tab_taxaUpload), to see if it is also internally calling the `https://bie-ws.ala.org.au/ws/species/lookup/bulk` service and see if the values can be sent to biocache-service directly (I think they already are).

**Comment by alexhuang091** [comment]
Quick question @nickdos (sorry for the Chinese in below screen capture)

In this case, currently `AdvancedSearchParams.groovy` formats query to `taxa=aaa OR bbb OR ccc OR ddd&q=bbbbbb`
<br/>and biocache-hubs converts it to somthing like
`q = (lsid:urn:lsid:biodiversity.org.au:afd.taxon:ca203904-a17d-46af-aaaa-0b7238f9ff0c OR text:"bbb" OR text:"ccc" OR text:"ddd") AND bbbbb`<br/>
<img width="867" alt="截屏2021-09-22 下午12 01 40" src="https://user-images.githubusercontent.com/61677987/134271789-ce96558d-0755-4ca5-9db3-f78fb0697050.png">

**Comment by nickdos** [comment]
> so we'll abandon the use of `grailsApplication.config.skin.useAlaBie`

Not entirely as we still want to support legacy requests, which will still use that setting. E.g. a user goes back to their list of downloads (https://doi.ala.org.au/myDownloads) and wants to re-run a download from a year ago. That search request should behave the same way and use old `&taxa=foo` syntax via BIE.

But the user going via the UI and searching via form will get the new syntax.

**Comment by nickdos** [comment]
> Quick question @nickdos (sorry for the Chinese in below screen capture)
> 
> In this case, currently `AdvancedSearchParams.groovy` formats query to `taxa=aaa OR bbb OR ccc OR ddd&q=bbbbbb`
> 
> and biocache-hubs converts it to somthing like
> `q = (lsid:urn:lsid:biodiversity.org.au:afd.taxon:ca203904-a17d-46af-aaaa-0b7238f9ff0c OR text:"bbb" OR text:"ccc" OR text:"ddd") AND bbbbb`

We won't do that "fall-back" in hubs. We'll simply pass the original text (string the user entered) to biocache-service and let the service do the fallback (assuming it does that). I think hubs can prompt the user to try the equiv. `text:foo` search on the "no records found" page anyway.

**Comment by alexhuang091** [comment]
> We won't do that "fall-back" in hubs. We'll simply pass the original text (string the user entered) to biocache-service and let the service do the fallback (assuming it does that). I think hubs can prompt the user to try the equiv. `text:foo` search on the "no records found" page anyway.

Hi Nick, my understanding is UI construts the query to `q=xxx`(simple search) or `q=xxx and (taxa = aaa or bbb)`(advanced search) and sends it to `biocache-hubs`, 
`biocahe-hubs` expands the taxa part to a possible lisd:xxx and gets a new `q` and sends to `biocache-service`

1. we need to support old URL, which goes directly to `biocache-hubs` so there won't have code change in `hubs`. 
2. then we only update `AdvancedSearchParams.groovy` so that it never ouputs somethings like taxa=xxx, instead everything should be in `q`.

Is it correct?

**Comment by nickdos** [comment]
> 1. we need to support old URL, which goes directly to biocache-hubs so there won't have code change in hubs. or at least compatible with possible old query
> 2. then we only update AdvancedSearchParams.groovy so that it never ouputs somethings like taxa=xxx, instead everything should be in q.
>
>Is it correct?

Yes, that sounds right.

We only support old-stlye via direct URL (via `&taxa=acacia`), as you said. But using the UI, all searches should use either `q` or `fq` params (ignoring spatial searches that use `lat`,`lng` & `radius` as well).

It might be tricky to support both formats, so we might need to catch the old style and redirect to a different controller method (could also be a code block in same method??) that uses a different version of `AdvancedSearchParams` to create the URL sent to biocache-service. That is just a guess - start coding it and see how far you get first.

**Comment by nickdos** [comment]
Would be good to first create some controller unit tests with various search param combinations, so that the new code can be run against the unit tests to confirm nothing has changed.

**Comment by alexhuang091** [comment]
Hi @nickdos, then my question is, in below picture, what query will new `AdvancedSearchParams.groovy` constructs and sends to `biocache-hubs`?

<img width="867" alt="截屏2021-09-22 下午12 01 40" src="https://user-images.githubusercontent.com/61677987/134280001-232016df-b180-4f6a-921a-77a1a2434079.png">

**Comment by alexhuang091** [comment]
> It might be tricky to support both formats, so we might need to catch the old style and redirect to a different controller method (could also be a code block in same method??) that uses a different version of `AdvancedSearchParams` to create the URL sent to biocache-service. That is just a guess - start coding it and see how far you get first.

Hi Nick, no it won't be that complicated. 

Enter URL in address bar directly (for example http://dev.ala.org.au:8081/ala-hub/occurrences/search?taxa=aaa+OR+bbb&q=q), you'll go to `occurrenceController::list()` where has old code so whatever params will be handled.

```
"/occurrences/search"(controller: 'occurrence', action: 'list')
"/occurrence/search"(controller: 'occurrence', action: 'list')
```

The change will be in `AdvancedSearchParams`, when user enters something and click search 

```
class HomeController {
    def advancedSearch(AdvancedSearchParams requestParams) {
        log.debug "Home controller advancedSearch page"
        //flash.message = "Advanced search for: ${requestParams.toString()}"
        redirect(controller: "occurrences", action:"search", params: requestParams.toParamMap()) // this is handled by occurrenceController::list()
    }
```
we only need to make sure AdvancedSearchParams doesn't carry any `taxa` param

**Comment by nickdos** [comment]
Sounds good

**Comment by alexhuang091** [comment]
Current advanced search is like `search?taxa=aaa+OR+bbb&q=qqq`, `biocache-service` handles `aaa+OR+bbb` for taxa matching

Now the query will be like
http://localhost:8078/occurrences/search?q=text:qqq AND taxa:(aaa OR bbb) or 
http://localhost:8078/occurrences/search?q=text:qqq AND (taxa:aaa OR taxa:bbb)

Let me check if `biocache-service` can handle them properly

**Comment by alexhuang091** [comment]
It will be somewhat complicated to make `biocache-service` work perfectly (handle requests from both `biocahe-hubs` and API requests directly from users).

If just to make it working with `biocache-hubs` it will be easier.

Look at how `biocche-service` works now

1. it sends `aaa OR bbb` directly to get GUID which is incorrect. We should like what `biocahe-hubs` does, split it by `OR` to get list ['aaa', 'bbb']
2. if we put `taxa` into `q`, the query from `biocache-hubs` could be `q=text:qqq AND taxa:(aaa OR bbb)` or `q=text:qqq AND (taxa:aaa OR taxa:bbb)`, the `()` is required. Currently we use `taxaPattern = Pattern.compile("(^|\\s|\"|\\(|\\[|')taxa:\"?([\\w\\s\\(\\)\\.:\\-_]*)\"?");` to  extrat taxa which can't handle `()`. 
<br/>I suggest to put taxa into `fq` so the query will be `q=text:qqq&fq=taxa:aaa OR bbb` <br/>or  `q=text:qqq&&fq=taxa:aaa OR taxa:bbb` (this also doens't work now because the reuglar exoression extracts `aaa OR taxa:bbb` as taxa) no `()` is requierd and eixsiting reqular experssion will work.

<img width="1006" alt="截屏2021-09-23 下午12 29 57" src="https://user-images.githubusercontent.com/61677987/134446705-2cdca693-238c-4990-a019-f0af5f87c318.png">

**Comment by nickdos** [comment]
I'm not sure what you mean by "handle requests from both biocahe-hubs **and API requests** directly from users"...

Biocache-hubs just needs to support (old) URLs (saved URLs on old download DOI pages, mostly) that contain the param format `taxa={query}`. There is no need to worry about biocache-service or any API calls.

**Comment by nickdos** [comment]
Testing it, I get the same number of results for 

https://biocache.ala.org.au/occurrences/search?taxa=acacia+dealbata+OR+osphranter+rufus+OR+pogona+barbata

and

https://biocache-ws.ala.org.au/ws/occurrences/search?q=taxa:%22acacia+dealbata%22+OR+taxa:%22osphranter+rufus%22+OR+taxa:%22pogona+barbata%22

**Comment by alexhuang091** [comment]
Hi Nick, I'm talking about backend ablity to parse `taxa`, it's not perfect now.  `biocache-service` can't handle like `q=taxa:(aaa)` or `q=taxa:(aaa OR bbb)` for now. We, `biocache-hubs` can avoid generating this forms of queris but users can issue requests like this.

for `biocache-hubs`, currently we send `q=text:qqq&taxa=aaa OR bbb`, we can change that to `q=text:qqq&fq=taxa:aaa OR bbb`. this will be perfect. backend can parse it.

Since there can have only 1 `q` in url so if you don't like to put them into `fq`. we have to use `q=text:qqq AND taxa:(bbb OR ccc)`, `()` must be used I guess? (I'll verify this) that means backend has to process `()`

**Comment by alexhuang091** [comment]
Hi @nickdos, for the **Quick search** in main page
https://github.com/AtlasOfLivingAustralia/biocache-hubs/blob/46f99c19fba2c160d2933ba8d135627691d8a415/grails-app/views/occurrence/list.gsp#L125-L126

`<g:set var="searchQuery" value="${grailsApplication.config.skin?.useAlaBie?.toBoolean() ? 'taxa' : 'q'}"/>`
The initial value is whatever in `taxa` param
![2](https://user-images.githubusercontent.com/61677987/134829403-ba6aee3a-93d8-4149-be51-42ce562fe9c6.jpg)

Now we no longer have `taxa` param, they are now in `q` so like `q=taxa:aaa` (simple search) or `q=text:qqq AND (taxa:aa OR taxa:bb OR taxa:cc` (advanced search)

that means:
1. we need to parse `q`, split by `AND` first then split by `OR`, then split by `:` to get all values and join by `OR` as the initial input value
2. when user clicks search, split the input value by `OR` and prefix each value with `taxa:` to form the `q` for query
 
Do you want this to be done? or maybe just set the initial value of search input to be empty?

**Comment by nickdos** [comment]
Hard to tell without trying a few options... I'd prefer a simple solution that has zero/minimal logic for parsing the query. So maybe the approach is check the value of the `q` param to see if it has fields specified. If not, then copy the value into the simple "input" box, otherwise leave it empty.

E.g. if a user types "red kangaroo" into the simple search input at https://biocache.ala.org.au/ then that string should appear in the red highlighted input in the comment above. The alternative is the user used the advanced search form (or one of the other tabs like batch taxon search) and then hit enter. When they see the search results page, the simple input should be empty.

**Comment by alexhuang091** [comment]
> if a user types "red kangaroo" into the simple search input at https://biocache.ala.org.au/ then that string should appear in the red highlighted input in the comment above

Hi @nickdos , 
- whatever you entered in **simple search** will be prepend with `taxa:` and put into `q`
- whatever you entered in **advanced search** will be prepend with `text:` and put into `q`
- when you entered nothing in **advanced search** first input but entered some in taxa input, it will be `q=(taxa: aaa OR taxa bbb)`

so only when you entered nothing in **advanced search** will there have no field in `q` and the value then will be empty. So if you don't want to add logic to parse query (which I agree with you), leave that highlighted box always empty will be good enough.

**Comment by nickdos** [comment]
Just tested with simple search and results are all as expected but the query string the user entered is not shown in the "quick search" input, as it is on prod.

Prod
![image](https://user-images.githubusercontent.com/532845/140678512-b8184a26-78e2-46b4-a4b5-de19d6b034d5.png)

Test
![image](https://user-images.githubusercontent.com/532845/140678569-e194088b-be88-4abe-bdc3-0da31b7ac488.png)

**Comment by alexhuang091** [comment]
Hi Nick, I think what we agreed is not to parse the query string.

Old system can easily put taxa=`pogona` into the input.

But now the query string is `q=taxa:pogona`, in case user comes from advanced search it could be `q=text:ccc+AND+(taxa:"aaa"+OR+taxa:"bbb")`

This is your original reply 

> I'd prefer a simple solution that has zero/minimal logic for parsing the query. So maybe the approach is check the value of the q param to see if it has fields specified. If not, then copy the value into the simple "input" box, otherwise leave it empty.

**Comment by alexhuang091** [comment]
> as `searchQuery` is not defined in GSP or controller, that I could see. Should it be quoted as a string?

Hi Nick, sorry `searchQuery` was accidently deleted by me in https://github.com/AtlasOfLivingAustralia/biocache-hubs/commit/be864aa75bab23ebb80ab661f1c3f5cb9191f505#diff-da61b2fd3f0e65dc8c9c8ff5e8510ba299d33bde923db33762032499757ed9e2

We just need to put it back. All queries from new system will have a `a=taxa:xxx`, so input box should always be empty. (if we do as you said: _the approach is check the value of the q param to see if it has fields specified. If not, then copy the value into the simple "input" box, otherwise leave it empty_.)

Only those from old links in form of `search?taxa=xxx` will have value of taxa param put into input.

**Comment by nickdos** [comment]
OK, thanks for the reminder. Will leave it as is and can always make a new issue to check for simple scenario of `q=taxa:"xxx"` which is the most common case and copy `xxx` into the input box.

**Comment by alexhuang091** [comment]
yes, `q=taxa:xxx` will be easier to implement. I'll put that line of `searchQuery` back so it can handle old form url

**Comment by adam-collins** [comment]
This is a bit long, so I didn't read it all. `q=taxa:xxx` is currently implemented.
