### ISSUE TITLE
user assertion name is `undefinded` in biocache-hubs

### ISSUE THREAD

**Issue by alexhuang091** [AtlasOfLivingAustralia/biocache-hubs#504]
flag an issue on a prod record, you will see

![1](https://user-images.githubusercontent.com/61677987/133951797-bf80b521-6c4b-496f-803e-c3c4adf19b9a.jpg)

**it's supposed to show the name of the issue, for example: 'Suspected outlier', 'Geospatial issues'. etc.**

**Comment by alexhuang091** [comment]
It was broken by Dave's change on May 25 https://github.com/AtlasOfLivingAustralia/biocache-service/commit/7711b7016f66602704fd30404f26b29ea0b8892f#diff-4323f21f8c796cec348933df95392cf36f82a8a771192122cc7fe8b1f05c0215

so user assertions added after that will have an empty name in database. In my commit I added a workadound so assertion name will be set if empty.

**Comment by adam-collins** [comment]
Code is merged, assuming it is done.
