### ISSUE TITLE
Add a 'record verified/corrected' option in the list of assertion categories

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/biocache-hubs#51]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=283
*date:* Tue Nov  5 21:59:40 2013
*author:* chris.go...@gmail.com
 ---

Requested via support email on 6/11.

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/biocache-service#22
