### ISSUE TITLE
Add link to "My Downloads" on download confirmation screen

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#510]
@javier-molina suggested it would be useful to include a link to the user's ["My downloads" page](https://doi.ala.org.au/myDownloads), on the download confirmation. This would've been useful when the download emails were not working.

"My Downloads - view a list of all your previous downloads" (linked to https://doi.ala.org.au/myDownloads)

![image](https://user-images.githubusercontent.com/532845/136313063-58a42db1-5613-44a9-a46f-34bc36bb3e42.png)

**Comment by alexhuang091** [comment]
Hi @nickdos how about this?

<img width="419" alt="截屏2021-10-08 下午12 34 25" src="https://user-images.githubusercontent.com/61677987/136484401-70e59779-e7eb-4748-b351-9f1362da7d11.png">

**Comment by nickdos** [comment]
The 2 links under each other are a bit messy & confusing to the eye. How about moving the "My downloads..." link to be below the grey box?

**Comment by nickdos** [comment]
As an afterthought - instead of putting the text link below the box, another solution could be to change the main "call to action" button to be a button group. E.g. 

``` < Return to search results  |  My Downloads > ```
