### ISSUE TITLE
application error on `raw_taxon_name` query

### ISSUE THREAD

**Issue by alexhuang091** [AtlasOfLivingAustralia/biocache-hubs#511]
this query 

`https://biocache.ala.org.au/occurrences/search?q=raw_taxon_name:%22Anigozanthos%20rufus`

caused an application error on `biocache-hubs`

---
Steps to reproduce:
1. search `red kangaroo` in simple search
2. 
![1](https://user-images.githubusercontent.com/61677987/136896471-36334713-fbc9-474a-852c-638e6d8a1ffa.jpg)

**Comment by alexhuang091** [comment]
It should be an issue on `biocache-hubs`, the url constructed is incorrect.

![2](https://user-images.githubusercontent.com/61677987/136897339-f1598d55-cf17-4cd3-969c-8c43fdc3c0ef.jpg)

**Comment by nickdos** [comment]
I can't replicate this - "red kanagaroo" gives the expected search result for _Osphranter rufus_, not _Anigozanthos rufus_ as reported above.

  
https://biocache.ala.org.au/occurrences/search?q=raw_taxon_name:%22Anigozanthos%20rufus%22 gives the expected result too (not error)
