### ISSUE TITLE
data-box application error

### ISSUE THREAD

**Issue by alexhuang091** [AtlasOfLivingAustralia/biocache-hubs#514]
data-box showing application error on 

https://biocache-databox.ala.org.au/occurrences/4a5041ab-26d3-4c8a-a0aa-cb1f8f05b8fe

although the ws call 
https://biocache-ws-databox.ala.org.au/ws/occurrences/4a5041ab-26d3-4c8a-a0aa-cb1f8f05b8fe

returns valid data

**Comment by adam-collins** [comment]
Seems OK today.
