### ISSUE TITLE
Not getting an email when downloading records

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/biocache-hubs#517]
**Steps to recreate**

1. opened Australian Museum ornithology collection records - https://biocache.ala.org.au/occurrences/search?q=collection_uid%3Aco120
2. Selected download
3. Selected darwin core option
4. Selected .csv option
![image](https://user-images.githubusercontent.com/23368496/138186552-4dec3552-d15d-4269-ace0-db0e9aaed574.png)

5. Submitted
6. Got popup saying download being prepared and with option to see URL
![image](https://user-images.githubusercontent.com/23368496/138186623-c41599f3-5437-4719-9243-b5d7a3969c74.png)

7. Opened dialogue box for URL
8. copied to clipboard
![image](https://user-images.githubusercontent.com/23368496/138186668-c30b792e-fbd9-4654-98d9-0e9096fae971.png)
Link:
https://biocache.ala.org.au/ws/occurrences/offline/download?hubName=Atlas+of+Living+Australia&file=records-2021-10-21&mintDoi=true&reasonTypeId=10&dwcHeaders=true&searchUrl=https%3A%2F%2Fbiocache.ala.org.au%2Foccurrences%2Fsearch%3Fq%3Dcollection_uid%253Aco120%26qualityProfile%3DALA&fields=data_resource_uid%2Cimages%2Craw_recordedBy%2Cmodified%2Clanguage%2Clicense%2CrightsHolder%2CaccessRights%2CbibliographicCitation%2Creferences%2CinstitutionID%2CcollectionID%2CdatasetID%2CinstitutionCode%2CcollectionCode%2CdatasetName%2CownerInstitutionCode%2CbasisOfRecord%2CinformationWithheld%2CdataGeneralizations%2CdynamicProperties%2CoccurrenceID%2CcatalogNumber%2CrecordNumber%2CrecordedBy%2CindividualCount%2CorganismQuantity%2CorganismQuantityType%2Csex%2ClifeStage%2CreproductiveCondition%2Cbehavior%2CestablishmentMeans%2CoccurrenceStatus%2Cpreparations%2Cdisposition%2CassociatedMedia%2CassociatedReferences%2CassociatedSequences%2CassociatedTaxa%2CotherCatalogNumbers%2CoccurrenceRemarks%2CorganismID%2CorganismName%2CassociatedOccurrences%2CpreviousIdentifications%2CmaterialSampleID%2CeventID%2CparentEventID%2CfieldNumber%2CeventDate%2CeventTime%2Cyear%2Cmonth%2Cday%2CverbatimEventDate%2Chabitat%2CsamplingProtocol%2CsamplingEffort%2CsampleSizeValue%2CsampleSizeUnit%2CfieldNotes%2CeventRemarks%2ClocationID%2ChigherGeography%2Ccontinent%2CwaterBody%2CislandGroup%2Cisland%2Ccountry%2CcountryCode%2CstateProvince%2Ccounty%2Cmunicipality%2Craw_locality%2CverbatimLocality%2CminimumElevationInMeters%2CmaximumElevationInMeters%2Celevation%2CverbatimElevation%2CminimumDepthInMeters%2CmaximumDepthInMeters%2Cdepth%2CverbatimDepth%2ClocationAccordingTo%2ClocationRemarks%2CdecimalLatitude%2CdecimalLongitude%2CgeodeticDatum%2CcoordinateUncertaintyInMeters%2CcoordinatePrecision%2CverbatimCoordinates%2Craw_decimalLatitude%2CverbatimLatitude%2Craw_decimalLongitude%2CverbatimLongitude%2Craw_geodeticDatum%2CverbatimCoordinateSystem%2CverbatimSRS%2CfootprintSRS%2CgeoreferencedBy%2CgeoreferencedDate%2CgeoreferenceProtocol%2CgeoreferenceSources%2CgeoreferenceVerificationStatus%2CgeoreferenceRemarks%2CidentificationID%2CidentificationQualifier%2CtypeStatus%2CidentifiedBy%2CdateIdentified%2CidentificationReferences%2CidentificationVerificationStatus%2CidentificationRemarks%2CtaxonID%2CscientificNameID%2CacceptedNameUsageID%2CtaxonConceptID%2CscientificName%2CacceptedNameUsage%2CparentNameUsage%2CoriginalNameUsage%2CnameAccordingTo%2CnamePublishedIn%2ChigherClassification%2Ckingdom%2Cphylum%2Cclass%2Corder%2Cfamily%2Cgenus%2Csubgenus%2CspecificEpithet%2CinfraspecificEpithet%2CtaxonRank%2CverbatimTaxonRank%2CscientificNameAuthorship%2CvernacularName%2CnomenclaturalCode%2CtaxonomicStatus%2CnomenclaturalStatus%2CtaxonRemarks%2Craw_basisOfRecord%2CmeasurementDeterminedDate%2CvideoIDs%2Cspecies%2CmeasurementRemarks%2CmeasurementValue%2CrelationshipRemarks%2CidentifierRole%2CrelationshipOfResource%2CmeasurementMethod%2Cprovenance%2CsoundIDs%2Cid%2Crights%2Csource%2Craw_scientificName%2Craw_continent%2CmeasurementID%2CmeasurementType%2CmeasurementUnit%2CmeasurementDeterminedBy%2CmeasurementAccuracy%2CrelatedResourceID%2CimageIDs%2Ctype&fileType=csv&qa=none&sourceTypeId=0&email=robina.sanderson%40gmail.com&doiDisplayUrl=https%3A%2F%2Fbiocache.ala.org.au%2Fdownload%2Fdoi%3Fdoi%3D&q=collection_uid%3Aco120&qualityProfile=ALA
9. Wait for 15+ minutes

**Expected result**
1. Would get email with results
2. opening the copied URL would get results

**Actual results**
1. Did not receive email
2. Opening the copied URL results in an error message

3. opening the downloads option for my profile shows the download and I can access the download from there.

**Comment by alexhuang091** [comment]
Hi @RobinaSanderson, for Expected result.2, actually opening the copied URL initiates the download again, it's not for viewing records or checking download results.

**Comment by alexhuang091** [comment]
I've attached the download log by Robina, 2 succeeded, 2 failed. Both success case come from 52.63.189.25, both failed case come from 140.253.225.40

[download.log](https://github.com/AtlasOfLivingAustralia/biocache-hubs/files/7385216/download.log)
