### ISSUE TITLE
Remove default facets

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#52]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=299
*date:* Wed Nov 13 16:37:15 2013
*author:* moyesyside
 ---

By default, the occurrence_year and uncertainty facets are always returned. This was a hack for the Spatial Portal.

This should be removed and added to the SP code by add these facets into the request.

**Comment by nickdos** [comment]
Appears to be fixed now.
