### ISSUE TITLE
flag an issue problem

### ISSUE THREAD

**Issue by alexhuang091** [AtlasOfLivingAustralia/biocache-hubs#520]
when input an invalid record id, it should show `The record id can't be found` but actually not.

it's caused by `biocache-service` backend change which breaks `occurrenceController::exists(String id)` 
<img width="588" alt="截屏2021-11-05 下午4 22 16" src="https://user-images.githubusercontent.com/61677987/140463450-82489ad9-76d0-4fd0-aee5-b7a38b9e8f4e.png">

**Comment by adam-collins** [comment]
Pull request merged with changes to associated code. Assuming it is done.
