### ISSUE TITLE
Charts tab issue with decade display

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#528]
https://biocache-test.ala.org.au/occurrences/search?q=occurrence_date%3A%5B2020-07-20T00%3A00%3A00Z+TO+2020-07-30T00%3A00%3A00Z%5D#tab_chartsView

Note the filter for this search is date: 2020-07-20 TO 2020-07-30... 

Decade charts shows wrong decade (2010-2019) and link (clicking on the chart) returns zero results (as expected)

![image](https://user-images.githubusercontent.com/532845/152718952-0dbd542b-83c0-49d4-ade3-8029cbf8b7a0.png)

Fix is to show correct decade (2020-2029).

Note: this may be a bug in the charts JS code - not sure where this might reside.

**Comment by adam-collins** [comment]
I think it is working today because the charge lists the expected decade and clicking on it works.
