### ISSUE TITLE
Facets for Datasets and Data Providers list codes instead of names

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/biocache-hubs#53]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=420
*date:* Sun Dec  8 19:58:50 2013
*author:* leebel...@gmail.com
 ---

Previously in the SP, the facet lists used the names of the data providers and datasets. Now it appears that code are used for both in the form of "drxxx" for datasets and "dpxxx" for data providers. 

Rendering them useless without a lookup.

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/spatial-portal#65
