### ISSUE TITLE
Adding user annotations fails on biocache-ws-test

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#530]
Adding an annotation via the UI is currently failing on the test site. E.g. https://biocache-test.ala.org.au/occurrences/2d761aca-5f22-4ffb-a3ef-69312c21e121 - click "Flag an issue".

I can see via the console the following POST fails with a `403`:

https://biocache-test.ala.org.au/occurrences/assertions/add

Presumably biocache-hubs needs to send the appropriate JWT code or a different form of an API key to `biocache-ws-test`. Note, the current value for `biocache.apikey` is valid for auth-test.

@djtfmartin Can you point to some example code in collectory to speed this up, please?

**Comment by nickdos** [comment]
Was related to API gateway changes - so holding off testing until those changes are merged into develop

**Comment by adam-collins** [comment]
Annotations have been created since this issue. Assuming it is working now.
