### ISSUE TITLE
Minor i18n issues related to DQ changes 

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#537]
2 PRs contributed by @vjrj that fix display issues for LA users, that were missed when DQ changes were released in 2021.

- #535 
- #536

**Comment by vjrj** [comment]
Sorry @nickdos for not adding this issue previously.

#530 internationalize these messages:

![image](https://user-images.githubusercontent.com/180085/157127884-51544960-d467-4956-828d-1303a5641375.png)

![image](https://user-images.githubusercontent.com/180085/157127893-952bfce0-8899-41d6-a9f0-871bccd05be6.png)

![image](https://user-images.githubusercontent.com/180085/157127914-53ed9a43-9874-43b9-8495-873ce5fc9641.png)

![image](https://user-images.githubusercontent.com/180085/157128061-087119bd-37c5-457a-8578-328d3592b12c.png)

and #535 has similar screenshots.

**Comment by nickdos** [comment]
Thanks for screenshots @vjrj - makes testing changes much easier 👍

**Comment by nickdos** [comment]
QA - no issues detected on test site.
