### ISSUE TITLE
Minor i18n issues

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/biocache-hubs#538]
Minor i18n issues I'm trying to fix:

- [x] ![image](https://user-images.githubusercontent.com/180085/157274206-121fbc0d-da80-41cf-bb0e-81735ab81dd8.png)
- [x] ![image](https://user-images.githubusercontent.com/180085/157274581-54b47af5-4ee2-473f-bc4e-4ece3d369268.png)
- [x] ![image](https://user-images.githubusercontent.com/180085/157292331-bbd57028-ed1f-40a3-99b7-db44f2b7c399.png)
- [x] ![image](https://user-images.githubusercontent.com/180085/157310475-5bb66ee1-8d4d-4b9b-b4cf-568cce275db7.png)
- [x] ![image](https://user-images.githubusercontent.com/180085/157315938-21dfd441-11c5-4ba2-b4d5-e9664a5b5e64.png)
- [x] ![image](https://user-images.githubusercontent.com/180085/157404451-9fc7498c-cbb6-452b-938f-95238e5d78d5.png)
![image](https://user-images.githubusercontent.com/180085/157428135-2b25c4ed-4b48-4738-846e-c60c42de5ea3.png)

I'm searching for more.

**Comment by nickdos** [comment]
QA - tested for ALA and no adverse issues detected. I'm unable to test other language or locale deployments so if any are detected, we'll need to reopen this issue after the next release.

**Comment by vjrj** [comment]
In general you can test:

- installing `ala-i18n` to get the last messages_*
- adding `lang=XX` to the url

For instance:
 
- https://collections.ala.org.au/?lang=es 
- https://bie.ala.org.au/?lang=es

although as `ala-i18n` is not installed it uses old `messages_es`.

But for `ala-hub` this does not work and I think that is because Locale is hardcoded via `defaultLocale` config.

**Comment by nickdos** [comment]
Thanks @vjrj I did try setting lang=es today and was puzzled  why it didn't work, as I used to test it that way.
