### ISSUE TITLE
Randomised sequence of data quality test results in CSV data output

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocache-hubs#54]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=489
*date:* Wed Dec 18 17:02:01 2013
*author:* CoolDa...@gmail.com
 ---

Reported by user wanting to do periodic manual exports from ALA to import into a local system for mapping and analysis.

The sequence of columns for DQ test results is inconsistent in the CSV output between different download events. Client is finding this makes processing on his end difficult.

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/biocache-service#23
