### ISSUE TITLE
For zero results search add option to try with DQ filters off

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#540]
As suggested by @timhicks-ala in Slack and solution suggested by @djtfmartin & @matthewandrews https://atlaslivingaustralia.slack.com/archives/CR8ASH0G1/p1646733064117709

If user gets zero results, e.g.

> No records found for catalogNumber:myCatalogNumber

then prompt with:

> No records found for catalogNumber:myCatalogNumber. [Try this search without data quality filters applied](#) [linked]

**Comment by nickdos** [comment]
Seems a tad more complicated as the usual "No records found" is not displayed for this corner case...

![image](https://user-images.githubusercontent.com/532845/157577854-f225b4a8-3670-4ac9-9816-d3a91daf07f4.png)

So we either have to make the results page look the same as when zero records are returned (no table with tabs shown at all) or try and squeeze the message into the UI the way it appears above...

Going with first option is preferred as it makes the UX consistent with how it has always shown an empty results set but will be a bit more work.

**Comment by djtfmartin** [comment]
@nickdos I'm not sure i have a preference here.

**Comment by adam-collins** [comment]
Closing as not more work is requested.
