### ISSUE TITLE
Browser console shows Javascript error on advance search/Spatial search

### ISSUE THREAD

**Issue by Rita-C** [AtlasOfLivingAustralia/biocache-hubs#545]
![Screen Shot 2022-04-22 at 10 23 09 am](https://user-images.githubusercontent.com/29115246/164603889-a918af2b-fb0b-470b-8ace-5f14c2dfabb3.png)

**Comment by adam-collins** [comment]
Reproduce with a large circle, maybe. It appears to work without error on the occurrences/search page.
