### ISSUE TITLE
Name type option on advanced search is not being read

### ISSUE THREAD

**Issue by Rita-C** [AtlasOfLivingAustralia/biocache-hubs#547]
Root cause for https://github.com/AtlasOfLivingAustralia/avh-hub/issues/132#issuecomment-1119149417"

On `AVH` advanced search tab, the name type option "Supplied name" above the inputs, results in it using the "Matched name" - so that option is not being read.

**Comment by Rita-C** [comment]
Hi @nickdos , could you please code review the change?
I tested locally, works as expected.

**Comment by nickdos** [comment]
Code looks good ✅

**Comment by Rita-C** [comment]
Hi @nickdos, code deployed to avh-test, could you please test when you have a chance?

**Comment by nielsklazenga** [comment]
@Rita-C , I can do testing.

Matched name: https://avh-test.ala.org.au/occurrences/search?q=taxa%3A%22Agrostis+venusta%22 (327 records)
Provided name: https://avh-test.ala.org.au/occurrences/search?q=raw_scientificName%3A%22Agrostis+venusta%22 (128 records)

I think the supplied name search should have a terminal wild card, so it also finds the strings that have authorship, in this case 'Agrostris venusta Trin.' and/or infraspecific bits.

Also, the numbers given for the facets are higher by 20 than the numbers of results, 347 and 148 vs. 327 and 128, but that might have nothing to do with what you've done, although I would be interested to find out what these 20 records are.

**Comment by nielsklazenga** [comment]
@nickdos , yes, I think SOLR also does not allow it on 'string' fields, which `raw_scientific_name` is, and wild cards in SOLR are a pain if there are spaces in the search string. If this is not something that recently disappeared, I am happy for it to stay as it is. It is just that I noticed it just now.

**Comment by Rita-C** [comment]
> 

biocache-hub also displays higher by 20 in the facets results
https://biocache-test.ala.org.au/occurrence/search?q=taxa%3A%22Agrostis+venusta%22&fq=data_hub_uid%3Adh9&qualityProfile=ALA&disableAllQualityFilters=true

https://biocache-test.ala.org.au/occurrences/search?q=raw_scientificName%3A%22Agrostis+venusta%22&fq=data_hub_uid%3Adh9&qualityProfile=ALA&disableAllQualityFilters=true

**Comment by adam-collins** [comment]
Is more required on this issue?
