### ISSUE TITLE
download button a dataset page doesn't work

### ISSUE THREAD

**Issue by mbohun** [AtlasOfLivingAustralia/biocache-hubs#55]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=524
*date:* Tue Jan 14 20:41:20 2014
*author:* milo_nic...@hotmail.com
 ---

e.g. clicking the download records button on [http://collections.ala.org.au/public/show/dr365](http://collections.ala.org.au/public/show/dr365) produces an error - A reasonTypeId must be provided.

**Comment by nickdos** [comment]
Seems to be fixed.

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/collectory#41
