### ISSUE TITLE
Advanced search - Collection list should not include "Not supplied"

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#550]
Under the `Institution or collection` drop-down, right at the end there is a value `All records from Not Supplied`. This option should not be displayed and is you select it and search, it gives a result set that is not correct - it should be a negative search but instead does `collection_uid:*` (and not the correct `-collection_uid:*`).

Check the other drop-down lists and fix them as well.

**Comment by jack-brinkman** [comment]
Screenshot of advanced search page after commit 83b6765 (within ASBP hub):

![image](https://user-images.githubusercontent.com/104949733/176608074-90ae2777-aba9-4a25-b3a8-f44c793c970b.png)

**Comment by adam-collins** [comment]
Picked the fix from the branch it was sitting in.
