### ISSUE TITLE
new added Mulitvalue fields are not displayed properly

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/biocache-hubs#551]
New identified issues:

![Screen Shot 2022-07-11 at 3 15 56 pm](https://user-images.githubusercontent.com/31238531/178193618-6854852e-eed6-4ae0-b3d0-aa74fc019eb9.png)

Check this link: https://biocache-databox.ala.org.au/occurrences/e71a5549-2841-44fc-b2b1-2098c3de9e77

Biocache will compare fields of  **raw_recordedBy**  and **recordedBy**. If they are different, a 'supplied as' comment will be added.

However, we can see recordedBy has been updated to multivalues, but raw_recordedBy is still a string joined by ' _ '
`"raw_recordedBy":"CSIRO - CRIMP",`
`"recordedBy":["Csiro","Crimp"],`

In our Solr:
` <field name="raw_recordedBy" type="string" indexed="true" docValues="true"/>`
` <field name="recordedBy" type="string" docValues="true" multiValued="true" indexed="true"/>`

**raw_recordedBy should be multiValued, same as recordedBy**

Fixed
  **samplingProtocol**

--------- Solved---------
Link to: https://github.com/gbif/pipelines/issues/670 
For example, in this search:

https://biocache-ws-databox.ala.org.au/ws/occurrences/de159cbb-7aed-4bfb-872a-56594d795ed0

It shows:     Identified by   ["Marie Tarrant"]

It is displayed as an array of strings due to mulitivalues  type.

An array of identifiers is returned from:

https://biocache-ws-databox.ala.org.au/ws/occurrences/de159cbb-7aed-4bfb-872a-56594d795ed0

**Fixed**
identfiedBy AKA collector/s is defined as Multivalue in SOLR, but biocache returns a string joined with '|'
datasetName

List of multivalues. No values: this field is not defined in BiocacheIndex class
|Fields|BiocacheIndex (dev)|SOLR|
|-----|-----|-----|
| speciesGroup |Y|Y|
| speciesSubgroup |N|Y|
| speciesListUid ||Y|
| imageIDs |N|Y|
| soundIDs ||Y|
| videoIDs ||Y|
| multimedia |Y|Y|
| multimediaLicense ||Y|
| assertions |Y|Y|
| geospatialIssues ||Y|
| occurrenceYear |return the first year|Y|
| contentTypes ||Y|
| machineTags ||Y|
|datasetID||Y|
|datasetName||Y|
| identifiedBy ||Y|
|recordedByID||Y|
|recordedBy|Y|Y|
| lifeStageLineage ||Y|

Raised by @peggynewman  - it may not be related.
Example: specimenType
https://biocache-databox.ala.org.au/occurrences/de159cbb-7aed-4bfb-872a-56594d795ed0 problem specimenType field

**Comment by qifeng-bai** [comment]
![Screen Shot 2022-06-28 at 12 44 26 pm](https://user-images.githubusercontent.com/31238531/176080868-c4fee03d-c01e-479b-a744-3cf6996c4471.png)

**Comment by adam-collins** [comment]
It looks like these commits are applied.
