### ISSUE TITLE
BioCache autocomplete functionality is broken

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocache-hubs#556]
The search bar here brings up a bunch of autosuggestions: https://bie.ala.org.au/
The one here doesn't: https://biocache.ala.org.au/search#tab_simpleSearch
I have a user who has the second one bookmarked, and swears it used to show suggestions as well. a) Did it ever, and b) can it? He thinks it might've been turned off around the time we did the names upgrade, but I don't see how that's related.

Raised by Tim

**Comment by matthewandrews** [comment]
Biocache autocomplete requests at ALA (like https://bie.ala.org.au/ws/search/auto.json?limit=20&q=test ) are failing because the response has no CORS (Access-Control-Allow-Origin) header.  Note that it is being rewritten currently from bie.ala.org.au to bie-ws.ala.org.au

**Comment by timhicks-ala** [comment]
(For my own notes: raised in https://support.ehelp.edu.au/a/tickets/154958)

**Comment by matthewandrews** [comment]
This is working now (after merging the two BIE load balancers into one).
