### ISSUE TITLE
ingest process for Darwin Core archive including multiple images

### ISSUE THREAD

**Issue by mbohun** [AtlasOfLivingAustralia/biocache-hubs#56]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=526
*date:* Wed Jan 15 16:14:34 2014
*author:* milo_nic...@hotmail.com
 ---

Both MV and AM have requested to include multiple images with distinct metadata (e.g. photographer, rights).  We have recommended they produce a Darwin Core archive using the simple image extension [http://rs.gbif.org/extension/gbif/1.0/images.xml](http://rs.gbif.org/extension/gbif/1.0/images.xml).  The ingest process needs to be developed for the DWC-A.

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/biocache-store#29
