### ISSUE TITLE
Feature request - remember data filter checkbox status between searches

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocache-hubs#569]
Currently, the data filter system in Biocache can be set to remember a particular filter for future searches (eg, it will remember the General filter, or CSDM, the next time you start a search).

It does not currently remember the state of individual checkboxes under a filter - the use case for this is performing multiple searches in Biocache including environmental outliers, but needing to un-tick the box to exclude those in each search.

Feature requested in https://support.ehelp.edu.au/a/tickets/173809

**Comment by adam-collins** [comment]
pull request https://github.com/AtlasOfLivingAustralia/biocache-hubs/pull/576

**Comment by sughics** [comment]
Related: https://github.com/AtlasOfLivingAustralia/biocache-hubs/pull/577
