### ISSUE TITLE
Issue Log after test release with Cogntio and Grails 5 -  6.0.1-SNAPSHOT

### ISSUE THREAD

**Issue by sughics** [AtlasOfLivingAustralia/biocache-hubs#570]
Issues raised by ALA memebers after the test release with grails5 and cognito for the bioacche-hubs, downloads-plugin and other hubs (ala-hub, asbp-hub, ozcam-hub, asbp-hub) which use these plugins. 

**Raised by Systems**
- [x] regions-test app is not displaying occurrence and species count

   _Update - Issue was caused by the biocache-service api path [/breakdown](https://api.test.ala.org.au/occurrences/breakdown?q=cl10925%3A%22NEW+SOUTH+WALES%22&fq=rank:(species%20OR%20subspecies)&fq=-occurrence_status_s:absent&fq=geospatial_kosher:true&fq=occurrence_year:*&pageSize=50&fq=occurrence_year:[1850-01-01T00:00:00Z%20TO%202023-12-31T23:59:59Z]&rank=kingdom) from both API Gateway and biocache-ws not returning any data for test and dev instance which indicated the issue would be originating SOLR as both environments use the same SOLR instance._
   
   _Update - FIXED As of 23/06/23 - this API path above has started working again data with any intervention_
   

**Raised Peggy/Data Team**
- [x] Explore your area species listings not working in table: https://biocache-test.ala.org.au/explore/your-area#-37.7897|144.9543|12|Mammals

   _Update - FIXED The API path called by the above page i.e. https://api.test.ala.org.au/occurrences/explore/group/{group} is not returning data as expected - it is returning a 404 instead_

- [x] API link fails due to missing token https://api.test.ala.org.au/occurrences/occurrence/8f2a3b34-67be-46c2-afaa-e4681cc9fc24 

  _Update -  FIXED  The url is not entirely correct - Should be https://api.test.ala.org.au/occurrences/occurrences/8f2a3b34-67be-46c2-afaa-e4681cc9fc24 . The path currently used ```/occurrence/{occurrenceId}```, is deprecated and hence not available on API gateway i.e.` api.test.ala.... `. This fix will be to  update this link to `/occurrences/{occurrenceId} instead.`_

      
- [ ] 404 an old API link - https://biocache-test.ala.org.au/ws/occurrences/8f2a3b34-67be-46c2-afaa-e4681cc9fc24

   _Update - It appears that `/ws/` on biocache hub is no longer being proxied to biocache-service. The direct path to biocache-service  https://biocache-ws-test.ala.org.au/ws/occurrences/8f2a3b34-67be-46c2-afaa-e4681cc9fc24 will work but it  recommended that  this link be used instead: https://api.test.ala.org.au/occurrences/occurrences/8f2a3b34-67be-46c2-afaa-e4681cc9fc24 where/when  possible_
      
- [x] Downloads page says "Did you know the Atlas of Living Australia provides a number of pre-generated downloads for common search queries (e.g. all plants, mammals, birds, insects, etc.)? View all pre-generated downloads." We don't pre-generate downloads.

   _Update - FIXED  Updated config to no longer include the text in downloads page_
  
- [x] Biocache UI - facet csv download 500 error (to replicate: from biocache occurrence list, select Kingdom | choose more, then click the download button from the table modal https://biocache-test.ala.org.au/occurrences/facets/download?q=occurrence_date%3A%5B2020-07-20T00%3A00%3A00Z%20TO%202020-07-30T00%3A00%3A00Z%5D&qualityProfile=ALA&facets=species_group 

     _Update - FIXED  Updated the biocache-service api called by the above endpoint on API gateway to prevent non-required authorization check on [/occurrences/facets/download](https://docs.test.ala.org.au/openapi/index.html?urls.primaryName=occurrences#/Download/downloadFacet)_

**Comment by adam-collins** [comment]
This version was released.
