### ISSUE TITLE
Facet labels not showing correctly in Biocache hubs (incl AVH, ASBP, OZCAM)

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/biocache-hubs#573]
Several facet labels under 'location' category menu are not appearing with their correct name.
This is occurring across ALA, AVH, ASBP and OZCAM.

See screenshots below:

![Image](https://user-images.githubusercontent.com/90439797/252858606-191bead6-d1dc-46bc-aedc-f3e23439231b.png)

![Image](https://user-images.githubusercontent.com/90439797/252858852-2e9a7bd3-f716-4980-adf0-1bd160b5e16e.png)

**Comment by adam-collins** [comment]
pull request https://github.com/AtlasOfLivingAustralia/biocache-hubs/pull/574

**Comment by adam-collins** [comment]
Hubs is requesting `https://api.ala.org.au/occurrences/facets/i18n_en_AU`. When this is fixed it should partially work.

**Comment by sughics** [comment]
Gateway has been updated: https://github.com/AtlasOfLivingAustralia/aws-apig-cognito/commit/d7a814237a93d28f0b732837b7975deb1c59622b
Issue is resolved.
