### ISSUE TITLE
Can't download map as image file from Biocache search

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/biocache-hubs#575]
When searching in Biocache, it is not currently possible to download a map of occurrences - the dialog box appears as expected, but clicking the "Download map" button does nothing - no file is created or downloaded, the box remains as if nothing was clicked.

The same behaviour is happening in AVH.

The "Base Layer" option appears to show an empty list, so possibly this list failing to load is also causing the image to fail to generate.

![Image](https://user-images.githubusercontent.com/57081387/255783029-fba1ec49-16e0-451d-9796-5b70e770b4c5.png)

Reported in:
https://support.ehelp.edu.au/a/tickets/181212
https://support.ehelp.edu.au/a/tickets/181305
https://support.ehelp.edu.au/a/tickets/181380
https://support.ehelp.edu.au/a/tickets/185472 as AVH issue
https://support.ehelp.edu.au/a/tickets/188994 as AVH issue
https://support.ehelp.edu.au/a/tickets/193037
https://support.ehelp.edu.au/a/tickets/198635 as AVH issue

**Comment by sughics** [comment]
@adam-collins   - issue seems to be potentially related to spatial-service?

**Comment by adam-collins** [comment]
Fixed on test. 

Disabled gateway usage as it is missing too many services.

**Comment by adam-collins** [comment]
pull request https://github.com/AtlasOfLivingAustralia/biocache-hubs/pull/587

**Comment by kylie-m** [comment]
Flagged by another user today - https://support.ehelp.edu.au/a/tickets/193037

I just tried on biocache-test, can confirm the download is working
