### ISSUE TITLE
User unable to respond to assertions (cannot see 'verify this assertion' button)

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/biocache-hubs#579]
Hi all. I'm trying to finally nail down the question of giving someone access to respond to assertions in biocache. 

I worked with this on Sushant and he established that all a user needs is ROLE_COLLECTION_ADMIN added in userdetails and to log out and in, however I currently have a user with that role who can't see the Verify this assertion button on a record. 

Testing with my own gmail account (https://auth.ala.org.au/userdetails/admin/user/show/89299), despite giving it the same role, I can't see that button either.

This is to get someone responding to assertions in the iNaturalist dataset (example record is https://biocache.ala.org.au/occurrences/b0c22061-b3e9-4223-883c-1fc81b6e2862), so not a museum collection, but I can see the Verify button using my own regular admin account on an iNat record, so I don't think that's going to be an issue (ie it's not hardcoded to only work with museum records or something).

My next thought is that some cache needs to be cleared somewhere, but I'm hesitant to go clearing caches willy-nilly to try and work it out.

- raised by @timhicks-ALA

**Comment by adam-collins** [comment]
It also appears that the login bug is a problem here. i.e. it says you are logged in but are not. I resolved this by:
- opening the occurrence page https://biocache.ala.org.au/occurrences/b0c22061-b3e9-4223-883c-1fc81b6e2862
- Clicking logout, this took me to the search page.
- Clicking logout again, this just refreshed the search page.
- Clicking login and logging in.
- opening the occurrence page again https://biocache.ala.org.au/occurrences/b0c22061-b3e9-4223-883c-1fc81b6e2862

I have been able to reproduce this issue, showing logged in when not, by:
- opening [biocache.ala.org.au](http://biocache.ala.org.au/) and clicking logout until it says login
- open [bie.ala.org.au](http://bie.ala.org.au/) and clicking logout until it says login
- in [bie.ala.org.au](http://bie.ala.org.au/) click login and login
- opening the occurrence page https://biocache.ala.org.au/occurrences/b0c22061-b3e9-4223-883c-1fc81b6e2862
- it now says you are logged in but you will not see the buttons.

**Comment by peggynewman** [comment]
@adam-collins is this is the same problem that causes us only sometimes see our Edit button on the collectory pages?

**Comment by adam-collins** [comment]
This is fixed now. It was a configuration issue. Ansible is updated.
