### ISSUE TITLE
Faceting a second time can fail when you CHOOSE MORE...

### ISSUE THREAD

**Issue by mbohun** [AtlasOfLivingAustralia/biocache-hubs#58]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=573
*date:* Mon Feb 10 15:08:03 2014
*author:* john.t...@austmus.gov.au
 ---

This is a BioCache problem with a second facet. If you choose a facet from the drop down list (CHOOSE MORE...), when a facet is already chosen you can get two different results, one of which is wrong.

Step 1. 
Search for something eg penguins
[http://biocache.ala.org.au/occurrences/search?taxa=penguins#tab_recordsView](http://biocache.ala.org.au/occurrences/search?taxa=penguins#tab_recordsView)

Step 2.
Facet on an area, eg New South Wales
[http://biocache.ala.org.au/occurrences/search?q=penguins&fq=state:%22New%20South%20Wales%22#tab_recordsView](http://biocache.ala.org.au/occurrences/search?q=penguins&fq=state:%22New%20South%20Wales%22#tab_recordsView)

Step 3. This works
Facet on a species | CHOOSE MORE
Eudyptes pachyrhynchus 12 (Tick the box)  *** ticking the box makes it work 
INCLUDE selected items in search
[http://biocache.ala.org.au/occurrences/search?q=penguins&fq=state%3A%22New+South+Wales%22&fq=species:%22Eudyptes%20pachyrhynchus%22#tab_recordsView](http://biocache.ala.org.au/occurrences/search?q=penguins&fq=state%3A%22New+South+Wales%22&fq=species:%22Eudyptes%20pachyrhynchus%22#tab_recordsView)
(12 ersults)

Step 3 in a different way. This doesn't work
Facet on a species | CHOOSE MORE
Eudyptes pachyrhynchus 12 (DON'T tick the box)  *** this will fail
[http://biocache.ala.org.au/occurrences/search?q=penguins&fq=state%253A%2522New+South+Wales%2522&fq=species:%22Eudyptes%20pachyrhynchus%22#tab_recordsView](http://biocache.ala.org.au/occurrences/search?q=penguins&fq=state%253A%2522New+South+Wales%2522&fq=species:%22Eudyptes%20pachyrhynchus%22#tab_recordsView)
(296 results)
*** note that the filter for New South Wales has disappeared

**Comment by nickdos** [comment]
Was fixed some time in past.
