### ISSUE TITLE
Repeating species with incorrect record counts after "Show more species" in Explore Your Area

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/biocache-hubs#589]
Issue can be replicated with this example location: https://biocache.ala.org.au/explore/your-area#-31.7083|152.2204|11|ALL_SPECIES

1. Load the page and scroll to the bottom of the list shown. Note the Pied Butcherbird at #44 in the list, with 24 records.
2. Click "Show more species" and scroll down slightly. Note the Pied Butcherbird reappears at #55, this time with 28 records (note also the jump in records from #50 to #51).

Other species are repeated in the attached screenshots - see the Prickly Raspfern at #42 and #52, the Crabapple at #98 and #104, and the Red-necked Wallaby at #96 and #103.

The record counts also seem to be incorrect. The Pied Butcherbird shows 24 or 28 records, but there are 32 in Biocache with the data profile off (click the "list of records" to replicate the search in Biocache). The Crabapple shows 16 and 18 in EYA, but 21 in Biocache. It's possible EYA uses a slightly different filter or search, and so comes up with slightly different numbers of records to Biocache for the same search, but at least one number shown in EYA is wrong when a species is duplicated across a "Show more species" fold.

![Image](https://github.com/AtlasOfLivingAustralia/biocache-hubs/assets/57081387/6676fa84-6491-4fc8-bff7-522a34cd3842)
![Image](https://github.com/AtlasOfLivingAustralia/biocache-hubs/assets/57081387/88643f58-e255-4645-a209-f4262eb5943e)

Originally raised in https://support.ehelp.edu.au/a/tickets/190102

**Comment by adam-collins** [comment]
It is a performance tradeoff.  The implication of '24' or '28' or '31' in this context has little meaning and therefore is lower priority for accuracy. Sorting and pagination are relatively expensive for faceting. For the purposes of 'explore your area' it might be more worthwhile to query all species in the facet given the small area in the query (up to 10km radius).

**Comment by adam-collins** [comment]
The most appropriate solution is to fetch all result rather than using paging. This means one less button on the screen. Lists are not too long so browsers should be able to handle it.

**Comment by adam-collins** [comment]
Related to #592

**Comment by adam-collins** [comment]
Closing, refer to #592
