### ISSUE TITLE
Institution/Collection drop down

### ISSUE THREAD

**Issue by mbohun** [AtlasOfLivingAustralia/biocache-hubs#59]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=594
*date:* Sun Feb 23 20:50:02 2014
*author:* natasha....@csiro.au
 ---

The institution and collection drop down does not use generic collectory associations to group them together.  It relies on a naming relationship between the collection and institution. 

For example
"Museum Victoria Entomology Collection" is associated with the Museum Victoria institution based on a prefix. 

I am assuming that the custom code was written with OZCAM in mind.

I am not sure that we have all the WS's that we need from the collectory to support this.   The collections listing does not supply the corresponding institution:
[http://collections.ala.org.au/ws/collection.json](http://collections.ala.org.au/ws/collection.json)

Neither does the complete institution listing:
[http://collections.ala.org.au/ws/institution.json](http://collections.ala.org.au/ws/institution.json)

But it is available in the individual institution lookup:
[http://collections.ala.org.au/ws/institution/in6](http://collections.ala.org.au/ws/institution/in6)

**Comment by nickdos** [comment]
This seems to be a non-issue ATM. No one has complained the drop-down in the advanced search is wrong. There might be a time where this association fails but for now it works.
