### ISSUE TITLE
Explore Your Area UI issue when sorting by Common or Scientific Name

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/biocache-hubs#592]
A user has reported minor issues with the Explore Your Area UI:
(Example URL: https://biocache.ala.org.au/explore/your-area#-35.2802|149.1310|12|ALL_SPECIES)

1. Clicking the "Scientific Name" header sorts by the number of records, not by name.
2. Clicking the "Common Name" header does sort by common name, but sometimes the screen seems to flash and it changes to sorting by Scientific Name instead. Clicking on each header in turn a few times reliably reproduces this behaviour.

This behaviour has been replicated in Chrome and Edge.

In terms of sorting by each type of name, there is a workaround to download a species checklist from the page and sort data offline.

Reported in:
https://support.ehelp.edu.au/a/tickets/181673
https://support.ehelp.edu.au/a/tickets/180896
https://support.ehelp.edu.au/a/tickets/182486
https://support.ehelp.edu.au/a/tickets/187323
https://support.ehelp.edu.au/a/tickets/193527
https://support.ehelp.edu.au/a/tickets/197834

**Comment by adam-collins** [comment]
I did have a 2nd thought that this should get the entire list to avoid paging artefacts.

**Comment by adam-collins** [comment]
Depends on biocache-service 3.5.0 for performance see https://github.com/AtlasOfLivingAustralia/biocache-service/issues/877
