### ISSUE TITLE
Ordering of page content versus menu

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/biocache-hubs#597]
On occurrence records that are referenced in publications, the order of the menu and order of the actual content on page doesn't match.

For example, on these records:
https://biocache.ala.org.au/occurrences/e4dd29c2-c3f3-415e-b950-f21b2557a3e4
https://biocache.ala.org.au/occurrences/e85df77c-cc54-40b4-8184-211ad02a1a25
https://biocache.ala.org.au/occurrences/e991c3c0-d6b7-4224-8e25-39a98389fa54
https://biocache.ala.org.au/occurrences/ed3c227c-0f2b-4327-8ce8-805b4c4b6f49

The section menu shows "Data quality tests" before "Referenced in publications"

![Screenshot 2024-03-21 at 10 42 39 am](https://github.com/AtlasOfLivingAustralia/biocache-hubs/assets/90439797/356711c0-e9a0-4f7e-8832-d4a93e84f5cc)

But the page content displays the "Referenced in publications" section before the "Data quality tests" section.

![Screenshot 2024-03-21 at 10 46 05 am](https://github.com/AtlasOfLivingAustralia/biocache-hubs/assets/90439797/71db4aa2-c741-42e7-987e-0b898619b8ac)

It would be ideal to match the ordering of these to enhance clarity/usability for our users.

**Comment by adam-collins** [comment]
Fixed the order of the section menu. Test on biocache-test, ozcam-test, avh-test.

**Comment by kylie-m** [comment]
Tested and passed 

- ordering of menu is correct, and links working normally on biocache-test, ozcam-test, avh-test, examples below:

- https://biocache-test.ala.org.au/occurrences/e85df77c-cc54-40b4-8184-211ad02a1a25#dataQuality
- https://ozcam-test.ala.org.au/occurrences/ed3c227c-0f2b-4327-8ce8-805b4c4b6f49
- https://avh-test.ala.org.au/occurrences/fbf588f8-b754-4445-9bd6-475b18694b30
