### ISSUE TITLE
Conservation status facet not reflecting species status

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/biocache-hubs#60]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=597
*date:* Tue Feb 25 19:13:40 2014
*author:* leebel...@gmail.com
 ---

Add to Map | Species | Mogurnda clivicola

This species is listed as "Vulnerable" (AU) in the species page but not in the facets.

State conservation
State conservation status (unprocessed)

This seems to imply that a species listed under the EPBC act will not reflect in either of the two conservation status facets? If so, not nice.

This issue was raised by a user from SA (via Robyn Lawrence) who was attempting to find out what fish species in SA had a conservation status.

Apparently there are 16 fish species in SA with some conservation status while the ALA reports 2 as far as I can tell. If I use the SP to facet on lifeform=fish, area=SA with coastal zone, conservation=some status I get 2.

I assume it is a biocache issue.

**Comment by nickdos** [comment]
I can't make sense of this issue but it appears to be biocache-service related.

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/biocache-service#24
