### ISSUE TITLE
Data profile is not saved

### ISSUE THREAD

**Issue by yasima-csiro** [AtlasOfLivingAustralia/biocache-hubs#600]
Biocache data profile is not saved in test.

Steps to reproduce:
1. Go to biocache-test
2. Search for a species
3. Click on settings -> choose a data profile -> save
4. Next login doesn't show the saved the data profile. 

Note: userdetails save property API requires users/write permission.

**Comment by adam-collins** [comment]
Ideally we would send the user JWT and it would be enough to change the user's profile data. Asking if this can be added to userdetails before creating an issue there.

Adding users/write permissions to the JWT machine-to-machine gets past authentication but now there is a new error, presumably only for AWS Cognito, `Member must have length less than or equal to 20 (Service: AWSCognitoIdentityProvider`. Waiting to hear back on this as well.

**Comment by adam-collins** [comment]
Can be tested at biocache-test.
1. Do a search to bring you to the search result page that has the data quality filters.
2. Login, if not already.
3. Click on the data quality settings icon, on the right.
4. Select a different data quality profile.
5. Click save. This will test the saving of a property. Browser developer tools should have no error.
6. Open a new tab.
7. Do another search to bring you to the search result page.
8. This page will have the saved data profile selected. This tests the retrieval of the property.

**Comment by kylie-m** [comment]
This is working well for me, including no console errors on save (#5). Also works after logging out and back in.
