### ISSUE TITLE
Occurrence page processed values are not always split as expected

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/biocache-hubs#602]
The processed recordedByID is not is not split when `value|value`. It is expected to be split in the same way as a raw recordedByID `value | value`. 

For example https://biocache-test.ala.org.au/occurrences/1f1c4c09-3788-4c8a-ad10-27246d6c67f0

This splitting of raw and processed fields is probably generic and applies to other fields as well.

I think the data is from https://biocache-ws-test.ala.org.au/ws/occurrences/compare/1f1c4c09-3788-4c8a-ad10-27246d6c67f0.

**Comment by adam-collins** [comment]
Probably only an issue when there are multiple URLs that fail to split because the `a` tag created is then wrong.

**Comment by kylie-m** [comment]
Hi Adam, looks good to me on the UI - spaces are coming through on the main record pages below: 
https://biocache-test.ala.org.au/occurrences/1f1c4c09-3788-4c8a-ad10-27246d6c67f0
https://biocache-test.ala.org.au/occurrences/a2cc12f8-7eb3-4216-8b57-2932bed5cbe3

FYI in the `Compare "original vs processed" values` modal, I noticed the processed values don't have spaces, eg "https://www.wikidata.org/wiki/Q108765728|https://orcid.org/0000-0001-7368-013X"

**Comment by adam-collins** [comment]
I think it is acceptable to present the "original vs processed" without additional interpretation. This is consistent with other comparison values displayed.
