### ISSUE TITLE
Taxa 'Group' in Explore Your Area is showing incorrect taxa

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/biocache-hubs#604]
The [Ferns and allies] Group in Explore Your Area is showing kangaroos and birds and frogs as well as plants. This is also happening on biocache-test.

![explore-your-area](https://github.com/AtlasOfLivingAustralia/biocache-hubs/assets/90439797/36280032-3df2-4ea3-ab64-60f09ffe52c3)

Other Groups appear to be filtering correctly. 

Steps to reproduce the issue:

1. [Explore Your Area](https://biocache.ala.org.au/explore/your-area)
2. Search for a location and allow results to finish loading
3. Click on "[Ferns and allies]"
4. Check Common Name and Scientific Name of results listed – this group is including other taxa such as birds

Add on steps
5. Click on a different Group to check search results
6. Allow time for the results to fully load
7. Click on [Ferns and allies] again and see if results are still incorrect

It's happening for me on Chrome, Firefox and Safari

cc @timhicks-ala

**Comment by adam-collins** [comment]
Other than interacting with the page and looking at results, this URL can be used for testing https://biocache-test.ala.org.au/explore/your-area#-35.3515|149.2330|12|Ferns%20and%20allies. Prod shows "loading..." and does not update, test does update and selects the expected "Ferns and allies" in the left hand side list.

**Comment by kylie-m** [comment]
I'm getting the page stuck on "loading" for all of the larger groups (1000+), such as All species, Animals, Plants. Other than this, explore your area is working well

**Comment by kylie-m** [comment]
Retest has passed, functioning well for all groups, including those larger groups

**Comment by nickdos** [comment]
Deployed in version 7.1.0.
