### ISSUE TITLE
update iNat /people/ link to use userId instead of userName

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/biocache-hubs#607]

**Comment by adam-collins** [comment]
for testing https://biocache-test.ala.org.au/occurrences/7563b168-57cb-4970-9b3a-a4585e4b8db6

**Comment by kylie-m** [comment]
That's working for me, plus a few others I checked too

**Comment by peggynewman** [comment]
Probably need to also check that the inat query from a user profile is still working. I can't check because the link to inaturalist function doesn't work in test
https://aws-auth-test-2023.test.ala.org.au/userdetails/myprofile/
... but the links user details creates are 
https://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr1411&fq=alau_user_id:peggydnew
and
https://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr1411%20OR%20data_resource_uid:dr364&fq=alau_user_id:peggydnew%20OR%20alau_user_id:%2219807%22
So I think that's fine ... my records look better in test as well

**Comment by sadeghim** [comment]
Also, looking at the `Original vs Processed`, userID is not transferred to the processed column:
![image](https://github.com/user-attachments/assets/b1c7bead-5be9-472c-aab9-bf815f8b9252)

**Comment by adam-collins** [comment]
@sadeghim to my understanding, userId is not processed by the pipelines so there will only be the field `userId`, not `raw_userId and userId`. 
1. If you want to change how pipelines works please create a new issue in biocache-service with the prefix `pipelines - ` and describe the changes that are required.
2. If you want to change a single field in `/occurrences/compare/{uuid}` please create an issue in biocache-service with details. Note that this service provides the data for "Original vs Processed" section, please raise an issue with details in biocache-service.

**Comment by sadeghim** [comment]
@adam-collins I think, there is no need to change the logic of the pipelines. And that `userId` can stay as is since there is no real transformation to it.

**Comment by adam-collins** [comment]
@peggynewman is that what you mean?
1. user details links to biocache-service are working in production
2. you cannot link a user test account to an inaturalist account
3. user details URLs to biocache-service for inaturalist cannot be tested because you cannot link a user test account to an inaturalis account

Continuing with these assumptions
- `userName` SOLR field is (was) suitable for use as links to iNaturalist of the form `/people/{userName}`. 
- This is now `/people/{userId}`. This informs me that it is likely that the `userName` contents changed or the `/people/{user}` address operation changed or it has never worked.
- The links from userdetails (prod), that you provided, list the user filter as `alau_user_id` that is now an alias of `userId`.
- The filter for dr1411 in the example is `alau_user_id:peggydnew`.
- For iNaturalist data that we receive have the `userId` field contents change? If yes, how. If no, then userdetails will not need a change as long as userIds stored in userdetails has not changed. Given that production is still working this is likely the case.
- The filter for dr364 in the example is `alau_user_id:"19807"`. Given that this an ALA ID this URL is still correct unless biocollect changed the contents of the `userId` field. Please add a comment with details if that is the case.

**Comment by peggynewman** [comment]
Let me comment on these individually:

> 1. user details links to biocache-service are working in production

yes, on the basis that the query is `fq=alau_user_id:peggydnew` 

> 2. you cannot link a user test account to an inaturalist account
> 3. user details URLs to biocache-service for inaturalist cannot be tested because you cannot link a user test account to an inaturalis account

correct, inat does not have the test environment for OAUTH2, but you can just mangle the URL to see if it will work

> userName SOLR field is (was) suitable for use as links to iNaturalist of the form /people/{userName}.
> This is now /people/{userId}. This informs me that it is likely that the userName contents changed or the /people/{user} address operation changed or it has never worked.

Don't ever remember userName being working in production. I remember it not working in production and we had to fix it in the past few years. userName is full of spaces and can change, whereas userID is an iNaturalist user name that uniquely identifies them in the system and does not change. When this facility has not worked, people complain through the help desk so I am assuming that this is something that has recently gone wrong.

>The links from userdetails (prod), that you provided, list the user filter as alau_user_id that is now an alias of userId.
The filter for dr1411 in the example is alau_user_id:peggydnew.

Yes, and that is my userId, not my userName. My userName is Peggy Newman and I can change that anytime to Datarey McDataface. 

> The filter for dr364 in the example is alau_user_id:"19807". Given that this an ALA ID this URL is still correct unless biocollect changed the contents of the userId field. Please add a comment with details if that is the case.

I thought it was weird that when we did this, we repurposed the alau_user_id field and as far as I understand, biocache knows that this field contains userIDs for both the ALA and iNaturalist.

**Comment by timhicks-ala** [comment]
(helpdesk note: raised in https://support.ehelp.edu.au/a/tickets/207168)
