### ISSUE TITLE
Regions app download doesnt contain dataResourceUid

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#61]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=601
*date:* Tue Mar  4 20:31:28 2014
*author:* moyesyside
 ---

Regions app download doesnt contain dataResourceUid

**Comment by nickdos** [comment]
Extra fields for downloads can be specified by adding them to the download URL via the appropriate param (see API docs). Moving to regions app.

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/regions#9
