### ISSUE TITLE
Institution name and collection name blanks in downloads when specified

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#62]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=602
*date:* Tue Mar  4 20:36:05 2014
*author:* moyesyside
 ---

[http://biocache.ala.org.au/ws/occurrences/download?q=red+kangaroo&fields=institution_name,collection_name&reasonTypeId=1](http://biocache.ala.org.au/ws/occurrences/download?q=red+kangaroo&fields=institution_name,collection_name&reasonTypeId=1)

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/biocache-service#25
