### ISSUE TITLE
QID issues for creating alerts from specieslists

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#63]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=605
*date:* Wed Mar 12 17:48:06 2014
*author:* moyesyside
 ---

QID issues for creating alerts from specieslists

**Comment by nickdos** [comment]
Can't make sense of this one. Looks like a biocahe-service issue, so moving there,

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/biocache-service#26
