### ISSUE TITLE
Bicache load check for empty files

### ISSUE THREAD

**Issue by mbohun** [AtlasOfLivingAustralia/biocache-hubs#65]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=609
*date:* Thu Mar 13 16:06:10 2014
*author:* natasha....@csiro.au
 ---

Add an extra step that checks for empty files before attempting to load a data resource. 

Particularly important for ANWC because they automatically generate and upload archives that fail.  These ZIP files will contain empty CSV files.

**Comment by djtfmartin** [comment]
This is a biocache store issue. 
Added https://github.com/AtlasOfLivingAustralia/biocache-store/issues/25
Closing
