### ISSUE TITLE
Faceting is inconsistent and the process of identifying candidate contextual layers unknown

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/biocache-hubs#69]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=634
*date:* Wed Apr  9 23:58:26 2014
*author:* leebel...@gmail.com
 ---

1. The ORDERING of geospatial facets appears random (=dog's breakfast):
Uncertainty (in metres)
Sensitive
State conservation
State conservation (unprocessed)
IMCRA (meso-scale)
Local Gov. Area
State/Territory
Country
Biogeographic region
IBRA
IMCRA
Dynamic land cover
Vegetation types - native
Vegetation types - present
Spatial validity

2. NAMING of facets is inconsistent, e.g., the IBRA layers in the SP are named (Add to Map | Layers)-

IBRA 6 Regions
IBRA 6 Sub Regions
IBRA 7 Regions
IBRA 7 Subregions

but in the facets, you have

IBRA

So which IBRA is it? You could find out by mapping all the IBRA layers and checking alignment of points, but this is obtuse.

3. If the IBRA noted above is actually IBRA 6 Regions or Sub Regions, why is it still there when IBRA 7 supersedes it? Therefore, what is the process for deprecating facets? What is the process of identifying and 'loading' a new facet from a new contextual layer?

4. Ideally, a user should be able to facet on non-trivial (e.g., not single polygons of small extent, e.g., GER polygons) CONTEXTUAL non-trivial  layers as this is a powerful filtering mechanism.

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/biocache-service#30
