### ISSUE TITLE
collection picker for the AMRIN advanced search

### ISSUE THREAD

**Issue by mbohun** [AtlasOfLivingAustralia/biocache-hubs#72]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=640
*date:* Wed Apr 16 17:45:33 2014
*author:* milo_nic...@hotmail.com
 ---

From the head of AMRIN - 
I think it would be good to have each collection as a search field as well. This has been done in OZCAM. It is the collection rather than the institution which is linked to specific records and the filters are not so obvious to the new user.

**Comment by nickdos** [comment]
I don't understand this issue - the advanced search allows searching against both institutions and collections... It needs some specific use cases with examples.

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/amrin-hub#1
