### ISSUE TITLE
Standardise assertions across all ALA services

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/biocache-hubs#74]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=650
*date:* Sun Apr 27 15:59:51 2014
*author:* leebel...@gmail.com
 ---

In developing the R library (ALA4R) for interfacing with ALA data, inconsistencies in the assertions have been detected. 

The assertions developed by the ALA are the most significant value-add to the records available - particularly for the research community. 'Data Quality' has remained one of the most significant issues raised by the research community so it is vital that we communicate the assertions in a comprehensive and consistent manner. The intent in ALA4R is to enable users to visualize the assertions associated with a record set. For this to happen, assertions need to be comprehensive and consistent.

There are at least three sources of information related to record assertions in the ALA

1. [http://biocache.ala.org.au/ws/assertions/codes](http://biocache.ala.org.au/ws/assertions/codes)
2. [http://bit.ly/peFILi](http://bit.ly/peFILi)
3. Downloaded records from spatial portal, biocache, ALA4R etc

There needs to be one location where the list of assertions are, and  (extremely important), their definitions can be found. This location should be linked to wherever assertions are exposed. There are currently missing assertions from the list in (2) above and others are not defined.

Assertions need to be a consistently named. At the moment, there are two different sets of names (and maybe more). I'd suggest that the names at [http://biocache.ala.org.au/ws/assertions/codes](http://biocache.ala.org.au/ws/assertions/codes) be used throughout the systems.

As far as I can tell, the assertions appended to downloads are a consistent subset. If it was decided to remove assertions for which ALL records are "FALSE" (as was suggested happens by Dave M), fine - but this may conflict (at least by default) with [Issue #489](https://code.google.com/p/ala/issues/detail?id=489). There is a current maximum of 87 assertions so there is probably a case for removal of 'non applicable' assertions from the records downloads to reduce data volume.

The attached spreadsheet is a summary of the assertions from the three locations noted above. Highlighted cells in the spreadsheet represent missing information, as far as I can tell - without comprehensive definitions.

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/biocache-service#32
