### ISSUE TITLE
Drill down in biocache charts broken for "By collection"

### ISSUE THREAD

**Issue by mbohun** [AtlasOfLivingAustralia/biocache-hubs#75]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=651
*date:* Sun Apr 27 18:48:57 2014
*author:* natasha....@csiro.au
 ---

This is a regression issue. The charts JS needs to take into account the fact that the label has an i18n value. The fq value of the facet should be used to construct the drill down URL.

**Comment by nickdos** [comment]
No URL to test and could relate to any number of charts implementations. I have a feeling this was fixed anyway.
