### ISSUE TITLE
Reproductive Condition facet

### ISSUE THREAD

**Issue by mbohun** [AtlasOfLivingAustralia/biocache-hubs#76]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=653
*date:* Sun Apr 27 20:05:09 2014
*author:* milo_nic...@hotmail.com
 ---

From Climatewatch staff- ... checking some of the plant data from ClimateWatch using the ALA mapping tools. One of the big things to look for is when plants are flowering. This information is stored as ‘Reproductive Condition’ in the ALA record. We were wondering if it’s possible to add a filter the data (like those in the attached screen shot) to only look at different reproductive phases?

**Comment by nielsklazenga** [comment]
Yes, http://rs.tdwg.org/dwc/terms/reproductiveCondition. HISCOM would really like this facet in AVH too (and has just requested it). I have been in a meeting with seed bank and restoration people and they find this information really important as well.

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/biocache-store#75
