### ISSUE TITLE
Occurrence records with invalid layer sampling?

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/biocache-hubs#78]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=659
*date:* Thu May  1 22:17:26 2014
*author:* leebel...@gmail.com
 ---

Summaries of occurrence queries from Kristen Williams are suggesting (serious?) anomalies in the sampling of spatial layers of some records during processing. For example, if a query is constructed on 

Country = n/a AND
IBRA = n/a AND
IMCRA = n/a AND
el884 (bathymetry and elevation) = n/a

it should only return records that occur outside Australia. The following query however

[http://biocache.ala.org.au/occurrences/search?fq=-ibra%3A*&fq=-imcra%3A*&fq=-country%3A*&fq=-el848%3A*&wkt=POLYGON((96.6%20-58.0,159.8%20-58.0,159.8%20-10.5,96.6%20-10.5,96.6%20-58.0))#tab_mapView](http://biocache.ala.org.au/occurrences/search?fq=-ibra%3A*&fq=-imcra%3A*&fq=-country%3A*&fq=-el848%3A*&wkt=POLYGON((96.6%20-58.0,159.8%20-58.0,159.8%20-10.5,96.6%20-10.5,96.6%20-58.0))#tab_mapView) 

produces 40,954 records, most of which ARE in 'Australia' and are terrestrial. 

A few records are marine (correctly or not as I haven't checked yet) but should still be on the bathy/topo layer (and IMCRA). 

There are also a few on offshore islands, which should also be on the bathy/topo layer, if not IMBRA or IMCRA - and they should also be 'Australia' but that may be another issue. 

The WKT (bounding box) here just includes Australia and associated islands. 

PS: Diagnosis of classification of the records would be made easier if `#658` were solved.

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/biocache-store#30
