### ISSUE TITLE
add RightsHolder to the image section of a record details page

### ISSUE THREAD

**Issue by mbohun** [AtlasOfLivingAustralia/biocache-hubs#80]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=669
*date:* Wed May 14 18:04:35 2014
*author:* milo_nic...@hotmail.com
 ---

From the Australian Museum:

I have found one problem with the use of our images - unfortunately the rights information is not shown. The dump I sent included as discussed a "rightsHolder" field (the value of which is always "Australian Museum") but this seems to have been ignored. e.g. in this record:

[http://biocache.ala.org.au/occurrences/481d5e2a-7811-4317-b156-9e9f32c8e96e](http://biocache.ala.org.au/occurrences/481d5e2a-7811-4317-b156-9e9f32c8e96e)

the photographer is mentioned but not the rights holder. I was expecting the rights to be present as in the MV example you gave me earlier (below). Would it be possible to correct this soon please so that the rights for all the images are attributed to Australian Museum?

**Comment by nickdos** [comment]
RightsHolder is in the "Additional Properties" section but should also appear below the photo.
