### ISSUE TITLE
JS 404 import

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#84]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=712
*date:* Sun Jun 22 16:23:47 2014
*author:* moyesyside
 ---

See screenshot:

[https://www.dropbox.com/s/bc6tz100q074ca1/Screenshot%202014-06-23%2009.23.04.png](https://www.dropbox.com/s/bc6tz100q074ca1/Screenshot%202014-06-23%2009.23.04.png)

**Comment by nickdos** [comment]
Still seeing it. Only affects dev tools in Chrome...

**Comment by djtfmartin** [comment]
I'll close this as its benign. Closing

**Comment by nickdos** [comment]
Fixed it.
