### ISSUE TITLE
Column name oddities in occurrences and species download

### ISSUE THREAD

**Issue by mbohun** [AtlasOfLivingAustralia/biocache-hubs#86]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=754
*date:* Thu Jul 10 00:24:16 2014
*author:* antarcti...@gmail.com
 ---

1. If I ask for "matched_name" or "lsid" in my list of fields to be returned, I don't get them back.

(try e.g. [http://biocache.ala.org.au/ws/occurrences/index/download?reasonTypeId=10&q=data_resource_uid:dr356&fields=longitude,lsid,matched_name&qa=none](http://biocache.ala.org.au/ws/occurrences/index/download?reasonTypeId=10&q=data_resource_uid:dr356&fields=longitude,lsid,matched_name&qa=none))

2. If I leave the requested fields as their default values, I get the scientific name in a column called scientificName - all good. But if I actually specify the field "scientificName", I get something with all-lower case names and abbreviated genus:

[http://bie.ala.org.au/ws/download?q=genus:Aptenodytes&fields=scientificName](http://bie.ala.org.au/ws/download?q=genus:Aptenodytes&fields=scientificName)

scientificName
"aptenodytes"
"a. forsteri"
"a. patagonicus"

If I ask for "nameComplete", I get what appears to be the correct scientific name.

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/biocache-service#34
