### ISSUE TITLE
Distance outside expert range should be expressed in KM

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/biocache-hubs#87]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=616
*date:* Thu Mar 20 16:52:14 2014
*author:* leebel...@gmail.com
 ---

At the moment, the record details don't state what the UNIT is when reporting "Distance outside expert range". It appears to be metres? I'd suggest km.

![capture 2](https://cloud.githubusercontent.com/assets/1772897/3976196/226ae014-281b-11e4-8117-7932e407eb24.jpg)

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/biocache-service#35
