### ISSUE TITLE
Missing i18n labels/values

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#89]
On facet column "choose more" popup, the INCLUDE selected items and EXCLUDE selected items buttons are not translated for the ZH lang.

See: 
![i18n-screenshot](https://cloud.githubusercontent.com/assets/532845/3990439/e7616978-28cb-11e4-863e-88d6ff3d2cc7.png)

**Comment by santiagomrv** [comment]
I have solved this issue. I hope do the PR this week.
![captura de pantalla 2016-10-29 a las 19 33 31](https://cloud.githubusercontent.com/assets/22981165/19831613/c99319d6-9e0e-11e6-8717-2ce50b653747.png)

**Comment by nickdos** [comment]
Thanks @santiagomrv
